DOC-199 aggiunta della figura del programmatore nel preventivo del quarto sprint
Error-418-SWE/Documenti pull request #104
Opened 2023-12-14 19:59 UTC by SilvioNardo

### Note
Aggiunta la richiesta di revisione da parte del responsabile in quanto la modifica è concettualmente importante

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-14 20:31 UTC, TodescoMattia approved these changes

2023-12-16 08:18 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- *Verificatore*: al fine di verificare la correttezza delle modifiche ai documenti, al fine di effettuare un controllo sulla validità e formulazione degli use case individuati e del documento di Ana
Ripetizione di “al fine”

2023-12-16 08:20 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- *Verificatore*: al fine di verificare la correttezza delle modifiche ai documenti, al fine di effettuare un controllo sulla validità e formulazione degli use case individuati e del documento di Ana
Mettere il punto alla fine dell’elenco puntato

2023-12-16 08:21 UTC, Carraro-Riccardo requested changes
Giusto un paio di correzioni, per il resto bene bene.

2023-12-17 20:40 UTC, Carraro-Riccardo approved these changes

2023-12-17 20:41 UTC, merged