DOC-239 caricamento verbale 23-12-15
Error-418-SWE/Documenti pull request #106
Opened 2023-12-15 22:41 UTC by SilvioNardo

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-16 14:31 UTC, TodescoMattia requested changes
buono! poche cose da cambiare

2023-12-16 14:31 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- feature del PoC;
direi dei*

2023-12-16 14:31 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- Next.js
manca ;

2023-12-16 14:31 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- è emersa l'importanza di precaricare dal database una parte dei dati delle merci così da poter mostrare a schermo informazioni di base come quali sono i bin occupati ma le restanti informazioni del
dividerei la frase con un punto (o una virgola almeno) se no è troppo lunga

2023-12-16 14:31 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- non è richiesto ma è desiderabile poter creare scaffali conteneti piani di altezze diverse;
typo su contenenti

2023-12-16 14:31 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- in assenza di API, le loro iterrogazioni possono essere simulate con risposte randomiche.
Lo riscriverei indicando che l'azienda non ce le fornisce (come sono implementate almeno) e quindi noi simuliamo e basta

2023-12-16 14:31 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +A causa delle festività natalizie questo è stato l'ultimo meeting esterno previsto per l'anno 2023. Il prossimo incontro è previsto per gli inizi del mese di gennaio quando lo stato dei lavorì sarà p
accento sulla i di lavori

2023-12-17 09:43 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +    (name: "Alberton Michela", role: "Referente aziendale"),
Non sono referenti, semmai "Partecipante esterno" o qualcosa del genere

2023-12-17 09:49 UTC, ggardin requested changes

2023-12-17 09:49 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Ai referenti aziendali sono stati esposti gli avanzamenti svolti sui PoC rispetto al precedente meeting esterno e sono sorte discussioni relativamente a:
sono stati esposti ~gli avanzamenti svolti~ _i progressi_ sui PoC

2023-12-17 09:49 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Relativamente ai PoC da realizzare in fututro e alla luce delle conoscenze acquisite, sono emersi con il proponente le seguenti considerazioni:
*emerse

2023-12-17 09:49 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- è emersa l'importanza di precaricare dal database una parte dei dati delle merci così da poter mostrare a schermo informazioni di base come quali sono i bin occupati ma le restanti informazioni del
In più si ripete 
``` md
sono emerse le seguenti considerazioni:
- è emersa ...
```

2023-12-17 09:49 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- il piano inferiore degli scaffali è verosimile che coincida con il pavimento dell'area di lavoro;
"- è verosimile che il piano inferiore ..."

2023-12-17 20:17 UTC, ggardin approved these changes

2023-12-17 21:12 UTC, ggardin requested changes

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Ai referenti aziendali sono stati esposti i progressi sui PoC rispetto al precedente meeting esterno e sono sorte discussioni relativamente a:
Il referente aziendale è uno solo. Rimuoverei in toto l'incipit della frase, tanto è sottointeso chi siano gli interlocutori

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Non sono stati identificati particolari vincoli sulle performance.
Bisognerebbe anche dire che abbiamo parlato dei requisiti non funzionali identificati

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +È richiesta la compatibilità dell'applicazione almeno con i browser:
Scritta così sembra una richiesta esplicita del Proponente, in realtà bisogna far capire che questi requisiti li abbiamo identificati noi sulla base dei requisiti minimi hardware e software richiesti per l'esecuzione di WebGL

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- Firefox;
Mancano i numeri di versione dei browser

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Inoltre sono approvati ma non richiesti l'utilizzo di WebGL e la compatibilità dell'applicativo con i browser sopracitati versione mobile.
WebGL lo usiamo per forza perché senza di quello Three non gira

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +I dispositivi su cui sarà eseguita l'applicazione sono normali PC Desktop verosimilmente presenti in uffici ed eventualmente dispositivi tablet.
- Dispositivi _tipici_
- Il doppio avverbio non mi piace

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- PostgreSQL.
PostgreSQL al posto di MySQL, che inizialmente era la tecnologia individuata

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- è importante precaricare dal database una parte dei dati delle merci così da poter mostrare a schermo informazioni di base, per esempio quali sono i bin occupati. Le restanti informazioni delle sin
Non "necessitano", ma "possono essere reperite blablabla"

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- non è richiesto ma è desiderabile poter creare scaffali contenenti piani di altezze diverse;
~non è richiesto ma~ (che non sia richiesto viene dal fatto che è desiderabile)

2023-12-17 21:12 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +A causa delle festività natalizie questo è stato l'ultimo meeting esterno previsto per l'anno 2023. Il prossimo incontro è previsto per gli inizi del mese di gennaio quando lo stato dei lavori sarà p
- ~questo è stato l'ultimo meeting~ non sono previsti ulteriori incontri per l'anno 2023.
- RTB non è una faseeeeee! Attenzione

2023-12-17 21:44 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- Firefox;
io ho riportato i vincoli dei browser in base a quanto approvato dal dialogo con il proponente, alla domanda lui non ha specificato una versione a parte per chrome

2023-12-17 22:22 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +È richiesta la compatibilità dell'applicazione almeno con i browser:
io ho riportato la richiesta del proponente in seguito alle considerazioni fatte assieme

2023-12-17 22:23 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Inoltre sono approvati ma non richiesti l'utilizzo di WebGL e la compatibilità dell'applicativo con i browser sopracitati versione mobile.
non so, il proponente aveva detto che non era richiesto mi pare e io ho riportato le conclusioni tratte nel meeting

2023-12-17 22:24 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +I dispositivi su cui sarà eseguita l'applicazione sono normali PC Desktop verosimilmente presenti in uffici ed eventualmente dispositivi tablet.
a me sembra funzionare la frase che ho scritto, puoi fare un esempio esplicito della tua proposta?

2023-12-17 23:47 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +I dispositivi su cui sarà eseguita l'applicazione sono normali PC Desktop verosimilmente presenti in uffici ed eventualmente dispositivi tablet.
lascio un mio suggerimento: "L'applicazione sarà ottimizzata per l'esecuzione su comuni PC desktop, tipicamente utilizzati negli ambienti d'ufficio, garantendo al contempo la compatibilità con dispositivi tablet."

2023-12-18 09:59 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +È richiesta la compatibilità dell'applicazione almeno con i browser:
Allora non è chiaro

2023-12-18 10:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +È richiesta la compatibilità dell'applicazione almeno con i browser:
In realtà, trattandosi di requisiti non funzionali, non emergono direttamente dal confronto con proponente, ma bensì sono frutto di analisi nostre. Come dicono Tullio e Cardin, tutti siamo capaci di individuare i requisiti funzionali (che emergono anche dal capitolato o con il Proponente stesso), ma tutta la parte di non funzionali è studio nostro come gruppo. Pertanto, l'individuazione delle versioni dei software non è corretto dire che è stato il proponente ad individuarle, ma bensì ha semplicemente confermato quanto avevamo individuato nella nostra analisi dei requisiti.

2023-12-18 10:02 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- Firefox;
Come nel commento precedente, i proponente può al massimo confermare quanto da nooi individuato in merito alle versioni. Si è parlato di Chrome, è vero, ma nella nostra analisi sono già presenti anche le versioni minime per gli altri browser.

2023-12-18 10:04 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Inoltre sono approvati ma non richiesti l'utilizzo di WebGL e la compatibilità dell'applicativo con i browser sopracitati versione mobile.
WebGL è un componente fondamentale che permette l'utilizzo di librerie come Three.js, pertanto, non è _opzionale_ o _desiderabile_ il suo utilizzo, bensì è intrinseco nell'utilizzo di Three.js stesso, come requirements software del browser.

2023-12-18 13:46 UTC, TodescoMattia requested changes

2023-12-18 13:46 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Durante il meeting sono state discusse ulteriormente le tecnologie impiegate e in programma per una futura implementazione, in particolare è stato approvato da parte del proponente l'utilizzo di:
Proponente*

2023-12-18 13:46 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Relativamente ai PoC da realizzare in fututro e alla luce delle conoscenze acquisite, sono emerse con il proponente le seguenti considerazioni:
Proponente*

2023-12-20 01:43 UTC, TodescoMattia approved these changes

2023-12-20 08:10 UTC, ggardin requested changes

2023-12-20 08:10 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +In seguito all'utilizzo delle tecnologiche da noi individuate, in particolar modo per la libreria Three.js, è necessario che i browser interessati dispongano di una versione minima atta a supportare
- ~In seguito... utilizzo~ Per adottare le tecnologie da noi individuate
- I browser non dispongono di una versione minima, siamo noi a definirle
- Doppio spazio dopo "mediante"

2023-12-20 08:10 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +\
Rimuovere la linea

2023-12-20 08:10 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Desiderabilmente è previsa la compatibilità dell'applicativo con i browser sopracitati versione mobile.
Prevista

2023-12-20 08:10 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +- Docker;
Docker Compose

2023-12-20 08:10 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +Relativamente ai PoC da realizzare in fututro e alla luce delle conoscenze acquisite, sono emerse con il Proponente le seguenti considerazioni:
*futuro

2023-12-20 13:37 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Verbali/23-12-15/23-12-15.typ
> +\
si indenta male senza

2023-12-21 12:02 UTC, ggardin approved these changes

2023-12-21 12:03 UTC, merged