Doc 279 correzione verbale 23 12 17
Error-418-SWE/Documenti pull request #110
Opened 2023-12-17 22:41 UTC by SilvioNardo

### Note
le conversation relative agli errori corretti si trovano a: https://github.com/Error-418-SWE/Documenti/pull/109

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-17 23:44 UTC, TodescoMattia requested changes

2023-12-17 23:44 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- due membri lavoreranno ai PoC: il programmatore si impegnerà nell'integrazione dei PoC minori in un singolo PoC principale, mentre il membro del gruppo asseganato al ruolo di verificatore proseguir
Programmatore*

2023-12-17 23:44 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- due membri lavoreranno ai PoC: il programmatore si impegnerà nell'integrazione dei PoC minori in un singolo PoC principale, mentre il membro del gruppo asseganato al ruolo di verificatore proseguir
Verificatore*

2023-12-17 23:44 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- due membri lavoreranno ai PoC: il programmatore si impegnerà nell'integrazione dei PoC minori in un singolo PoC principale, mentre il membro del gruppo asseganato al ruolo di verificatore proseguir
typo su assegnato

2023-12-17 23:44 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- I progettisti e il responsabile lavoreranno nella stesura del documento Norme di Progetto aggiungendo almeno cinque nuovi capitoli;
maiuscola su Progettisti e Responsabile

2023-12-17 23:44 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
>  - l'analista continuerà a redarre il documento di Analisi dei Requisiti migliorando quanto fatto e completando la tabella dei requisiti;
Analista*

2023-12-17 23:44 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
>  - l'amministratore dovrà:
Amministratore

2023-12-18 13:42 UTC, TodescoMattia approved these changes

2023-12-19 16:05 UTC, giogardin requested changes

2023-12-19 16:05 UTC, giogardin commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
>  - to do e divisione ruoli.
Maiuscola

2023-12-19 16:05 UTC, giogardin commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- I Progettisti e il Responsabile lavoreranno nella stesura del documento Norme di Progetto aggiungendo almeno cinque nuovi capitoli;
lavoreranno _alla_

2023-12-19 16:05 UTC, giogardin commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
>  $bold("Relativamente agli improvements le relative soluzioni accordate sono:")$
Relativamente e relative sono ridondanti

2023-12-19 16:05 UTC, giogardin commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- A causa di imprevisti tecnici, si sono verificati casi di insufficiente comunicazione tra i membri del gruppo creando il cosiddetto "effetto sottomarino" producendo rallentamenti dei lavori;
Doppia subordinata. Spezzerei la frase

2023-12-19 16:05 UTC, ggardin commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
>    - migliorare le GitHub Action risolvendo gli errori presenti legati al versionamento dei file e alla  modifica del changelog.
- ~presenti~
- doppio spazio
- ~modifica~ aggiornamento del changelog

2023-12-19 16:05 UTC, ggardin commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- Impegnarsi, in caso di imprevisti, a comunicare tempestivamente agli altri membri del gruppo gli eventuali ritardi previsti nei lavori;
~previsti~

2023-12-19 16:05 UTC, ggardin commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- avendo deciso, in seguito ai problemi riscontrati nello scorso sprint, di porre ai lavori scadenze infrasettimanali, le task sono state completate continuativamente, evitando sovraccarichi durante
Task completate ~continuativamente~ con maggiore costanza

2023-12-19 20:12 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
>  - to do e divisione ruoli.
dove? su to do non credo dato che viene dopo un ;

2023-12-19 20:21 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
> +- Impegnarsi, in caso di imprevisti, a comunicare tempestivamente agli altri membri del gruppo gli eventuali ritardi previsti nei lavori;
ha senso comunicare agli altri i ritardi che si prevedono a causa degli imprevisti, se si comunicano i ritardi già avvenuti è troppo tardi

2023-12-20 07:57 UTC, ggardin commented on 2 - RTB/Documentazione interna/Verbali/23-12-17/23-12-17.typ
>  - to do e divisione ruoli.
La convenzione è:
1. se la lista segue un paragrafo, si usano le minuscole
2. se la lista non segue un paragrafo, si usano le maiuscole

2023-12-21 17:54 UTC, ggardin approved these changes

2023-12-21 17:56 UTC, merged