DOC-155 redigere sezione technical management processes: measurement process
Error-418-SWE/Documenti pull request #125
Opened 2023-12-28 18:31 UTC by TodescoMattia

### Note
Redatto paragrafo di measurment process.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-28 19:38 UTC, SilvioNardo requested changes
Mi sembra che vada bene, comunque a livello di specificità è molto simile al capitolo che avevo scritto e sul quale sono state richieste modifiche

2023-12-28 19:38 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +    - identificare e pianificare l'utilizzo dei necessari sistemi o servizi abilitanti per i casi in cui i paramentri di misurazione di qualità non vengano rispettati.
typo su "paramentri "

2023-12-28 19:38 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Questo processo viene svolto affinchè il gruppo sia in grado di prendere le corrette decisioni per gestire al meglio il raggiungimento dei propri obiettivi.
Sostituisci "affinchè" con "affinché"

2023-12-28 22:43 UTC, SilvioNardo approved these changes

2023-12-29 15:41 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Lo scopo del processo di misurazione è raccogliere, analizzare e riportare dati e informazioni, al fine di dimostrare la qualità dei prodotti, servizi e processi.
dimostrare la qualità dei prodotti, servizi e processi. -> dimostrare la qualità *di* prodotti, servizi e processi.

2023-12-29 15:41 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Questo processo viene svolto affinché il gruppo sia in grado di prendere le corrette decisioni per gestire al meglio il raggiungimento dei propri obiettivi.
questo sezione del paragrafo ha un'indentazione strana nel file compilato, così lo vedo visualizzo corretto:
```
, servizi e processi.\
Questo processo viene svolto
```

2023-12-29 15:41 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Le misure devono avere queste caratteristiche di qualità:
uguale come sopra

2023-12-29 15:41 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Le misure devono avere queste caratteristiche di qualità:
se leggi questo pezzo risulta un pò strano, provo a fornire la soluzione:
Le misure devono soddisfare determinate caratteristiche di qualità, ovvero devono essere: 
+ verificabili;
+ significative;
+ attuabili;
+ tempestive;

2023-12-29 15:41 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +    - definire la strategia di misurazione per i processi di supporto. La strategia scelta si compone di una serie di parametri e metriche che permettono di valutare la qualità dei processi di suppor
qui è colpa mia, in questa sezione ho aggiunto un altra misurazione ieri sera che dovrebbe essere sui requisiti soddisfatti del prodotto

2023-12-29 15:41 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +    - identificare e pianificare l'utilizzo dei necessari sistemi o servizi abilitanti per i casi in cui i parametri di misurazione di qualità non vengano rispettati.
qui non ho capito cosa volevi dire, riesci a riscriverlo in maniera più chiara?

2023-12-29 19:18 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +    - identificare e pianificare l'utilizzo dei necessari sistemi o servizi abilitanti per i casi in cui i parametri di misurazione di qualità non vengano rispettati.
prova a dirmi se ti piace di più cosi. è una frase effettivamente poco chiara sono daccordo

2023-12-29 19:23 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +    - definire la strategia di misurazione per i processi di supporto. La strategia scelta si compone di una serie di parametri e metriche che permettono di valutare la qualità dei processi di suppor
ok modificherò con una pr appena il documento è terminato direi

2023-12-30 17:50 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +    - definire la strategia di misurazione per i processi di supporto. La strategia scelta si compone di una serie di parametri e metriche che permettono di valutare la qualità dei processi di suppor
aggiusta già adesso, basta che aggiungi
- metriche soddisfatte

2023-12-30 17:50 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +    - identificare e pianificare l'utilizzo dei necessari sistemi o servizi abilitanti per i casi in cui i parametri di misurazione di qualità non vengano rispettati.
top molto meglio

2023-12-31 16:48 UTC, FakeDaemon approved these changes

2023-12-31 17:03 UTC, merged