DOC-299 Redigere verbale 23-12-31
Error-418-SWE/Documenti pull request #138
Opened 2024-01-02 14:51 UTC by AlessioBanzato

### Note

Ho messo due revisori perché:
- Antonio era verificatore nello sprint a cui appartiene la retrospettiva;
- Riccardo è il verificatore attuale.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-01-02 16:11 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Verbali/23-12-31/23-12-31.typ
> +È stato notato un rallentamento dei lavori e una concentrazione degli stessi nel weekend, ovviamente causato dal periodo di feste. Questo rallentamento non viene visto, però, come un vero e proprio a
per andare a capo e creare un nuovo paragrafo usare \ a fine paragrafo, altrimenti l'indentazione impazzisce

2024-01-02 16:14 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Verbali/23-12-31/23-12-31.typ
> +- L'Analista si occuperà della revisione completa del documento Analisi dei Requisiti;
l'analista deve anche terminare il documento, oltre che revisionarlo

2024-01-02 17:50 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/23-12-31/23-12-31.typ
> +- Sono state individuate delle metriche di base riguardanti i documenti e l'andamento generale del team;
solitamente per identificare il "team" utiliziamo il termine "gruppo"... per conformità direi di attenerci a questo, come facciamo anche nelle norme di progetto.

2024-01-02 17:51 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/23-12-31/23-12-31.typ
> +=== Norme di Progetto
Se presenti, elencherei i capitoli svolti vs i capitoli non svolti

2024-01-02 17:56 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/23-12-31/23-12-31.typ
> +È stato realizzato il PoC finale. Dato il cambio di ruoli è stato programmato un meeting interno per spiegare nel dettaglio il PoC e il suo funzionamento ai nuovi Programmatori. Sarà inoltre necessar
Più che "E' stato realizzato il PoC finale", metterei in luce che è frutto della compattazione dei "mini PoC" finora prodotti (e che hanno trovato approvazione del Proponente). Non perchè sia sbagliato quanto detto, ma lo preciserei maggiormente ecco.

2024-01-02 17:56 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/23-12-31/23-12-31.typ
> +Non sono stati apportati importanti cambiamenti. Sono ancora presenti dei bug, in particolare il numero di versione nei documenti continua a rimanere lo stesso.
cambierei la seconda frase in "il numero di versione dei documenti non viene correttamente aggiornato".

2024-01-02 18:01 UTC, Carraro-Riccardo requested changes
Giusto qualche cambiamento secondo la mia modestissima opinione. Per il resto il contenuto va bene.

2024-01-03 14:46 UTC, FakeDaemon approved these changes
per me approvato, non mergio subito per permettere a riccardo di controllare i cambiamenti

2024-01-03 22:53 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/23-12-31/23-12-31.typ
> +È stato realizzato un PoC finale tramite la compattazione dei PoC esplorativi realizzati fin'ora, i quali avevano ottenuto l'approvazione del Proponente durante i meeting svolti prima del periodo del
typo in "fin'ora" -> finora senza apostrofo

2024-01-03 22:54 UTC, Carraro-Riccardo requested changes
typo individuato

2024-01-04 08:07 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Verbali/23-12-31/23-12-31.typ
> +È stato realizzato un PoC finale tramite la compattazione dei PoC esplorativi realizzati fin'ora, i quali avevano ottenuto l'approvazione del Proponente durante i meeting svolti prima del periodo del
damn

2024-01-04 08:41 UTC, Carraro-Riccardo approved these changes

2024-01-04 08:43 UTC, merged