DOC-288 Aggiornato il documento analisi dei rischi in typst in base alle norme di progetto
Error-418-SWE/Documenti pull request #145
Opened 2024-01-03 21:01 UTC by SilvioNardo

### Note
Caricamento del file relativo all'analisi dei rischi. Tale file è stato pesantemente modificato per essere conforme alle attuali norme di progetto.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-01-03 23:19 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +È prevista una modifica sostanziale, più o meno temporanea, nella comunicazione con il proponente. Questo potrebbe portare a ritardi nei lavori dovuti ad un maggior impegno da parte del team nel gara
Ci riferiamo solitamente a noi come "gruppo" e non con "team"

2024-01-03 23:19 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +È prevista una modifica sostanziale, più o meno temporanea, nella comunicazione con il proponente. Questo potrebbe portare a ritardi nei lavori dovuti ad un maggior impegno da parte del team nel gara
Proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo requested changes
Possono sembrare tante conversation ma più della metà sono relativi alla maiuscola mancante nella parola "Proponente"... per il resto giusto qualche cambiamento di qualche parola. Il contenuto direi che va bene.

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +== Comunicazione con il proponente
Proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +I contatti con il proponente subiscono variazioni nella qualità e nella frequenza a causa di problematiche fuori dal controllo del gruppo. Questa situazione potrebbe causare un rallentamento signific
proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +  - se il periodo critico previsto è sufficientemente breve da permettere al team di continuare con un corretto avanzamento dei lavori nonostante la variazione nella comunicazione con il proponente,
proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Si possono adottare, in accordo con il proponente, una o più tra le seguenti strategie comunicative:
proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +  - uso di strumenti asincroni per facilitare lo scambio di informazioni tra gruppo e proponente;
Proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Si attende il termine del periodo nel quale la comunicazione con il proponente risulta problematica.
Proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Per evitare perdite di tempo il team continua a lavorare priorizzando task che non dipendono direttamente dall'intervento del proponente.
team -> gruppo

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Per evitare perdite di tempo il team continua a lavorare priorizzando task che non dipendono direttamente dall'intervento del proponente.
Proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +In caso di Accettazione del rischio è importante tenere monitorata nel tempo la situazione per accertarsi che le circostanze non richiedano una modifica nell'approccio di risoluzione.
Accettazione con la A maiuscola è corretto?

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Lo sviluppo potrebbe allontanarsi dalle linee guida o dalle aspettative del proponente, non rispettando quanto preventivato o pianificato. Tale rischio, comporterebbe dunque la produzione di un softw
Proponente con la P maiuscola

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Lo sviluppo potrebbe allontanarsi dalle linee guida o dalle aspettative del proponente, non rispettando quanto preventivato o pianificato. Tale rischio, comporterebbe dunque la produzione di un softw
aggiungerei una virgola tra richieste e conducendo-> "richieste, conduncendo"

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Lo sviluppo potrebbe allontanarsi dalle linee guida o dalle aspettative del proponente, non rispettando quanto preventivato o pianificato. Tale rischio, comporterebbe dunque la produzione di un softw
per quanto corretta l'espressione "perdite di tempo", metterei una forma più formale tipo "conducendo a rallentamenti nell'analisi...."

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Le attività di lavoro assegnate ai membri coinvolti che non hanno una corretta conclusione nei tempi e nelle modalità previste possono essere riassegnate ad altri membri del team.
team -> gruppo

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +I partecipanti che si dovessero trovare in questa situazione rischierebbero di accentuare eventuali incomprensioni nel proprio lavoro senza la possibilità di confrontarsi con gli altri accorgendosi d
forse più che partecipanti direi "membri"

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Le analisi tecnologiche precedentemente fatte devono essere riviste in luce delle nuove opzioni individuate. Queste ultime possono essere a loro volta totalmente o parzialmente sconosciute al team il
fatte -> svolte

2024-01-03 23:34 UTC, Carraro-Riccardo commented on 1 - Candidatura/Analisi dei rischi/Analisi dei rischi.typ
> +Rallentamenti non preventivati che possono avere conseguenze a cascata sulle attività dipendenti e che possono coinvolgere più membri del team per un periodo di tempo difficilmente prevedibile.
team -> gruppo

2024-01-04 13:47 UTC, ggardin commented
Ma è corretto che questo documento stia in Candidatura?
Immagino che `1 - Candidatura/Analisi dei rischi` debba rimanere immutato e che vada aggiunta `2 - RTB/Analisi dei rischi`, no?

2024-01-04 15:29 UTC, ZacconeRosario requested changes
Molto bene, ho trovato solo due piccole correzioni da fare

2024-01-04 15:29 UTC, ZacconeRosario commented on 2 - RTB/Documentazione interna/Analisi dei rischi/Analisi dei rischi.typ
> +  - conseguenze relative a ciuascuna delle azioni possibili, esse descrivono gli effetti collaterali a breve o medio termine che il rischio può comportare.
Typo in "ciuascuna", da cambiare in "ciascuna"

2024-01-04 15:29 UTC, ZacconeRosario commented on 2 - RTB/Documentazione interna/Analisi dei rischi/Analisi dei rischi.typ
> +In caso di accettazione del rischio è importante tenere monitorata nel tempo la situazione per accertarsi che le circostanze non richiedano una modifica nell'approccio di risoluzione.
"accettazione"  da cambiare in "Accettazione", nel resto del documento è scritto sempre con la "a" maiuscola

2024-01-04 17:49 UTC, ZacconeRosario reviewed
Tutto ok, le modifiche svolte vanno bene

2024-01-04 17:50 UTC, ZacconeRosario approved these changes

2024-01-04 20:07 UTC, Carraro-Riccardo approved these changes

2024-01-04 20:08 UTC, merged