DOC-352 Correzione UC-1, UC-2
Error-418-SWE/Documenti pull request #179
Opened 2024-01-12 09:08 UTC by FakeDaemon

### Note

Pr relativa ai primi UC da modificare (gli altri andranno in un altra task, ho già modificato su jira) per rendere più piccola la task e più facile da correggere. 

>la creazione manuale del magazzino, era già emerso con il proponente che non dovrebbe più comprendere l'inserimento delle dimensioni del magazzino, ma bensì un semplice piano che sarà poi regolabile

modifica degli UC 1,2; relativa tabella fonte-requisito e UML

mentre del UC1 sono abbastanza convinto sia corretto, le modifiche sostanziali sono state fatte su UC2. Serve essere ancora più specifici? Se si, come? Aggiungendo una estensione da 2.1 e 2.2 riguardante l'errore della modifica delle varie dimensioni?

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-01-13 11:28 UTC, Carraro-Riccardo requested changes

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +l'utente vuole modificare le dimensioni dell'ambiente rimpicciolendo troppo le dimensioni dell'ambiente vuoto.
rimpicciolendo troppo -> riducendo eccessivamente

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'utente regola le dimensioni dell'ambiente di lavoro a piacimento.
rimuovere "a piacimento"

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'utente ha creato l' ambiente di lavoro manualmente;
rimuovere lo spazio dopo l'apostrofo

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- all'utente viene notificato l'errore relativo al fatto che l'ambiente non può diventare più piccolo.
cambiare in "le dimensioni dell'ambiente non possono essere ulteriormente diminuite"

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +l'utente vuole modificare le dimensioni dell'ambiente rimpicciolendo troppo le dimensioni dell'ambiente non vuoto.
ampliare il contesto: "Dato un ambiente già creato con già elementi posizionati (come scaffali e/o bin), l'utente cerca di ridurre le dimensioni dell'ambiente in modo eccessivo, non permettendo di mantenere gli elementi precedentemente posizionati". Riformula in modo più preciso.

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +All'avvio dell'applicazione e in ogni momento si desideri, si può decidere di creare un ambiente di lavoro vuoto di dimensioni predefinite.
"All'avvio dell'applicativo è possibile creare un ambiente vuoto di dimensioni predefinite da cui iniziare. Tale funzionalità, rimane disponibile durante l'utilizzo dell'applicativo qualora si volesse ripristinare l'ambiente."

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- è stato generato un ambiente di lavoro vuoto di dimensioni standard;
standard -> predefinite. Standard è un termine tecnico che stabilisce che tali dimensioni provengono da uno standard. In questo contesto è meglio definirle come "dimensioni predefinite"

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'utente crea un ambiente di lavoro vuoto con dimensioni standard.
standard -> predefinite

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- UC-2.1 Errore dimensioni magazzino troppo piccole;
Per conformità con gli altri use case, gli use case di errore si chiamano "visualizzazione errore ..." e non "errore". Anche perchè lo use case è la visualizzazione dell'errore, non l'errore di per sè.

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +== Errore dimensioni troppo piccole rispetto rispetto agli elementi nell'ambiente
Per conformità con gli altri use case, gli use case di errore si chiamano "visualizzazione errore ..." e non "errore". Anche perchè lo use case è la visualizzazione dell'errore, non l'errore di per sè.

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [FM-1.1.1], [Obbligatorio], [L'utente deve poter creare un magazzino tramite caricamento di un file SVG in qualunque momento.], [UC-1.1],
"In qualunque momento" è troppo generico... è come dire che durante magari la configurazione del database io posso creare il magazzino caricando un file svg... o magari mentre ricerco un prodotto... io rimuoverei quella dicitura e semmai, come nel caso precedente, specificherei che la funzionalità rimane disponibile qualora si volesse ricreare o cambiare l'ambiente. Aggiornare ovviamente use case e immagine.

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [FM-1.2.1], [Obbligatorio], [L'utente deve poter creare un magazzino vuoto in qualunque momento.], [UC-1.2],
Stessa cosa per quel "qualunque momento"

2024-01-13 11:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'utente vuole ridurre la dimensione dell'ambiente nonostante l'ambiente di lavoro contenga elementi che in questo modo non si adatterebbero più alle dimensioni del piano.
"...lavoro contenga elementi le cui posizioni non risulterebbero più valide alle nuove dimensioni ridotte"

2024-01-15 10:12 UTC, Carraro-Riccardo requested changes
Errore nome use case

2024-01-15 10:12 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +== Errore dimensioni magazzino troppo piccole
Lo use case è "Visualizzazione errore dimensioni magazzino troppo piccole", non solo "Errore". Infatti anche nell'immagine è così.

2024-01-15 11:22 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +== Errore dimensioni magazzino troppo piccole
scusa, mi era sfuggito

2024-01-16 10:16 UTC, Carraro-Riccardo approved these changes

2024-01-16 10:18 UTC, merged