DOC 388: creato verbale di retrospettiva del  24-01-28
Error-418-SWE/Documenti pull request #214
Opened 2024-02-04 19:56 UTC by TodescoMattia

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-04 21:55 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-01-28/24-01-28.typ
> +La fase di pianificazione di questo sprint risulta assente, poiché esso coincide temporalmente con la settimana più impegnativa della sessione d'esami invernale e poiché il gruppo è ancora in attesa
credo sia inconveniente dire che  "la pianificazione risulta assente",  io direi che "durante la pianificazione è stato deciso di attendere l'esito del colloquio RTB e nel frattempo, essendo questo sprint coincidente temporalmente con la settimana più impegnativa della sessione d'esami, i membri del gruppo si concentreranno sullo studio individuale"  o qualcosa di simile.

2024-02-04 22:14 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/24-01-28/24-01-28.typ
> +La fase di pianificazione di questo sprint risulta assente, poiché esso coincide temporalmente con la settimana più impegnativa della sessione d'esami invernale e poiché il gruppo è ancora in attesa
sensato

2024-02-05 16:14 UTC, SilvioNardo approved these changes

2024-02-05 16:50 UTC, ZacconeRosario requested changes

2024-02-05 16:50 UTC, ZacconeRosario commented on 2 - RTB/Documentazione interna/Verbali/24-01-28/24-01-28.typ
> +Il gruppo ha deciso di sospendere l'utilizzo di ChatGPT per la correzione grammaticale e sintattica dei documenti, in quanto i risultati prodotti non sono stati soddisfacenti e la pratica era soggett
e la pratica era soggetta ad allucinazioni frequenti => e venivano riscontrati parecchi falsi positivi (termine più tecnico)

2024-02-06 13:32 UTC, ZacconeRosario approved these changes

2024-02-06 14:38 UTC, merged