DOC-390 Redatto verbale 24-02-4
Error-418-SWE/Documenti pull request #215
Opened 2024-02-05 10:19 UTC by FakeDaemon

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-05 17:15 UTC, SilvioNardo requested changes

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +- Pianificazione sprint, ruoli e prossimi obbiettivi
manca il punto dopo obbiettivi

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +- Pianificazione sprint, ruoli e prossimi obbiettivi
riguardo la doppia "b" in "obbiettivi", secondo la treccani (https://www.treccani.it/enciclopedia/obiettivo-o-obbiettivo_(La-grammatica-italiana)/) "Sono corrette entrambe le forme: la forma obiettivo è più vicina all’etimo latino obiectivum, mentre obbiettivo è una forma di origine popolare che ha subito il raddoppiamento della b", quindi in caso forse è più formale una b solo

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +Il team ha aperto la riunione discutendo l'esito della prima parte di RTB svolta con il professor Cardin. Si è discusso in particolare delle criticità rilevate nel documento di `Analisi dei Requisiti
è chiaro ma per renderlo ancora più chiaro si può dire "...discutendo l'esito della prima parte del colloquio RTB svolto... " così da escludere l'ambiguità del termine RTB che può indicare anche tutto il periodo RTB.

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +Il team procede quindi esaminando la situazione corrente e settando degli obbiettivi "a lungo termine" da concludere come prerequisito per la seconda parte del RTB con il professor Vardanega. In part
cambiare "team" in "gruppo"

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +Il team ha aperto la riunione discutendo l'esito della prima parte di RTB svolta con il professor Cardin. Si è discusso in particolare delle criticità rilevate nel documento di `Analisi dei Requisiti
cambiare "team" in "gruppo"

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +- modifica di alcune metriche del `Piano di Qualifica` non compatibili con il modello di sviluppo scelto dal team;
cambiare "team" in "gruppo"

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +Il team procede quindi esaminando la situazione corrente e settando degli obbiettivi "a lungo termine" da concludere come prerequisito per la seconda parte del RTB con il professor Vardanega. In part
io cambierei la frase in "La situazione corrente è stata esaminata dal gruppo e sono stati definiti obbiettivi "a lungo termine" da concludere entro la seconda parte del colloquio RTB con il professor Vardanega."

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +- aggiornamento in seguito al big-bang del `Piano di Progetto`;
big-bang lo metterei tra virgolette

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +- tolti i programmatori e reinseriti gli analisti in vista del lavoro sull' `Analisi dei Requisiti`.
Programmatori e Analisti con la maiuscola

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +La pianificazione per lo sprint in corso ha visto definiti:
la pianificazione riguarda il prossimo sprint, non quello in corso

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +== Pianificazione <pianificazione>
tag <pianificazione> da togliere

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +- revisione suddivisione ruoli per prolungamento del RTB oltre le attese;
metterei "revisione suddivisione ruoli preventivati a causa di un prolungamento nei tempi della valutazione RTB oltre le attese;"

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +La pianificazione per lo sprint in corso ha visto definiti:
al posto di "ha visto definiti:" metterei  "si è focalizzata nella:"

2024-02-05 17:15 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +- tolti i programmatori e reinseriti gli analisti in vista del lavoro sull' `Analisi dei Requisiti`.
metterei "rimozione dei Programmatori e reinserimento degli Analisti tra i ruoli dello sprint in vista...."

2024-02-05 19:32 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +Il team ha aperto la riunione discutendo l'esito della prima parte di RTB svolta con il professor Cardin. Si è discusso in particolare delle criticità rilevate nel documento di `Analisi dei Requisiti
non capisco la conversation, "prima parte di RTB svolta con il professor Cardin" non è abbastanza chiaro?

2024-02-05 20:24 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-04/24-02-04.typ
> +Il team ha aperto la riunione discutendo l'esito della prima parte di RTB svolta con il professor Cardin. Si è discusso in particolare delle criticità rilevate nel documento di `Analisi dei Requisiti
nel senso che metterei "colloquio RTB " invece di solo RTB

2024-02-06 14:48 UTC, SilvioNardo approved these changes

2024-02-06 14:49 UTC, merged

2024-02-06 16:23 UTC, ggardin commented
Ragazzi scusate ma da quando in qua i nomi dei documenti si riferiscono in _monospace_?

2024-02-06 16:46 UTC, FakeDaemon commented
> Ragazzi scusate ma da quando in qua i nomi dei documenti si riferiscono in _monospace_?

![immagine_2024-02-06_174630439](https://github.com/Error-418-SWE/Documenti/assets/91839513/3e33f345-c2b8-49bd-9732-3546946f7d1f)