DOC-395 Specificati i valori che possono essere modificati durante la modifica di uno scaffale
Error-418-SWE/Documenti pull request #218
Opened 2024-02-06 01:28 UTC by SilvioNardo

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-06 07:23 UTC, AlessioBanzato requested changes
Typo e un consiglio di stile

2024-02-06 07:23 UTC, AlessioBanzato commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'utente può seleziona un diverso orientamento dello scaffale nel piano (orizzontale o verticale);
selezionare*

2024-02-06 07:23 UTC, AlessioBanzato commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +L'utente può decidere, per ciascuno di essi, di sostituirlo specificando il nuovo valore oppure di lasciarlo inalterato.
Consiglio, non richiesta: personalmente toglierei entrambi i "\\" precedenti

2024-02-06 14:54 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +L'utente può decidere, per ciascuno di essi, di sostituirlo specificando il nuovo valore oppure di lasciarlo inalterato.
aspetto di sentire anche l'opinione di qualcun altro a riguardo perché la differenza è poca e non saprei cosa è meglio.

2024-02-06 16:09 UTC, AlessioBanzato approved these changes

2024-02-07 17:22 UTC, giogardin approved these changes

2024-02-07 17:43 UTC, merged