DOC-409 Specificare spostamento della visuale UC11.1
Error-418-SWE/Documenti pull request #226
Opened 2024-02-07 14:03 UTC by AlessioBanzato

### Note

Oltre alle modifiche richieste dalla task ho rimosso tutti i '.' al termine di ogni requisito funzionale dove erano rimasti.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-07 15:36 UTC, SilvioNardo requested changes

2024-02-07 15:36 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +una volta che il sistema è stato configurato, l'utente può visualizzare il magazzino e spostare la visuale lungo almeno uno dei tre assi (orizzontale, verticale, profondità).
al posto di "una volta che.." che è abbastanza informale, metterei "successivamente alla configurazione del sistema, l'utente..."

2024-02-07 15:36 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +una volta che il sistema è stato configurato, l'utente può visualizzare il magazzino e spostare la visuale lungo almeno uno dei tre assi (orizzontale, verticale, profondità).
essendo che stiamo elencando gli assi, il terzo lo chiamerei "longitudinale" al posto di "profondità"

2024-02-07 15:36 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'utente ha spostato la visuale sul magazzino nella direzione di almeno uno dei tre assi (orizzontale, verticale, profondità).
anche qua metterei "longitudinale" al posto di "profondità"

2024-02-07 15:36 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'utente può spostare la visuale del magazzino in verticale;
nei 3 punti relati agli assi metterei "...spostare la visuale del magazzino lungo l'asse orizzontale;",  "...spostare la visuale del magazzino lungo l'asse verticale;",  "...spostare la visuale del magazzino lungo l'asse longitudinale;"

2024-02-09 18:37 UTC, SilvioNardo requested changes, later dismissed

2024-02-09 18:37 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +sucessivamente alla configurazione di sistema, l'utente può visualizzare il magazzino e spostare la visuale lungo almeno uno dei tre assi (orizzontale, verticale, logitudinale).
typo su logitudinale

2024-02-09 18:37 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +sucessivamente alla configurazione di sistema, l'utente può visualizzare il magazzino e spostare la visuale lungo almeno uno dei tre assi (orizzontale, verticale, logitudinale).
typo in "sucessivamente"

2024-02-10 20:34 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +sucessivamente alla configurazione di sistema, l'utente può visualizzare il magazzino e spostare la visuale lungo almeno uno dei tre assi (orizzontale, verticale, logitudinale).
Forse qui sarebbe meglio approfondire cosa intendiamo con "configurazione del sistema". Più che parlare di sistema magari si potrebbe dire "configurazione dell'ambiente 3D"? Si potrebbe indicare il relativo UC

2024-02-11 09:29 UTC, ggardin approved these changes

2024-02-11 09:46 UTC, merged