DOC-378 Refactor Piano di Progetto
Error-418-SWE/Documenti pull request #228
Opened 2024-02-07 14:58 UTC by ggardin

### Note

Completo refactor del documento Piano di Progetto. Per i dettagli lascio i link ai ticket.

- ristrutturazione introduzione;
- riordinate sezioni;
- aggiunta di grafici con il pacchetto `Cetz` al posto di `plotst`;
- evidenziazione di termini positivi e negativi nelle tabelle di consuntivo;
- aggiornati riferimenti documentali;

In abbinata al Piano di Progetto è stato aggiornato anche il foglio elettronico associato.

Implementa e chiude i ticket [DOC378], [DOC-376], [DOC-385], [DOC-420] e [DOC-421].

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

[DOC-376]: https://error418swe.atlassian.net/browse/DOC-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-385]: https://error418swe.atlassian.net/browse/DOC-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-420]: https://error418swe.atlassian.net/browse/DOC-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-421]: https://error418swe.atlassian.net/browse/DOC-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-02-07 17:29 UTC, SilvioNardo requested changes

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> + authors: (
metterei i redattori in ordine alfabetico

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Identificati i rischi, le relative contromisure e il calendario di progetto, si è definito, mediante una pianificazione a ritroso, un preventivo iniziale dei costi di realizzazione del progetto.
al posto di "si è definito" metterei "è stato definito"

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +    [Costo\ ruolo], [€ 2100], [€ 1960], [€ 2625], [€ 1225], [€ 2940], [€ 2205], [],
metterei il costo totale anche nella tabella (ultima cella, ultima riga)

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +L'Analista è il ruolo preposto all'individuazione, redazione, aggiornamento e tracciamento dei requisiti del progetto. Il modello Agile adottato dal gruppo prevede che l'attività di analisi si svolga
in "Pertanto, per  il ruolo di Analista..." c'è un doppio spazio dopo "per"

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Il periodo individuabile tra l'aggiudicazione del capitolato e la data di consegna del prodotto viene suddiviso in 2 periodi principali dettati dalle revisioni esterne _Requirements and Technology Ba
sostituirei "individuabile" con "compreso"

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Essenziale in questa organizzazione è l'analisi retrospettiva al termine di ogni sprint. Essa permette di valutare in modo critico eventuali mancanze, criticità o errori che possono in questo modo ve
piccola ripetizione di "in futuro", rimuoverei la prima occorrenza

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- *Problematiche insorte*: analisi delle criticità riscontrate durante lo sprint, in modo da aver chiari le motivazioni che le hanno causate;
typo su "chiari", metterei "chiare"

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Al fine di rendere quanto più chiaro possibile il contenuto dei documenti, e per evitare qualsiasi forma di ambiguità in merito ai termini utilizzati, il gruppo _Error\_418_ fornisce un _*Glossario*_
essendo che parliamo del glossario e che il prof Cardin ha detto "Il glossario va riferito anche con il numero di versione del documento" mi viene il dubbio che sia da mettere il glossario (e relativa versione) nei riferimenti

2024-02-07 17:29 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
>  = Pianificazione del lavoro
aggiungerei dopo la spiegazione degli sprint un paragrafo che spiega che i ruoli descritti ruotano ogni 2 sprint mantenendoci comunque elastici a riguardo in base alle task

2024-02-07 18:33 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Al fine di rendere quanto più chiaro possibile il contenuto dei documenti, e per evitare qualsiasi forma di ambiguità in merito ai termini utilizzati, il gruppo _Error\_418_ fornisce un _*Glossario*_
OK, ho aggiunto ai riferimenti a documentazione interna. Ho visto che ci sono altri documenti senza il riferimento, aggiungo i relativi ticket.

2024-02-07 20:22 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
>  = Pianificazione del lavoro
E se invece fosse in prossimità del `2.3 Analisi dei ruoli`? Come lo vedi?

2024-02-07 23:59 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
>  = Pianificazione del lavoro
ci avevo pensato ma in quel punto non si è ancora parlato di sprint, comunque se pensi che possa andare prova e vedi dove ci sta meglio

2024-02-10 00:47 UTC, SilvioNardo requested changes

2024-02-10 00:47 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +== Preventivo calcolato
avendo aggiunto questa informazione nella tabella mi viene il dubbio che questo punto sia ridondante o posizionato male. D'altro canto scriverlo solo nella tabella potrebbe non essere sufficiente

2024-02-10 00:47 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +    [Costo ruolo],     [90],     [160],     [150],     [0],     [0],     [90],     [490],
la cella Costo ruolo va a capo tagliando a metà la parola ruolo, se possibile sarebbe più elegante far andare a capo bene

2024-02-10 00:47 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- scelta di una data per un eventuale primo meeting con il professore Cardin per ottenere un feedback sull'Analisi dei Requisiti;
per restare in linea con il resto del documento metterei "Professor Cardin" al posto di "professore Cardin" (anche se ho alcuni dubbi sull'utilizzo della maiuscola per Professor)

2024-02-10 00:47 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- redigere del Glossario.
metterei "redigere il Glossario" o "redazione del Glossario"

2024-02-10 00:47 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Gli obiettivi dell'ottavo sprint si incentrano sul completamento delle attività rimaste sospese nel settimo sprint, e sull'avanzamento del documento Norme di Progetto, oltre che sul miglioramento di
nel punto "...già concluse. ,, gli..."  probabilmente c'è stato un errore di digitazione, non sono sicuro di come volessi impostare la frase.

2024-02-10 00:47 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Gli obiettivi dell'ottavo sprint si incentrano sul completamento delle attività rimaste sospese nel settimo sprint, e sull'avanzamento del documento Norme di Progetto, oltre che sul miglioramento di
io toglierei la prima virgola ottenendo "...rimaste sospese nel settimo sprint e sull'avanzamento del documento..."

2024-02-10 00:47 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - migliorare il Glossario come indicato nel primo punto della.
non è specificato il primo punto di cosa.

2024-02-10 00:47 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Gli obiettivi dell'ottavo sprint si incentrano sul completamento delle attività rimaste sospese nell'ottavo sprint, sulla revisione dei documenti e del PoC in vista della valutazione RTB. , gli obiet
in "...valutazione RTB. , gli obiettivi..." c'è una virgola in più e manca la maiuscola in "gli"

2024-02-10 20:04 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +    [Costo ruolo],     [90],     [160],     [150],     [0],     [0],     [90],     [490],
Corrette tutte le occorrenze e il foglio di calcolo che genera il codice, così che il problema non si ripresenti in futuro

2024-02-10 20:22 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +== Preventivo calcolato
Sono d'accordo sul fatto che messo qui sia un po' isolato. Forse possiamo metterlo dopo la tabella e prima dell'Analisi dei ruoli (attuale paragrafo 2.3)?

2024-02-10 20:57 UTC, SilvioNardo requested changes

2024-02-10 20:57 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Gli obiettivi del decimo sprint vertono sulla revisione dei documenti in preparazione per il colloquio RTB. , gli obiettivi prefissati per questo sprint sono:
solito problema della virgola

2024-02-10 20:57 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Gli obiettivi del dodicesimo sprint riguardano la partecipazione al colloquio RTB, in data 25/01/2024 alle ore 8:40.
specificherei che era il colloquio RTB con il Professor Cardin

2024-02-10 20:57 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- aggiunta di grafici significativi al Piano di Progetto, come ad esempio la Suddivisione oraria per ruolo, mediante il pacchetto `plotst` di Typst;
metterei "suddivisione" in minuscolo

2024-02-10 20:57 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Le risoluzioni attuate per risolvere i problemi citati in precedenza si concentrano su un'organizzazione e un'attenzione maggiore nella fase di pianificazione, oltre alla definizione di standard rela
la lista puntata è anticipata solo da uno spazio "...verbali. :"

2024-02-10 20:57 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Aggiornare vecchi documenti con nuovo template;
ultimo punto della lista puntata ha ";" al posto del "."

2024-02-10 20:57 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Preparazione presentazione revisione RTB.
la frase "Preparazione presentazione revisione RTB" mi sembra troppo sintetica, metterei "Preparazione della presentazione per la revisione RTB"

2024-02-10 20:57 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Inviata la candidatura al Prof. Cardin per il colloquio RTB;
nel resto del documento abbiamo usato "Professor"

2024-02-10 20:57 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Il totale delle ore lavorate, seppur basso, è stato in gran parte rispettato. Tuttavia, il ruolo di Analista è stato attivato per correggere un errore di forma riscontrato nel calcolo dei codici iden
riformulerei "Il totale delle ore lavorate, seppur basso, è stato in gran parte rispettato." in "Il totale delle ore di lavoro preventivate è stato in gran parte rispettato."

2024-02-10 21:10 UTC, SilvioNardo requested changes

2024-02-10 21:10 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +    [Banzato],     [0],     [0],     [1 (-1)],     [0],     [0],     [0],     [1 (-1)],
alcuni dati della tabella non sono in linea con quelli del preventivo (per esempio Banzato ha segnato come Analista "1(-1)" però nella tabella di preventivo sprint 11 è segnato 4 ore.)

2024-02-10 21:11 UTC, SilvioNardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +== Preventivo calcolato
va bene

2024-02-10 21:45 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +    [Banzato],     [0],     [0],     [1 (-1)],     [0],     [0],     [0],     [1 (-1)],
Hai ragione, ma purtroppo il documento attualmente in `main` non è corretto e ha diversi errori. Fa fede il foglio elettronico, infatti se vedi il preventivo dello sprint 11 in questo documento torna tutto

2024-02-11 11:26 UTC, SilvioNardo approved these changes

2024-02-11 11:27 UTC, merged