DOC-424: revisione capitolo 4 norme di progetto
Error-418-SWE/Documenti pull request #235
Opened 2024-02-08 16:03 UTC by TodescoMattia

### Note
con la rimozione del capitolo 3, questo diventerà a sua volta il capitolo 3

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-09 19:24 UTC, SilvioNardo requested changes

2024-02-09 19:24 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Processo di gestione dei modelli di ciclo di vita;
non saprei se è giusta la maiuscola in questo elenco puntato. Da un lato noi mettiamo la minuscola negli elenchi però dall'altro stai nominando il nome dei processi...

2024-02-09 19:24 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Processo di gestione delle risorse umane.
da capire se ha senso citare il processo di gestione delle risorse umane perché alla relativa sezione abbiamo detto che essendo un progetto didattico non viene sviluppato

2024-02-09 19:24 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +L'attuazione è l'ultima fase del processo di gestione del ciclo di vita, e consiste nell'attuazione delle contromisure stabilite durante la fase di verifica. \
ripetizione di "attuazione", sostituirei la seconda occorrenza con un sinonimo come "adozione" o "esecuzione"

2024-02-09 19:24 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>  Le responsabilità del Programmatore includono:
per evitare di ripetere "Programmatore" metterei semplicemente "Le sue responsabilità includono:"

2024-02-09 19:24 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Comunicazione frequente: la frequenza della comunicazione permette di prendere decisione in modo tempestivo e informato.
intendevi "prendere decisioni"?

2024-02-09 20:26 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Processo di gestione dei modelli di ciclo di vita;
l'ho messa perchè questi 3 punti vengono poi implementati uno per uno nelle pagine dopo. quindi mi sembra un elenco di una certa rilevanza (tipo un titolo che dice i punti che verranno trattati dopo)

2024-02-09 20:26 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Processo di gestione delle risorse umane.
secondo me ci sta motivare perchè non lo abbiamo implementato

2024-02-10 14:26 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Processo di gestione delle risorse umane.
Io lo rimuoverei perché la lista riguarda i "processi [...] **implementati**", e giustamente come dice Silvio la gestione delle HR non è stata fatta

2024-02-10 14:27 UTC, ggardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Processo di gestione dei modelli di ciclo di vita;
Qui mi atterrei alla solita regola, quindi lettera minuscola

2024-02-10 15:53 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Processo di gestione delle risorse umane.
tolto dalla lista di quelle implementate, ho però lasciato il paragrafo che spiega che non lo abbiamo implementato. Se volete rimuovere anche quello fatemi sapere, a me piaceva comunque l'idea di far sapere che ci abbiamo pensato

2024-02-10 18:00 UTC, SilvioNardo approved these changes

2024-02-10 18:03 UTC, merged