DOC-427 Revisionare paragrafo 5.3 delle Norme di Progetto
Error-418-SWE/Documenti pull request #238
Opened 2024-02-08 20:07 UTC by ZacconeRosario

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-10 19:17 UTC, FakeDaemon requested changes, later dismissed

2024-02-10 19:17 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- vengono identificate la risoluzione, la giustificazione della decisione e le ipotesi.
1) se possibile trasformare in elenco puntato
2) le ipotesi su cosa? Specificare se possibile

2024-02-10 19:17 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ *Decisioni organizzative*: sono relative al modo di lavorare, cioè a come vengono gestiti i processi di avanzamento del progetto. Esempi notevoli sono le decisioni focalizzate alla coordinazione de
io la riscriverei così:
 > Decisioni organizzative: sono relative al modo di lavorare, cioè a come vengono gestiti i processi di avanzamento del progetto. Esempi notevoli sono le decisioni focalizzate alla coordinazione del gruppo o alla scelta degli strumenti da utilizzare per la gestione del progetto __(ad esempio: scelta dell' ITS, delle piattaforme per la comunicazione e per la collaborazione)__:

2024-02-10 19:17 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ *Decisioni sulla qualità*: sono decisioni relative ai controlli di qualità.
due punti alla fine della frase per conformità al resto del paragrafo

2024-02-10 19:17 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    - documento soggetto a modifiche: Norme di progetto;
come segnato nella sezione "4.6.4.2.2 corsivo, grassetto, maiuscole e monospace" nomi dei documenti vanno segnati in monospace. Segno una volta per tutte le iterazione del paragrafo

2024-02-10 19:17 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il processo di decision making viene prevalentemente svolto nel meeting di retrospettiva, in modo da non contrastare la pianificazione dello sprint in corso ed evitare un eccessivo numero di meeting
> è richiesta una figura con maggiore esperienza nel campo di riferimento.

2024-02-10 19:35 UTC, ZacconeRosario commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- vengono identificate la risoluzione, la giustificazione della decisione e le ipotesi.
ipotesi era riferito alle decisioni, ho corretto

2024-02-10 19:47 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- vengono identificate la risoluzione, la giustificazione della decisione e le ipotesi.
va bene, ipotesi di che tipo: ipotesi sull'efficacia della decisione, sulla necessità di prendere la decisione, ... ? io lo specificherei

2024-02-11 13:56 UTC, ZacconeRosario commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- vengono identificate la risoluzione, la giustificazione della decisione e le ipotesi.
corretto

2024-02-11 23:03 UTC, SilvioNardo requested changes, later dismissed

2024-02-11 23:03 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ *Decisioni organizzative*: sono relative al modo di lavorare, cioè a come vengono gestiti i processi di avanzamento del progetto. Esempi notevoli sono le decisioni focalizzate alla coordinazione de
aggiungerei uno spazio tra "progetto" e la parentesi aperta.
toglierei uno spazio tra "dell' " e "ITS"

2024-02-11 23:03 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  - documento soggetto a modifiche: `Norme di Progetto`, documenti tecnici (diagramma delle classi, ...);
non è corretto mettere ", ..." rimarrei quanto più specifico possibile.

2024-02-11 23:03 UTC, SilvioNardo commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  - documento soggetto a modifiche: `Norme di Progetto`, documenti tecnici (diagramma delle classi, diagramma dei casi d'uso...);
anche qua i puntini mi sembrano sbagliati

2024-02-12 10:41 UTC, ggardin requested changes
Quasi mi dispiace bloccare la PR per un solo commento

2024-02-12 10:41 UTC, ggardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il processo di decision making viene prevalentemente svolto nel meeting di retrospettiva, in modo da non contrastare la pianificazione dello sprint in corso ed evitare un eccessivo numero di meeting
Qui temo ci vada il congiuntivo: ~è~ sia

2024-02-12 12:55 UTC, giogardin approved these changes

2024-02-12 12:57 UTC, merged