DOC-422 definire metriche adatte al nostro progetto
Error-418-SWE/Documenti pull request #239
Opened 2024-02-08 20:35 UTC by Carraro-Riccardo

### Note
https://error418swe.atlassian.net/browse/DOC-422?atlOrigin=eyJpIjoiZmE1Y2VmZGUxYzI5NDcyN2JmNjA0Y2YwMGE1NWQzNGMiLCJwIjoiaiJ9

Manca il riferimento alle versione dei documenti riferiti, quali:
- Norme di Progetto;
- Piano di Progetto;
- altri

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-08 21:31 UTC, ggardin requested changes

2024-02-08 21:31 UTC, giogardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +La metrica PV rappresenta il valore pianificato, indicante il costo preventivato per portare a termine le attività pianificate nello sprint. Per il calcolo del valore pianificato si considera la somm
Forse ~indicante~ -> ovvero

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +La metrica risulta un indice necessario a determinare il valore atteso del lavoro svolto in un determinato sprint. Il suo valore strettaemente maggiore di 0 indica che non sono contemplati periodi di
- ~risulta~ è
- typo in "strettamente"

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +- *SPV*: Sprint Planned Value, valore pianificato per un determinato sprint;
Andrei a capo per staccare il paragrafo dall'elenco puntato

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
Forse ci potrebbe stare un "Si definisce:" tra l'elenco e la tabella?

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +- $"dato s in S, con S insieme degli sprint svolti"$
Vedi commento precedente. Inoltre qui non sembra coerente avere l'elenco puntato perché il precedente era introdotto da "Dati:", mentre qui invece "dato" è incluso nell'elenco. Scriverei:
```
Dato:
- s in S...
```

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +Il costo totale del capitolato non può essere maggiore rispetto a quanto espresso in candidatura, pertanto gli unici valori accettbili (e ottimali) sono stime a ribasso rispetto al *BAC*. Dipendendo
- "stime a**l** ribasso", o ancora meglio "pari o inferiori"
- "può subire variazioni anche a**l** rialzo"
- metterei un punto dopo la parola "rialzo": "Sarà compito del gruppo..."
- ~e al momento della consegna, non superiore ad esse~ "puntando progressivamente, con l'avvicinarsi della milestone PB, ad un valore pari o inferiore". Come suona? Seppur esprima meglio il concetto di un miglioramento progressivo, ancora non mi sembra ideale

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +Avere un resoconto delle metriche soddisfatte per ogni sprint permette di evidenziare eventuali criticità e di attuare le misure di correzione necessarie, seguendo, come stabilito nelle Norme di Prog
Lascio il TODO perché l'esatto numero di paragrafo potrebbe subire variazioni

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +== Processi primari
Che ne dici? Mi sembra che così sia più chiaro il motivo di questa scelta.
```
Nel primo sprint si è ~definito~ confermato (?) l'utilizzo dell'ITS Jira come strumento di tracciamento, ~e gli sprint successivi sono stati utilizzati per la sua comprensione e corretto utilizzo~ ma per comprenderne a fondo le meccaniche e il corretto utilizzo, sono stati necessari i seguenti 4 sprint. Nel corso di questo periodo, sono state apportate modifiche di configurazione, anche consapevolmente non retrocompatibili, che hanno introdotto eterogeneità nei dati riportati dall'ITS.
```

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +*RTB*: In questo primo periodo, il gruppo è consapevole che il valore pianficato *PPV* risulta superiore a quanto prodotto nell'effettivo indicato dal *PEV*. Nonostante ciò il gruppo è sempre riuscit
- "risult**i** superiore"
- "Nonostante ciò **,**"
- "superiore ~almeno~ alla soglia minima del PPV, fissata a 80%"

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +\
Via le backslash ahahah, qui basta andare a capo

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +*RTB*: L'indice *CPI* risulta sempre in un range di valore accettabile. Seppur non lineare, non si evidenziano grandi variazioni, permettendo di evidenziare un corretto avanzamento in termini di cost
C'è una ripetizione di "evidenziare". Potresti scrivere "Seppur l'andamento non sia lineare, non si rilevano grandi variazioni, il che evidenzia un corretto avanzamento in termini di costi e lavoro prodotto"

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +*RTB*: Il valore dell'*EAC* oscilla attorno al valore del *BAC*. Il gruppo è consapevole che il valore stabilito dal *BAC* non può essere superato, pertanto l'*EAC* al termine del progetto dovrà atte
~può~ possa

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +  - *PdP*: Il documento ha inizialmente subito la maggior parte di aggiunte a livello testuale, come le sezioni di introduzione, amministrazione dei periodi e dei ruoli. Successivamente gli aggiornam
- Ripetizione. "La realizzazione di un sistema di definizione automatica delle tabelle"
- inizia le frasi con la minuscola qui

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +  - *Glossario*: Il Glossario è stato soggetto a relativamente poche modifiche; la maggior parte degli errori è stata riscontrata inizialmente, e successivamente il documento è stato soggetto a poche
- La seconda parte della frase ripete quanto detto all'inizio della stessa, penso si possa tagliare
- Inizia con la minuscola dopo il nome del documento

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +  - *WoW*: L'adozione dello standard ISO/IEC 12207:2017 ha portato con sè anche un grado di complessità maggiore nella stesura del documento, il quale è aumentato di dimensione e complessità. La magg
- Il documento si chiama Norme di Progetto (o NdP)
- Inizia con la minuscola dopo il nome del documento

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +    plot.add(WoW_points(offset: 0), line: "linear", label: "WoW", mark: "o")
NdP, non WoW

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +  - *PdQ*: L'insorgenza di errori nel Piano di Qualifica è dettata dall'inizio della sua stesura dallo sprint 9;
Inizia con la minuscola dopo il nome del documento

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +  - *AdR*: Data la natura del periodo di RTB, l'Analisi dei Requisiti è tra i documenti più corposi e maggiormente soggetti a revisioni e modifiche. Inoltre, l'incremento dei numero di errori è dovut
Inizia con la minuscola dopo il nome del documento

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +  - *Analisi dei Rischi*: La stesura del documento di Analisi dei Rischi non è stata caratterizzata da un numero elevato di errori.
Inizia con la minuscola dopo il nome del documento

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +*RTB*: La percentuale di metriche soddisfatte risulta per la maggior parte degli sprint superiore alla soglia accettabile del 75%. I periodi in cui tale soglia non è stata raggiunta sono gli sprint 8
~accettabile~ di accettabilità

2024-02-08 21:31 UTC, ggardin commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +- Sprint 11,12,13: periodo dal 15/01/2024 al 05/02/2024, caratterizzato dalla sessione d'esami.
Aggiungi uno spazio dopo il numero dello sprint

2024-02-09 10:58 UTC, ggardin commented
Questa PR chiude anche [DOC-418].

2024-02-09 12:16 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +\
Perdona l'ingerenza dei backslash ma mentre lavoraro li avevo messi perchè spezzava titolo e tabella :(

2024-02-09 12:20 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +  - *PdP*: Il documento ha inizialmente subito la maggior parte di aggiunte a livello testuale, come le sezioni di introduzione, amministrazione dei periodi e dei ruoli. Successivamente gli aggiornam
Ho optato per "l'implementazione"

2024-02-09 15:07 UTC, ggardin approved these changes

2024-02-09 15:08 UTC, merged