DOC-367 Estensione Glossario
Error-418-SWE/Documenti pull request #241
Opened 2024-02-09 15:43 UTC by FakeDaemon

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-10 22:29 UTC, SilvioNardo submitted a review, later dismissed

2024-02-10 22:29 UTC, SilvioNardo commented on Glossario.json
> +    "description": "Rappresentazione visiva del lavoro ancora da svolgere confrontato con il tempo necessario a portarlo a termine. Facendo una stima del tempo necessario a completare le attività, ri
riscriverei la descrizione elencando cosa si trova negli assi, per esempio wikipedia dice "Un burn down chart è una rappresentazione grafica del lavoro da fare su un progetto nel tempo. Di solito il lavoro rimanente (o backlog) è indicato sull'asse verticale e il tempo sull'asse orizzontale. Il diagramma rappresenta una serie storica del lavoro da fare." 
Inoltre non userei forme del tipo "puoi determinare..." ma è meglio usare "è possibile determinare..."

2024-02-10 22:29 UTC, SilvioNardo commented on Glossario.json
> +    "description": "Strumento di gestione dei progetti che illustra il lavoro completato in determinato periodo in relazione al tempo pianificato per quel lavoro. Un diagramma di Gantt può includere
metterei "...completato in un determinato periodo..."

2024-02-10 22:29 UTC, SilvioNardo commented on Glossario.json
> +    "description": "Gli epic rappresentano obiettivi generali o grandi porzioni di lavoro che possono essere suddivisi in story, task e bug.",
non sono sicuro di "e bug" nella suddivisione degli epic

2024-02-10 22:29 UTC, SilvioNardo commented on Glossario.json
> +    "description": "Strumento di gestione dei progetti che illustra il lavoro completato in determinato periodo in relazione al tempo pianificato per quel lavoro. Un diagramma di Gantt può includere
la descrizione è troppo generica a mio avviso

2024-02-10 22:29 UTC, SilvioNardo commented on Glossario.json
> +    "description": "Uno sprint è un breve periodo di tempo, in cui un team Scrum collabora per completare una determinata quantità di lavoro. Gli sprint rappresentano una parte essenziale delle metod
io scriverei che i nostri sprint corrispondono a una settimana

2024-02-11 08:31 UTC, ggardin commented on Glossario.json
> +    "description": "Rappresentazione visiva del lavoro ancora da svolgere confrontato con il tempo necessario a portarlo a termine. Facendo una stima del tempo necessario a completare le attività, ri
Inoltre burndown va con la b minuscola

2024-02-11 08:37 UTC, ggardin commented on Glossario.json
> +    "description": "Gli epic rappresentano obiettivi generali o grandi porzioni di lavoro che possono essere suddivisi in story, task e bug.",
Farei una cosa del tipo:
```
Nella metodologia Agile, un epic è una porzione di lavoro, rilasciabile in modo indipendente, che viene suddivisa in ticket. L'organizzazione del lavoro in epic aiuta a individuare gerarchie tra i ticket.
```

2024-02-11 08:58 UTC, ggardin requested changes
Ho segnato alcuni miglioramenti anche in parti non aggiunte da te.

_Consiglio per la prossima volta: se vedi che git è andato in crisi e ha rilevato che tutto il file è stato modificato, resetta il branch e poi apri PR_

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Specifica funzionalità o caratteristica all'interno del prodotto sviluppato.",
Toglierei "all'interno" perché è sottinteso. Inoltre aggiungerei alla fine ". Può essere richiesta esplicitamente dal Proponente o individuata dal Fornitore sulla base del processo di Analisi dei Requisiti."

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Gli epic rappresentano obiettivi generali o grandi porzioni di lavoro che possono essere suddivisi in story, task e bug.",
Farei una cosa del tipo:
```
Nella metodologia Agile, è una porzione di lavoro, rilasciabile in modo indipendente, che viene suddivisa in ticket. L'organizzazione del lavoro in epic aiuta a individuare gerarchie tra i ticket.
```

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Rappresentazione visiva del lavoro ancora da svolgere confrontato con il tempo necessario a portarlo a termine. Facendo una stima del tempo necessario a completare le attività, ri
Inoltre burndown va con la b minuscola

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Strumento di gestione dei progetti che illustra il lavoro completato in determinato periodo in relazione al tempo pianificato per quel lavoro. Un diagramma di Gantt può includere
Yes va migliorata. Quel "molto altro" non mi piace

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Rappresentano il lavoro da completare a sostegno degli obiettivi più ampi. I bug sono problemi che ostacolano l'avanzamento o la funzionalità del lavoro.",
Metterei al singolare la definizione

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Rappresentano il lavoro da completare a sostegno degli obiettivi più ampi. I bug sono problemi che ostacolano l'avanzamento o la funzionalità del lavoro.",
Bisogna menzionare il fatto che il ticket è individuale (aka viene lavorato da una singola persona) e atomico

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Rappresentano il lavoro da completare a sostegno degli obiettivi più ampi. I bug sono problemi che ostacolano l'avanzamento o la funzionalità del lavoro.",
Non capisco perché venga menzionato il bug

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "synonyms": []
Aggiungere a sinonimi "Norme di Progetto"

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "acronyms": ["WoW"],
Aggiungere ad acronimi "NdP"

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "synonyms": ["Compose"]
Teoricamente sarebbe corretto averlo tra i sinonimi, ma siccome "Docker Compose" contiene già la parola "Compose", per come funziona l'evidenziazione, diventa ridondante. Si può rimuovere dai sinonimi

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Apps Script è l'unica piattaforma low-code che consente di creare in modo rapido e veloce soluzioni aziendali che integrano, automatizzano e ampliano le funzionalità di Google Wor
Sinceramente non mi piace, sembra una marchetta. Meglio una cosa del genere:
```
Linguaggio di scripting, basato su JavaScript, che permette di automatizzare compiti nei prodotti Google Workspace.
```

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Google Workspace è una suite di software e strumenti di produttività per il cloud computing e per la collaborazione, offerta da Google.",
Non serve ripetere il termine, quindi farei "~Google Workspace~ È un..."

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "synonyms": ["Docs"]
Rimuovere il sinonimo perché ridondante (non sarebbe sbagliato metterlo, ma l'evidenziazione prevede già che la parola possa essere scomposta)

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "synonyms": ["Drive"]
Rimuovere il sinonimo perché ridondante (non sarebbe sbagliato metterlo, ma l'evidenziazione prevede già che la parola possa essere scomposta)

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +  "Ingegneria del software": {
Software con la S maiuscola

2024-02-11 08:58 UTC, ggardin commented on Glossario.json
> +    "description": "Unità di misura per esprimere una stima del lavoro complessivo richiesto per implementare completamente un elemento del backlog di prodotto o qualsiasi altra porzione di lavoro.",
"~un elemento del backlog di prodotto o qualsiasi altra porzione di lavoro~" -> "un ticket"

2024-02-11 09:07 UTC, FakeDaemon commented
> Glossario.json

purtroppo mi sono accorto della cosa solo ieri sera dopo che me l'ha detto silvio, comunque grazie per il tip

2024-02-11 10:34 UTC, ggardin requested changes
Aggiunta di Grafana ai termini

2024-02-11 10:34 UTC, ggardin commented on Glossario.json
> +  },
Aggiungi Grafana:
```
"Grafana": {
    "description": "È una piattaforma open-source per la visualizzazione e la monitoraggio di dati. Permette di creare dashboard interattive e personalizzabili per metriche, log e altri dati provenienti da diverse sorgenti.",
    "acronyms": [],
    "synonyms": []
}
```

2024-02-13 10:11 UTC, FakeDaemon commented on Glossario.json
> +    "description": "Gli epic rappresentano obiettivi generali o grandi porzioni di lavoro che possono essere suddivisi in story, task e bug.",
<img width="101" alt="eliminare" src="https://github.com/Error-418-SWE/Documenti/assets/91839513/a552c9b8-1b65-424f-a0c2-694635191b23">

bug non era intesa come suddivisione di epic, ma come tipo di task, comunque ho modificato la descrizione quindi il problema non si pone

2024-02-13 10:15 UTC, FakeDaemon commented on Glossario.json
> +    "description": "Apps Script è l'unica piattaforma low-code che consente di creare in modo rapido e veloce soluzioni aziendali che integrano, automatizzano e ampliano le funzionalità di Google Wor
Adesso che ola rileggo forse un pò hai ragione ahah. La definizione viene direttamente da Google, forse è per quello.

2024-02-13 10:24 UTC, FakeDaemon commented on Glossario.json
> +    "description": "Rappresentano il lavoro da completare a sostegno degli obiettivi più ampi. I bug sono problemi che ostacolano l'avanzamento o la funzionalità del lavoro.",
non mi ricordo perché l'ho messo, comunque tolgo

2024-02-14 10:34 UTC, giogardin approved these changes

2024-02-14 10:35 UTC, merged

2024-02-14 11:31 UTC, SilvioNardo commented on Glossario.json
> +  "Diagrammi di burn down": {
è corretto sia scrivere "burndown" che "burn down" però manterrei la forma unita per rimanere coerenti con gli altri documenti.

2024-02-14 11:31 UTC, SilvioNardo commented on Glossario.json
> +    "synonyms": ["burn down", "burn down Chart"]
aggiungerei "burndown-chart" "burndown chart" e "burndown" ai sinonimi