DOC-400 Specificare le informazioni necessarie al collegamento con il database UC6.1
Error-418-SWE/Documenti pull request #243
Opened 2024-02-09 16:23 UTC by Carraro-Riccardo

### Note
https://error418swe.atlassian.net/browse/DOC-400?atlOrigin=eyJpIjoiNTQzMTA3ZmNhNjkzNGJhMWJkZTQ5NzIwZjRkNjYxZWUiLCJwIjoiaiJ9

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-10 19:36 UTC, FakeDaemon requested changes, later dismissed

2024-02-10 19:36 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
>  == Configurazione collegamento al database <oo>
riesci ad eliminare questo riferimento(< oo >)? non pare essere richiamato da nessuna parte

2024-02-10 19:36 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'utente i dati relativi alla configurazione del collegamento al database, quali:
> l'utente **vuole configurare** i dati **necessari** alla configurazione del collegamento al database, quali:

2024-02-11 15:41 UTC, ggardin approved these changes

2024-02-11 15:57 UTC, merged