DOC-404 Rivedere termine richiesta UC7
Error-418-SWE/Documenti pull request #260
Opened 2024-02-12 19:30 UTC by AlessioBanzato

### Note

Vedendo com'è sviluppato l'UC-7 ho deciso di rinominarlo come "Spostamento". L'interrogazione di API è presente internamente e come requisito

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-13 08:08 UTC, ggardin commented
Siamo sicuri che sia corretto dire che l'utente "deve spostare"? Perché in realtà, prima dell'effettivo spostamento, ci sono:
1. interrogazione API per capire se sia possibile fare lo spostamento;
2. in caso di risposta positiva, il prodotto assume uno stato di transizione (magari con diversa opacità) per segnalare che lo spostamento è stato **richiesto**

2024-02-13 08:29 UTC, AlessioBanzato commented
> Siamo sicuri che sia corretto dire che l'utente "deve spostare"? Perché in realtà, prima dell'effettivo spostamento, ci sono:
> 
> 1. interrogazione API per capire se sia possibile fare lo spostamento;
> 2. in caso di risposta positiva, il prodotto assume uno stato di transizione (magari con diversa opacità) per segnalare che lo spostamento è stato **richiesto**

Io ho ragionato sul fatto che come utente la funzionalità che richiedo è lo spostamento di un prodotto, poi ovviamente prima dello spostamento effettivo ci sono i passaggi che hai scritto, che alla fine sono quelli che andremo a implementare noi.
Cosa/come modificheresti?

2024-02-13 08:43 UTC, ggardin commented
> > Siamo sicuri che sia corretto dire che l'utente "deve spostare"? Perché in realtà, prima dell'effettivo spostamento, ci sono:
> > 
> > 1. interrogazione API per capire se sia possibile fare lo spostamento;
> > 2. in caso di risposta positiva, il prodotto assume uno stato di transizione (magari con diversa opacità) per segnalare che lo spostamento è stato **richiesto**
> 
> Io ho ragionato sul fatto che come utente la funzionalità che richiedo è lo spostamento di un prodotto, poi ovviamente prima dello spostamento effettivo ci sono i passaggi che hai scritto, che alla fine sono quelli che andremo a implementare noi. Cosa/come modificheresti?

In realtà quello che dici ha molto senso. Vediamo un po' cosa dicono i verificatori

2024-02-14 08:48 UTC, Carraro-Riccardo requested changes
Tutto a posto, solo un piccolo cambiamento (secondo me)

2024-02-14 08:48 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [FM-7.1], [Obbligatorio], [L'utente deve poter spostare un prodotto da un bin ad un altro indicando le coordinate del bin di destinazione], [UC-7],
Personalmente, il termine “coordinate” mi fa più pensare a qualcosa del tipo x,y,z quindi lascerei più un “spostare un prodotto da un bin d’origine ad un altro di destinazione”

2024-02-14 09:08 UTC, Carraro-Riccardo approved these changes

2024-02-14 09:08 UTC, merged