DOC-475 Redigere verbale di retrospettiva 11/02/2024
Error-418-SWE/Documenti pull request #276
Opened 2024-02-15 15:06 UTC by FakeDaemon

### Note

nella parte di "analisi della retrospettiva" oltre a "criticità" ho aggiunto anche un paragrafo "soluzioni adottate". in entrambi i paragrafi ho cercato di tracciare criticità-soluzioni usando un elenco numerato

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-15 19:00 UTC, Carraro-Riccardo requested changes

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo apre la riunione analizzando l'andamento dello sprint appena concluso. È stato evidenziato come, nonostante fosse il primo sprint di lavoro dopo il warm start, si sia lavorato molto bene, c
"Il gruppo...appena concluso." riformulerei in "Il meeting si avvia con con l'analisi dello sprint concluso".

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo apre la riunione analizzando l'andamento dello sprint appena concluso. È stato evidenziato come, nonostante fosse il primo sprint di lavoro dopo il warm start, si sia lavorato molto bene, c
E' lo sprint stesso il warm start: lo sprint non è iniziato dopo un warm start, ma è esso stesso il warm start in quanto la ripresa dei lavori non è stata lenta ma veloce. Il periodo dunque va riformulato, magari in una forma "Nonostante si trattasse del primo sprint a seguito della sessione degli esami, la ripresa dei lavori è stata rapida (warm start), grazie anche alla scelta di non interrompere i lavori negli sprint precedenti ma di ridimensionare il carico di lavoro per far fronte agli impegni universitari."

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo apre la riunione analizzando l'andamento dello sprint appena concluso. È stato evidenziato come, nonostante fosse il primo sprint di lavoro dopo il warm start, si sia lavorato molto bene, c
Evitare espressioni del tipo "buono", "si è lavorato molto bene" che sono colloquiali e non formali e soprattutto i documenti devono essere oggettivi.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo apre la riunione analizzando l'andamento dello sprint appena concluso. È stato evidenziato come, nonostante fosse il primo sprint di lavoro dopo il warm start, si sia lavorato molto bene, c
Il "come dimostrato da" può essere sostituito da una frase del tipo "Il corretto andamento dello sprint è supportato anche dalle metriche esposte sul cruscotto di qualità realizzato in Grafana."

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Sono stati revisionati la maggior parte dei capitoli del documento, anche se il lavoro non è ancora del tutto ultimato.
Quali? e quali sono i riamanenti? elencali con un elenco puntato. Il verbale deve essere un resoconto preciso e informativo.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo si è impegnato a risolvere tutte le criticità riscontrate dal #cardin durante la prima parte di revisione RTB.
Quali criticità? elencale con un elenco puntato. Il verbale deve essere un resoconto preciso e informativo.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il lavoro sui documenti segue dal big bang attuato durante gli sprint precedenti e viene concluso.
Il PdP ha subito big bang, il PdQ non è mai stato dichiarato che abbia subito un big bang. Il PdQ è stato esteso e aggiornato con le metriche del periodo e la loro analisi.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il lavoro sui documenti segue dal big bang attuato durante gli sprint precedenti e viene concluso.
Specifica cosa è stato fatto per il pdp, come preventivo e consuntivo, indicandone lo sprint di riferimento

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo ha concordato l'invio della mail per presentarsi al colloquio con il #vardanega per sostenere la seconda parte del RTB.
riformulare in "Il gruppo ha concordato l'invio della mail per sostenere la seconda parte della revisione esterna RTB con il #vardanega per la data (data invio email, 14/02/2024)"

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +A contribuire al successo dello sprint 14 troviamo una buonissima pianificazione iniziale delle task, e il fatto che la modalità di lavoro asincrona risulta pienamente consolidata dal gruppo.
Evitare termini come "buonissimi" che sono colloquiali e non oggettivi.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +A contribuire al successo dello sprint 14 troviamo una buonissima pianificazione iniziale delle task, e il fatto che la modalità di lavoro asincrona risulta pienamente consolidata dal gruppo.
"risulta pienamente consolidata dal gruppo" è una constatazione soggettiva e non oggettiva.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +A contribuire al successo dello sprint 14 troviamo una buonissima pianificazione iniziale delle task, e il fatto che la modalità di lavoro asincrona risulta pienamente consolidata dal gruppo.
Non introdurre frasi o concetti con "il fatto che"

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +=== Criticità
Manca il paragrafo "Imprevements", probabilmente erroneamente sostituito da Criticità

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> ++ ritardi nelle correzioni delle pr
manca il ; alla fine dell'elemento

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Tra le criticità evidenziate troviamo:
Riformulare la struttura come nei paragrafi improvements degli sprint precedenti.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> + quando il verificatore si trova in difficolta vista la grande mole di lavoro in review, un membro può aiutare approvando le task più piccole. Questo contribuisce a snellire il numero di pr aperte ed
"Se un solo verificatore non risulta sufficiente a causa di un numero consistente di pull request richieste, il gruppo si impegnerà a scegliere un ulteriore membro che in qualità di verificatore provvederà nella review delle pull request aperte. Tale soluzione permette inoltre di ridimensionare il numero di branch aperti e ridurre conseguentemente la probabilità di merge conflict."

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo di comune accordo ha deciso di inviare al #vardanega la mail di candidatura per la seconda perte della revisione RTB. Il responsabile è stato incaricato di scrivire la mail e, mercoledì 14/
"... revisione RTB mercoledì 14/02/2024. Il Responsabile ha il compito di redigere la mail e inviarla." Fine.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +È stato ritenuto necessario quindi iniziare la bozza della presentazione, sulla base di un brainstorming per identificare le possibili slide e le domande che il professore potrebbe avere interesse a
E come la iniziavamo la bozza se non avevamo ottenuto la mail di conferma di Tullio con gli argomenti da lui richiesti? 
Secondo questa logica avremmo scritto una presentazione nata da un brainstorming che con quale probabilità avrebbe azzeccato esattamente i punti richiesti dal professore?

In caso si può dire che il gruppo si riserva di fissare un meeting per la creazione della bozza della presentazione e la suddivisione degli argomenti *a seguito* della risposta del professore

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +== Pianificazione sprint 15
Nel titolo del paragrafo di pianificazione non si riporta il nome dello sprint (vedi paragrafo degli altri verbali di retrospettiva)

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Sono stati programmati i seguenti compiti:
Rimuovendolo dal titolo sarà necessario inserire qui che la pianificazione si riferisce allo sprint 15

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- definire lo scheletro della presentazione per il colloquio;
Anche qui non è ragionevole avere una presentazione prima della mail di conferma del professore con gli argomenti da lui richiesti

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- programmare i due meeting interni riguardanti la presentazione;
Anche qui non è ragionevole avere una presentazione prima della mail di conferma del professore con gli argomenti da lui richiesti. Semmai è possibile definirli a seguito della risposta del professore.

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- iniziare i lavori riguardanti la parte di PB non appena gli ultimi lavori per il colloqui sono stati terminati, evitando di bloccarsi attendendo il colloquio.
Quali lavori?

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- iniziare i lavori riguardanti la parte di PB non appena gli ultimi lavori per il colloqui sono stati terminati, evitando di bloccarsi attendendo il colloquio.
"evitando di bloccarsi ... colloquio." -> "evitando la sospensione delle attività."

2024-02-15 19:00 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- Seconda parte RTB con #vardanega
manca ; alla fine dell'elemento

2024-02-16 14:35 UTC, FakeDaemon commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Sono stati revisionati la maggior parte dei capitoli del documento, anche se il lavoro non è ancora del tutto ultimato.
non riesco a vedere da jira precisamente quali task di Revisione NdP rimanevano da fare, mi mostra solo la story in report

2024-02-17 02:13 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Tra le criticità evidenziate troviamo:
@FakeDaemon nei vecchi verbali di retrospettiva (esempio 14-01-2024)  non sono mai stati usati gli elenchi numerati. Semplicemente si segnavano uno sotto l'altro gli improvements.

2024-02-17 02:31 UTC, Carraro-Riccardo requested changes

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> ++ maggiore partecipazione su Miro:\
Capisco l'intento di creare una corrispondenza tra improvments e soluzioni, ma anche qui si va contro alla struttura dei precedenti verbali. E' ragionevole come cosa, anche se non normata e non presente in nessun verbale precedente.

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Tra le criticità evidenziate troviamo:
Niente forme personali come "troviamo". Piuttosto riformula in "Si evidenziano le seguenti criticità:"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> + se un solo verificatore non risulta sufficiente a causa di un numero consistente di pull request aperte, il gruppo si impegnerà a scegliere un ulteriore membro che in qualità di verificatore provved
typo: "merge conflict"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> + se un solo verificatore non risulta sufficiente a causa di un numero consistente di pull request aperte, il gruppo si impegnerà a scegliere un ulteriore membro che in qualità di verificatore provved
mettere le virgole "che, in qualità di verificatore, provvederà"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> + se un solo verificatore non risulta sufficiente a causa di un numero consistente di pull request aperte, il gruppo si impegnerà a scegliere un ulteriore membro che in qualità di verificatore provved
provvederà all***e*** review, non "alla"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +A contribuire al successo dello sprint 14 troviamo un efficace pianificazione delle task e il rispetto della modalità di lavoro asincrona.
niente forme personali come "troviamo"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo ha concordato l'invio della mail per sostenere la seconda parte della revisione esterna RTB con il #vardanega per la data 14/02/2024.
"per la data" -> "in data"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il lavoro sul #pdp segue dal big bang attuato durante gli sprint precedenti e viene concluso. Viene inoltre redatto:
C'è più di un elemento nell'elenco, quindi sostituirei con "Vengono inoltre redatti:"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- preventivo sprint 14;
l'ultimo elemento dell'elenco deve terminare con il . e non ;

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il documento abbozza una struttura corretta, ma il livello di analisi raggiunto è spesso poco dettagliato e lacunoso. Inoltre, sono presenti alcuni errori di modellazione.\
Per andare a capo non serve \. Piuttosto doppio invio

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- Rimuovere capitolo Processi di supporto/Documentazione;
Specificherei tra parentesi che il capitolo in questione è un capitolo obsoleto non conforme allo standard iso adottato, ed è per questo che sta venendo rimosso. Dall'esterno può sembrare che stiamo semplicemente rimuovendo un capitolo delle norme senza motivo.

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il meeting si avvia con con l'analisi dello sprint concluso. Nonostante si trattasse del primo sprint a seguito della sessione degli esami, la ripresa dei lavori è stata rapida (warm start), grazie a
Cambierei in un "." tra "impegni universitari" e "il corretto". Il periodo è leggermente troppo lungo.

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- Seconda parte RTB con #vardanega;
"con" -> "con il"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Tutti queste criticità sono state corrette durante lo sprint appena concluso e il documento è ora pronto per la revisione prima del PB.
Da rivedere la parte "revisione prima del PB"... intendi forse che è pronto per essere revisionato prima dell'ingresso in PB?

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +Il gruppo di comune accordo ha deciso di inviare al #vardanega la mail di candidatura per la seconda parte della revisione RTB mercoledì 14/02/24. Il Responsabile ha il compito di redigere la mail e
Per andare a capo non serve \. E' sufficiente un doppio invio.

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- completare le ultime tesk necessarie per la candidatura;
typo in tesk

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- completare le ultime tesk necessarie per la candidatura;
"per la candidatura al secondo sportello di valutazione RTB"

2024-02-17 02:31 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- definire un meeting inerente la presentazione RTB a seguito della risposta del professore;
inerente "alla"

2024-02-17 23:18 UTC, Carraro-Riccardo reviewed
correzione typo

2024-02-17 23:18 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +- Rimuovere capitolo Processi di supporto/Documentazione (capitolo obsoleto non conforme allo standard iso adottato);
ISO in maiuscolo

2024-02-17 23:18 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione interna/Verbali/24-02-11/24-02-11.typ
> +In merito al successo dello sprint 14 ha contribuito un efficace pianificazione delle task e il rispetto della modalità di lavoro asincrona.
"un'efficace pianificazione" con l'apostrofo

2024-02-17 23:30 UTC, Carraro-Riccardo approved these changes

2024-02-17 23:34 UTC, merged