Aggiornare documento analisi costi
Error-418-SWE/Documenti pull request #3
Opened 2023-11-15 11:42 UTC by TodescoMattia

Link alla issue di Jira: https://error418swe.atlassian.net/browse/DOC-67?atlOrigin=eyJpIjoiZWVhMDczNzJjOTg4NGU0NzgzZmRmNmZmMTcxNGM3MTQiLCJwIjoiaiJ9

Note: Aggiornamento preventivo dei costi secondo indicazioni post accettazione capitolato.

### ✏️ Checklist

- [x] documento testato;
- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-11-15 14:38 UTC, ggardin requested changes
Grazie per la PR. Ci sono alcune cose da sistemare ma l'impianto mi sembra buono

2023-11-15 14:38 UTC, ggardin commented on Candidatura/Preventivo dei costi/Preventivo dei costi.typ
> +==  Periodo di sviluppo della Requirements and Technologies Baseline
C'è uno spazio di troppo

2023-11-15 14:38 UTC, ggardin commented on Candidatura/Preventivo dei costi/Preventivo dei costi.typ
> +- Periodo raccolta e analisi dei requisiti;
Iniziali minuscole

2023-11-15 14:38 UTC, ggardin commented on Candidatura/Preventivo dei costi/Preventivo dei costi.typ
> +L'amministratore è un ruolo presente durante l'intero progetto, in quanto si occupa di predisporre e controllare il corretto utilizzo delle procedure e degli strumenti definiti nel _way of working_,
Norme di Progetto al posto di *way of working*

2023-11-15 14:38 UTC, ggardin commented on Candidatura/Preventivo dei costi/Preventivo dei costi.typ
> +Il responsabile è un ruolo presente durante l'intero progetto. Il suo compito è quello di gestire il team di assicurarsi che lo sviluppo proceda secondo le tempistiche predefinite e le aspettative de
- [ ] Manca un connettivo dopo "team"
- [ ] Norme di Progetto con le iniziali maiuscole

2023-11-15 14:38 UTC, ggardin commented on Candidatura/Preventivo dei costi/Preventivo dei costi.typ
> +Il programmatore ha il compito di sviluppare concretamente l'architettura prodotta dal progettista, traducendola in codice sorgente. Il ruolo prevede un numero di ore molto elevato poiché riteniamo i
Non "sviluppare" ma "tradurre in codice eseguibile" o qualcosa del genere. Lo sviluppo appartiene ad altri ruoli.
Più che "dispendioso" direi che richiede tante ore.

2023-11-16 16:55 UTC, ggardin commented on Candidatura/Preventivo dei costi/Preventivo dei costi.typ
> +    (name: "Banzato Alessio", role: "Redattore"),
Ma questi ruoli vanno bene così? @FakeDaemon @Carraro-Riccardo

2023-11-18 15:11 UTC, TodescoMattia commented on Candidatura/Preventivo dei costi/Preventivo dei costi.typ
> +    (name: "Banzato Alessio", role: "Redattore"),
i ruoli li avevo messi cosi con riccardo, non sono giusti?

2023-11-19 11:35 UTC, ggardin commented on Candidatura/Preventivo dei costi/Preventivo dei costi.typ
> +    (name: "Banzato Alessio", role: "Redattore"),
Ok, grazie per il chiarimento. Ti do l'ok allora

2023-11-19 11:35 UTC, ggardin approved these changes

2023-11-19 11:35 UTC, merged