DOC-504 Uso delle variabili per riferirsi ai documenti
Error-418-SWE/Documenti pull request #300
Opened 2024-02-18 22:20 UTC by ggardin

### Note

n.d.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-18 23:01 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [QM-1], [Obbligatorio], [Deve essere rispettato quanto previsto dalle #ndp], [Decisione\ interna],
Mi rifaccio a quanto detto dal professore: per documenti di ampie dimensioni preciserei anche il capitolo a cui si sta facendo riferimento (e anche la versione)

2024-02-18 23:02 UTC, Carraro-Riccardo requested changes

2024-02-18 23:02 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [QM-2], [Obbligatorio], [Deve essere rispettato quanto previsto dal #pdq], [Decisione\ interna],
Mi rifaccio a quanto detto dal professore: per documenti di ampie dimensioni preciserei anche il capitolo a cui si sta facendo riferimento (e anche la versione)

2024-02-18 23:02 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [QM-1], [Obbligatorio], [Deve essere rispettato quanto previsto dalle #ndp], [Decisione\ interna],
Mi rifaccio a quanto detto dal professore: per documenti di ampie dimensioni preciserei anche il capitolo a cui si sta facendo riferimento (e anche la versione)

2024-02-19 19:49 UTC, ggardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [QM-2], [Obbligatorio], [Deve essere rispettato quanto previsto dal #pdq], [Decisione\ interna],
Per il PdQ credo sia sufficiente il numero di versione visto che l'intero documento è prescrittivo, no?

2024-02-19 19:50 UTC, ggardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [QM-1], [Obbligatorio], [Deve essere rispettato quanto previsto dalle #ndp], [Decisione\ interna],
Però ho il dubbio su quale paragrafo riferire

2024-02-20 14:24 UTC, Carraro-Riccardo approved these changes

2024-02-20 14:27 UTC, merged