DOC-522 Redigere verbale meeting di retrospettiva 18/02/2024
Error-418-SWE/Documenti pull request #304
Opened 2024-02-19 17:08 UTC by Carraro-Riccardo

### Note
https://error418swe.atlassian.net/browse/DOC-522?atlOrigin=eyJpIjoiYmI0ZmE4OWFjNmIxNDZlMTk3NzJlMzFmNzc1ZWI2Y2QiLCJwIjoiaiJ9

Si tratta del primo verbale di PB. Assicuratevi che il percorso sia corretto. 
Ho segnato anche @ggardin come reviewer perchè mi aveva chiesto di vedere. 
Ho necessità di feedback in merito a:
- tracciamento criticità - soluzioni;
- livello di dettaglio;

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-19 19:53 UTC, ggardin commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +Rimosso capitolo non derivante dallo standard ISO/IEC 12207:2017, il cui contenuto era già assorbito dal capitolo 4.6.3 delle #ndp_v.
Forse ha senso dire quale?

2024-02-19 20:00 UTC, ggardin reviewed
Molto buono. Lascio solo dei commenti in attesa della review vera e propria di @FakeDaemon.

2024-02-19 20:00 UTC, giogardin commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +Rimossa la GitHub action di supporto alla revisione di spellcecking mediante ChatGPT. Tale action era stata precedentemente disattivata a causa dei risultati non soddisfacenti prodotti e dei numerosi
Action con la maiuscola

2024-02-19 20:00 UTC, giogardin commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +Al fine di migliorare la conformità, la coerenza e la consistenza nell'utilizzo dei nomi dei documenti, dei nomi dei professori e del nome stesso del gruppo, tali termini sono stati resi variabili ri
I file non si mettono tra `backtick`?

2024-02-19 20:00 UTC, giogardin commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +    [Sprint Actual Cost (SAC)], [#TODO]
Note to self: rimuovere #TODO

2024-02-19 20:00 UTC, giogardin commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +#figure(caption: [Soluzioni individuate alle criticità riscontrate.],
Non sarebbe più utile inserire queste soluzioni di mitigazione nel PdP all'apposita sezione? E qui solo riferire il codice? Chiedo

2024-02-20 00:18 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +Al fine di migliorare la conformità, la coerenza e la consistenza nell'utilizzo dei nomi dei documenti, dei nomi dei professori e del nome stesso del gruppo, tali termini sono stati resi variabili ri
Penso sia stata rimossa come regola perchè non utilizzata

2024-02-20 00:20 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +#figure(caption: [Soluzioni individuate alle criticità riscontrate.],
Sì è quello che pensavo anche io, le avevo segnate qui intanto per averne una base. Io proporrei di dare ID,Titolo,Descrizione ad ogni soluzione nel pdp e qui riportare ID e Titolo (il titolo permette di recepire meglio di cosa si tratta piuttosto che solo un codice ID, così anche solo leggendo il verbale si capisce meglio cosa comporta la risoluzione)

2024-02-20 10:18 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +Lo Sprint 15 ha raggiunto gli obiettivi prefissati, terminando con tutte le task pianificate per il periodo completate.
rimuovere completate alla fine della frase

2024-02-20 10:18 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +- `publish-artifact` si aggiorna dalla versione _v3_ alla versione _v4_;
rimuovere il punto publish-artifact
c'era un errore nella task, la automazione era upload-artifact, publish artifact era il job

2024-02-20 10:32 UTC, FakeDaemon requested changes

2024-02-20 10:32 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +Rimossa la GitHub action di supporto alla revisione di spellcecking mediante ChatGPT. Tale action era stata precedentemente disattivata a causa dei risultati non soddisfacenti prodotti e dei numerosi
typo, si scrive spellchecking

2024-02-20 10:32 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +=== Termini riccorrenti
typo, togliere una c in ricorrenti

2024-02-20 10:32 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +#figure(caption: [Soluzioni individuate alle criticità riscontrate.],
riporto questa soluzione nelle norme allora

2024-02-20 10:32 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> += Pianificazione <pianificazione>
metterei un pagebreack() anche prima di pianificazione, che dopo il titolo c'è metà pagina bianca

2024-02-20 10:37 UTC, FakeDaemon commented
il livello di dettaglio va bene, e anche per quanto riguarda la questione tracciamento criticità-soluzione farei come discusso nella conversation, quindi nei verbali utilizzare una forma del tipo id criticità-id soluzione-titolo, criticità-titolo-id soluzione, oppure direttamente id criticità-id soluzione + titolo (tutto nella stessa casella)

2024-02-20 14:31 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/23-02-18/23-02-18.typ
> +Lo Sprint 15 ha raggiunto gli obiettivi prefissati, terminando con tutte le task pianificate per il periodo completate.
Lo avevo messo per evidenziare che il periodo si è concluso con tutte le task completate e nussuna task non risolta

2024-02-20 20:59 UTC, closed without merging