DOC-517 Redigere consuntivo di periodo Sprint 15
Error-418-SWE/Documenti pull request #309
Opened 2024-02-20 20:57 UTC by Carraro-Riccardo

### Note
[DOC-517]

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-23 10:37 UTC, ggardin requested changes
Alcune piccole correzioni, e alcune considerazioni più macro. Scusa per il ritardo

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - specificate le API utilizzate dall'UC7.
`;`

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +
Secondo te può essere utile mettere una sorta di divisorio che indichi il passaggio alla PB e la contestuale evoluzione dovuta al recepimento del feedback?

Una roba tipo:

```
#box(
  width: 1fr,
  height: 4em,
  fill: rgb(242, 236, 216, 100),
  stroke: 1pt + rgb(217, 212, 194, 100),
  align(
    center + horizon,
    [
      Accesso alla PB\
      Il documento cambia secondo le risoluzioni descritte nel #TODO\.
    ]
  )
)
```

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Lo Sprint 15 pur comportando un costo superiore a quanto preventivato, ha permesso di raggiungere tutti gli obiettivi prefissati. La distribuzione delle ore tra i membri del gruppo è stata differente
Metterei una virgola dopo 15

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- CPI: Il Cost Performance Index passa dal valore 0.97 (allo Sprint 14) a 0.98, indicando un miglioramento del rendimento del gruppo;
Dopo i due punti non metterei la maiuscola

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- EAC: L'Estimate At Completion passa dal valore 13.437,22 € (allo Sprint 15) a 13.292,70 €, indicando una riduzione del costo finale del progetto se il rendimento del gruppo rimarrà costante;
Dopo i due punti non metterei la maiuscola

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- EAC: L'Estimate At Completion passa dal valore 13.437,22 € (allo Sprint 15) a 13.292,70 €, indicando una riduzione del costo finale del progetto se il rendimento del gruppo rimarrà costante;
Può aver senso sottolineare che il valore di EAC sia comunque ancora superiore al BAC?

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Le ore preventivate di Responsabile e Amministratore, seppur quantitivamente rispettate, sono state ridistribuite tra i membri del gruppo;
Minuscola

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Le ore di Analista sono state maggiori di quanto preventivato: il tracciamento UC - requsiti, per renderlo uniforme, automatico e facilmente estendibile è stato implementato mediante un automazione
Minuscola

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Le ore di Progettista sono state maggiori di quanto preventivato: la progettazione dello schema ER del database è stata più complessa del previsto seppur permettendo di generare confronto tra i mem
Minuscola

2024-02-23 10:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - i termini ricorrenti all'interno dei documenti (es. nome di documenti, nome dei professori, ...) sono stati resi variabili riutilizzabili durante la stesura dei documenti;
Aggiungerei "per promuovere una maggior coerenza stilistica"

2024-02-23 15:53 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +
Non so bene: da un lato credo sia meglio avere un documento uniforme, quindi se dobbiamo fare qualcosa, lo farei all'intero corpo del documento.... d'altro canto però non credo sia ragionevole modificare tutto quello che si è scritto finora... 

Ad ogni modo, la soluzione proposta potrabbe essere effettivamente la soluzione migliore

2024-02-23 16:03 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +
#box(  
  width: 1fr,  
  height: 4em,  
  fill: rgb(242, 236, 216, 100),  
  stroke: 1pt + rgb(217, 212, 194, 100),  
  align(  
    center + horizon,  
    [  
      Accesso alla PB\  
      Il documento cambia secondo le risoluzioni descritte nel #TODO\.  
    ]  
  )  
)  

può andare?

2024-02-23 16:14 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +
![image](https://github.com/Error-418-SWE/Documenti/assets/77143275/963d6295-722a-45dd-8515-0b31fcab1547)

2024-02-24 16:11 UTC, ggardin approved these changes

2024-02-24 16:12 UTC, merged