DOC-531 Approfondito UC6
Error-418-SWE/Documenti pull request #320
Opened 2024-02-23 16:04 UTC by FakeDaemon

### Note

Approfondito UC6 aggiungendo la possibilità di popolare l'ambiente creando gli elementi automaticamente tramite indicazioni da database

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-23 16:23 UTC, Carraro-Riccardo requested changes

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- crea gli scaffali e li posiziona nell'ambiente come indicato nel database;
commento che può fare cardin "Quali proprietà". Esattamente come quando abbiamo scritto "Visualizzare le informazioni de prodotto"... "Quali informazioni?".

Espliciterei grazie a quali informazioni riesci a posizionarlo (basta anche solo dire coordinate di posizionamento X e Y  credo)

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- crea ogni ripiano di ogni scaffale secondo le proprietà fornite dal database;
come prima, definire le proprietà

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- crea i bin secondo le proprietà indicate dal database e li colloca dove indicato (all'interno di un ripiano o in un altra area valida);
come prima definire le proprietà

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il sistema è correttamente configurato con il database;
Questa frase non ha molto significato....

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il sistema crea gli scaffali con caratteristiche e posizione indicate nel database;
specifica di che caratteristiche di sta parlando

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il sistema crea i ripiani con caratteristiche e posizione indicate nel database;
typo ripiani

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il sistema crea i bin con caratteristiche e posizione indicate nel database;
specificare le caratteristiche

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il piano è popolato con scaffali, ripiani, bin e prodotti.
il piano -> l'ambiente

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il sistema popola il piano con scaffali, ripiani, bin e prodotti nelle posizioni e con le caratteristiche indicate nel database.
il piano -> l'ambiente

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il sistema popola il piano con scaffali, ripiani, bin e prodotti nelle posizioni e con le caratteristiche indicate nel database.
rimuovere la parte di caratterische da questa frase. Limitati a dire "Il sistema popola il piano con scaffali, ripiani, bin e prodotti secondo quanto stabilito nel database"

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [FD-6.0.1],[Desiderabile], [L'utente deve poter popolare automaticamente il piano leggendo i dati contenuti nel database], [UC-6],
il piano -> l'ambiente

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [FD-6.0.2],[Desiderabile], [L'utente deve poter popolare il piano con gli scaffali caricati da database], [UC-6],
il piano -> l'ambiente

2024-02-23 16:23 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +    [FD-6.0.3],[Desiderabile], [L'utente deve poter popolare gli scaffali  con i ripiani caricati da database], [UC-6],
Gli scaffali sono creati già con i ripiani, quindi questo è superfluo

2024-02-23 20:50 UTC, FakeDaemon commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- crea ogni ripiano di ogni scaffale secondo le proprietà fornite dal database;
mi sono accorto che non possiamo creare gli scaffali, ne gestirli, vengono creati con i parametri dati alla creazione dello scaffale, quindi ho rimosso

2024-02-23 20:55 UTC, FakeDaemon commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il sistema è correttamente configurato con il database;
era una precondizione, forse l'ho dimenticato e non me ne sono accorto

2024-02-23 20:58 UTC, FakeDaemon commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- il sistema crea i ripiani con caratteristiche e posizione indicate nel database;
non vedo il typo, puoi specificarlo meglio?

2024-02-23 22:24 UTC, Carraro-Riccardo requested changes

2024-02-23 22:24 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +A seguito della configurazione con il database il sistema:
Metterei una virgola tra “database” e “il sistema”

2024-02-24 14:33 UTC, Carraro-Riccardo approved these changes

2024-02-24 14:34 UTC, merged