DOC-515 Aggiunta struttura codificata ai rischi e loro opzioni di trattamento
Error-418-SWE/Documenti pull request #323
Opened 2024-02-24 02:37 UTC by SilvioNardo

### Note

Questa PR copre i task Doc-515 e Doc-516.

Nello specifico:
    - ho aggiunto le quattro categorie principali della struttura PMBOK;
    - ho spostato i rischi dentro le relative categorie;
    - ho aggiunto la codifica RIS-x.y  ai rischi dove "x" rappresenta il numero della categoria PMBOK mentre "y" rappresenta il 
       numero del rischio;
    - ho codificato le opzioni di trattamento OT-x-y-z dove "x" e "y" sono relative alle x e y del rischio corrispondente mentre "z" 
      è il numero dell'opzione di trattamento;
    - ho messo alcune sezioni (come le scritte "Opzioni di trattamento") in grassetto togliendo l'enumerazione con gli uguali;
    - ho aggiunto i tag <RIS-x.y> ai rischi;
    - ho messo i relativi codici OT-x.y.z nelle soglie;
    - ho modificato la descrizione e titolo del rischio RIS-4.3 (nel titolo ho messo "assegnati" al posto di "assegnate" e nella 
      descrizione ho aggiunto la frase "Il periodo rimanente senza task assegnati è sufficientemente ampio da permettere ai 
      membri coinvolti di proseguire i lavori.");
    - ho aggiunto degli accapo al posto del "/";
    - ho rimosso un paio di occorrenze di "l'azione correttiva di rischio" e ho lasciato solo riferimenti all'OT (opzione di 
       trattamento).
    
CONSIDERAZIONI:
    - Ho cercato di applicare la struttura PMBOK al nostro caso ma alcune cose (come la corretta categorizzazione dei rischi) 
       vanno discusse;
    - tutte le modifiche e le logiche di codifica andranno scritte nelle NdP;
    - non ho disposto i rischi in forma tabellare perché mi sono concentrato sulla loro struttura. Altri aspetti prettamente grafici 
       si possono implementare quando siamo sicuri della struttura;
    - i codici li ho scritti a mano sia per i rischi che per le OT perché non ho escogitato un modo migliore di farlo tramite le 
      funzioni typst.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-24 14:05 UTC, Carraro-Riccardo requested changes
Contenuto va bene nulla dire sui rischi e le soluzioni ad esse associate. Ho fatto parecchie osservazioni di stile riguardo i primi rischi individuati, stili come mettere il grassetto in alcuni punti, rimuovere un parte ricorrente, e aumentare lo spazio tra paragrafi.... nulla da ridire sul contenuto ma solo sulla sua presentazione. Tali richieste di cambiamento l'ho fatto per i primi rischi letti, quindi sono poi da riprodurre su tutti.

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - se, compreso un ragionevole rallentamento dovuto all'apprendimento di nuove competenze, la complessità delle tecnologie risulta gestibile con le competenze attuali del gruppo e non compromette si
lo dico qui poi in relazione anche a tutte le altre ricorrenze, rimuoverei quella "l'" prima dei nomi "OT-X.Y". Non suona bene a mio avviso. Mi sembra più immediato dire "si adotta OT-1.1.1" piuttosto che "si adotta l'OT-1.1".
Prima, senza il codice identificativo aveva senso mettere l'articolo, ora ne vedo meno la necessità.

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - se la complessità delle tecnologie supera significativamente le competenze attuali del gruppo e potrebbe quindi causare gravi ritardi nell'avanzamento dei lavori, si adotta l'"OT-1.1.1 Riduzione
rimuoverei  la l' da "l'OT-X.Y"

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Se si ritiene necessario, si richiede una maggiore partecipazione da parte degli altri membri del gruppo, con conseguente riassegnazione di attività e/o ruoli, per integrare le nuove tecnologie nel m
aggiungere un altro "invio" per separare un po'. Rischia se no di diventare un _wall of text_

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Le analisi tecnologiche precedentemente svolte devono essere riviste in luce delle nuove opzioni individuate. Queste ultime possono essere a loro volta totalmente o parzialmente sconosciute al gruppo
Queste ultime -> Quest'ultime

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
>  In caso di Accettazione del rischio è importante tenere monitorata nel tempo la situazione per accertarsi che le circostanze non richiedano una modifica nell'approccio di risoluzione.
Essendo questa parte già all'itnerno del paragrafo "Accettazione del rischio" ritengo che sia superfluo dire "In caso di Accettazione del Rischio", ma inizierei direttamente con "E' importante monitorare nel tempo la situazione...."

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +
aggiungerei un \  per separare maggiormente il paragrafo conseguenze da OT-1.1.2

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +
Aggiungerei un \ per dare maggiore spazio tra i due paragrafi

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Impatto: medio;
Metterei in grassetto il termine prima dei ":" (in questo caso *impatto*)

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Probabilità: 4;
Metterei in grassetto il termine prima dei ":"

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
>  - Soglie:
Metterei in grassetto il termine prima dei ":"

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Impatto: grave;
Metterei in grassetto il termine prima dei ":"

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Probabilità: 2;
Metterei in grassetto il termine prima dei ":"

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - se, compreso un ragionevole rallentamento dovuto all'apprendimento di nuove competenze, la complessità delle tecnologie risulta gestibile con le competenze attuali del gruppo e non compromette si
rimuoverei le virgolette intorno ai termini "OT-X.Y"

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - se la complessità delle tecnologie supera significativamente le competenze attuali del gruppo e potrebbe quindi causare gravi ritardi nell'avanzamento dei lavori, si adotta l'"OT-1.1.1 Riduzione
rimuoverei le virgolette intorno ai termini "OT-X.Y"

2024-02-24 14:05 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - se le lacune teoriche sono sufficientemente contenute da permetterene un recupero abbastanza rapido da non inficiare sulla pianificazione dei lavori, si adotta l'"OT-1.2.1 Eliminazione del rischi
typo: permetterne*

2024-02-24 14:05 UTC, Carraro-Riccardo requested changes
Contenuto va bene nulla dire sui rischi e le soluzioni ad esse associate. Ho fatto parecchie osservazioni di stile riguardo i primi rischi individuati, stili come mettere il grassetto in alcuni punti, rimuovere un parte ricorrente, e aumentare lo spazio tra paragrafi.... nulla da ridire sul contenuto ma solo sulla sua presentazione. Tali richieste di cambiamento l'ho fatto per i primi rischi letti, quindi sono poi da riprodurre su tutti.

2024-02-24 17:04 UTC, SilvioNardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +Se si ritiene necessario, si richiede una maggiore partecipazione da parte degli altri membri del gruppo, con conseguente riassegnazione di attività e/o ruoli, per integrare le nuove tecnologie nel m
ho aggiunto un accapo tra "...rischio." e "Se si ritiene..."
se intendi che vada messo più spazio prima di "*conseguenze*" allora devo per forza aggiungere "/"

2024-02-24 17:22 UTC, SilvioNardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - se, compreso un ragionevole rallentamento dovuto all'apprendimento di nuove competenze, la complessità delle tecnologie risulta gestibile con le competenze attuali del gruppo e non compromette si
io le lascerei perché identificano il titolo della sezione specifica

2024-02-24 17:22 UTC, SilvioNardo commented on 3 - PB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +  - se la complessità delle tecnologie supera significativamente le competenze attuali del gruppo e potrebbe quindi causare gravi ritardi nell'avanzamento dei lavori, si adotta l'"OT-1.1.1 Riduzione
come sopra

2024-02-25 13:58 UTC, Carraro-Riccardo approved these changes

2024-02-25 14:05 UTC, merged