DOC-545 Aggiornare i grafici di monitoraggio delle metriche
Error-418-SWE/Documenti pull request #334
Opened 2024-02-27 20:12 UTC by Carraro-Riccardo

### Note
DOC-545

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-28 13:25 UTC, FakeDaemon requested changes

2024-02-28 13:25 UTC, FakeDaemon commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
>  #figure(
nessun problema, solo la legenda di PPV, PAC e PEV viene visualizzata male con la dicitura PPV che esce dal riquadro

2024-02-28 13:26 UTC, FakeDaemon commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
>  #figure(
dimmi se mergiare comunque e aprire un ticket a parte per questa cosa o se la sistemi direttamente qui

2024-02-28 19:53 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
>  #figure(
Sì il problema è dovuto al glossario con la G al pedice... ne sono consapevole... al momento non ho una soluzione

2024-02-29 13:26 UTC, FakeDaemon commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
>  #figure(
va bene, approvo e poi andrà poi risolto in futuro

2024-02-29 13:26 UTC, FakeDaemon approved these changes

2024-02-29 13:26 UTC, merged