DOC-540 Redigere verbale retrospettiva 25-2-24
Error-418-SWE/Documenti pull request #338
Opened 2024-02-28 16:17 UTC by FakeDaemon

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-29 14:42 UTC, TodescoMattia commented on 3 - PB/Documentazione interna/Verbali/24-02-25/24-02-25.typ
> +Viene pianificata una riunione interna in data 26/02 alle ore 3:00 per discutere del design che il sistema software dovrà implementare.
ore 15:00 direi

2024-02-29 14:43 UTC, TodescoMattia commented on 3 - PB/Documentazione interna/Verbali/24-02-25/24-02-25.typ
> +- $"SEV" >= "SPV"$
qui va il punto a fine elenco direi

2024-02-29 14:48 UTC, TodescoMattia commented on 3 - PB/Documentazione interna/Verbali/24-02-25/24-02-25.typ
> +Predisposta la repo per contenere materiali inerenti la PB.
io scriverei repository interamente. repo mi sa da termine colloquiale

2024-03-01 10:45 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Verbali/24-02-25/24-02-25.typ
> +Predisposta la repo per contenere materiali inerenti la PB.
repo è un termine del glossario, quindi non dovrebbero esserci problemi

2024-03-01 16:04 UTC, AlessioBanzato requested changes

2024-03-01 16:04 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-02-25/24-02-25.typ
> +- aggiornamento capitolo 4.6.4 per quanto riguarda l'introduzione di variabili Typst per l'uso di termini ricorrenti.
punto e virgola e non punto

2024-03-01 16:04 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-02-25/24-02-25.typ
> +Come nello sprint precedente viene riconosciuto il ruolo del verificatore che ha saputo offrire review precise e tempestive.
Verificatore, "V" maiuscola

2024-03-01 16:04 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-02-25/24-02-25.typ
> +Lo sprint 16 ha visto le task assegnate completate nei tempi previsti, non sono stati riscontrati rallentamenti o problematiche significative.
Sprint, "S" maiuscola

2024-03-01 16:04 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-02-25/24-02-25.typ
> +Come nello sprint precedente il gruppo ha saputo mantenere una modalità di lavoro e di comunicazione asincrona.
Sprint, "S" maiuscola

2024-03-01 20:17 UTC, AlessioBanzato approved these changes

2024-03-01 20:31 UTC, TodescoMattia approved these changes

2024-03-01 20:37 UTC, merged