DOC-165 Aggiunto capitolo "Processo di integrazione"
Error-418-SWE/Documenti pull request #339
Opened 2024-02-28 16:46 UTC by SilvioNardo

### Note
I file yml non hanno il numero di versione, in caso li tolgo

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-02-29 14:03 UTC, FakeDaemon requested changes

2024-02-29 14:03 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +È quindi necessario il coordinamento con i processi di [@processo_definizione_architettura] e [@processo_design].
inserisci il nome del processo per intero e riporta i riferimenti al paragrafo dentro parentesi tonde per conformità con il resto del documento

2024-02-29 14:03 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il processo di integrazione ha lo scopo di combinare iterativamente elementi software al fine di ottenere un prodotto che soddisfi i requisiti rispettando l'architettura e il design definiti.
Cambierei la prima frase in:
Il processo di integrazione ha come scopo quello di sintetizzare un insieme di elementi in un sistema compiuto che soddisfa i requisiti software, architetturali o di design

2024-02-29 14:03 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +L'integrazione del sistema software avviene automaticamente mediante strumenti che permettano la Continuous Integration.
vai a capo con questa frase

2024-02-29 14:03 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- vengono identificati i risultati ed eventuali anomalie.
aggiungere che l'operazione di integrazione dell'elemento software nel sistema viene tracciata dalla pr su github

2024-02-29 14:03 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  - costruire l'immagine Docker e pubblicarla su Docker Hub e GitHub Container Registry tramite il file _build_docker.yml_;
tramite la action build_docker, le cui caratteristiche e job sono descritti nel file build_docker.yml

2024-02-29 14:03 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  - creare, tramite il file _tag_semver.yml_, un tag di versione semantica per ogni push sul branch di development del Version Control System. Tale tag viene pubblicato su GitHub e viene creata una r
tramite la action tag_semver, le cui caratteristiche e job sono descritti nel file tag_semver.yml, ...

2024-02-29 14:03 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  - l'esecuzione dei test avviene tramite il file _test_nodejs.yml_.
tramite la action test_nodejs, le cui caratteristiche e job sono descritti nel file test_nodejs.yml

2024-02-29 14:03 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +
aggiungere che l'esito dei test effettuati sull'elemento software da integrare viene registrato su github

2024-03-02 15:49 UTC, SilvioNardo commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- vengono identificati i risultati ed eventuali anomalie.
la aggiungo anche su gestione dei risultati

2024-03-02 15:55 UTC, SilvioNardo commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il processo di integrazione ha lo scopo di combinare iterativamente elementi software al fine di ottenere un prodotto che soddisfi i requisiti rispettando l'architettura e il design definiti.
reputo più corretta la mia versione

2024-03-02 21:41 UTC, FakeDaemon requested changes

2024-03-02 21:41 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  Gli elementi software implementati attivano il processo di integrazione dal momento in cui le modifiche presenti nella pull request vengono approvate da un verificatore, il quale attua la funzione
Verificatore con la V maiuscola

2024-03-03 11:27 UTC, FakeDaemon approved these changes

2024-03-03 11:35 UTC, merged