DOC-80 Miglioramenti alla formattazione dei documenti
Error-418-SWE/Documenti pull request #34
Opened 2023-11-21 15:59 UTC by ggardin

Link alla issue di Jira: https://error418swe.atlassian.net/browse/DOC-80?atlOrigin=eyJpIjoiMTM0MDA4MDM4YTJlNGNmN2IxNWFmZTlkNGFjZjVhODYiLCJwIjoiaiJ9

Note:
- riscritto il template grazie a @Carraro-Riccardo (alcuni cambiamenti sono breaking!);
- `roles.json` contiene i ruoli dei membri del gruppo durante l'intera durata del progetto;
- ho aggiornato il workflow di compilazione perché ora è richiesto che il file `roles.json` sia nella stessa directory di lavoro del documento.

### ✏️ Checklist

- [x] documento testato;
- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-11-21 19:35 UTC, TodescoMattia requested changes
Se te lo stessi chiedendo, si, mi sono divertito a scrivere Antonio* 10 volte tipo. Oltre a quello non mi pare di notare altre problematiche

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Analista",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Responsabile",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Progettista",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Verificatore",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Analista",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Programmatore",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Amministratore",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Programmatore",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Verificatore",
Antonio*

2023-11-21 19:35 UTC, TodescoMattia commented on roles.json
> +			"Oseliero Antionio": "Programmatore",
Antonio*

2023-11-22 08:43 UTC, ggardin commented
> Se te lo stessi chiedendo, si, mi sono divertito a scrivere Antonio* 10 volte tipo. Oltre a quello non mi pare di notare altre problematiche

Corretto!

2023-11-22 15:44 UTC, TodescoMattia approved these changes
buono!

2023-11-22 15:44 UTC, merged