DOC-164 Redigere sezione Technical Processes/Implementation Process
Error-418-SWE/Documenti pull request #347
Opened 2024-03-02 16:10 UTC by FakeDaemon

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-02 17:18 UTC, AlessioBanzato requested changes
Il contenuto in generale va bene, c'è solo qualche errore da correggere nella forma

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Fondamentale per garantire il livello di qualità richiesto dal #pdq è definire test per l'elemento di sistema che si vuole realizzare secondo il modello di sviluppo _Test Driven Development_. Questo
A fine paragrafo manca l'apostrofo su "dell'elemento"

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Come risultato della corretta implementazione del processo di implementazione otteniamo:
Dato che viene ripetuto il termine "implementazione", modificherei con "Come risultato della corretta implementazione del processo otteniamo:", oppure in un altro modo che viene in mente a te

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- l'implementazione viene tracciata.
Cambierei in "tracciamento dell'implementazione".

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Fondamentale per garantire il livello di qualità richiesto dal #pdq è definire test per l'elemento di sistema che si vuole realizzare secondo il modello di sviluppo _Test Driven Development_. Questo
Progettista, "P" maiuscola

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Data la mole di elementi grafici o interazioni utente che non sono né facili, né economici da testare automaticamente viene definito una modalità di testing manuale. Chi sviluppa l'elemento di sistem
"... viene **definita** una modalità ..."

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Data la mole di elementi grafici o interazioni utente che non sono né facili, né economici da testare automaticamente viene definito una modalità di testing manuale. Chi sviluppa l'elemento di sistem
Personalmente metterei i due punti dopo "test manuale", ma se non ti convincono lascia pure così

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Per aiutare il lavoro di verifica da parte del verificatore, riportare in pr tutte le funzionalità che si ha necessità di controllare manualmente.
Verificatore, "V" maiuscola

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Nel caso di codice riutilizzato o adattato si segue il metodo precedentemente descritto per certificare la bontà del codice introdotto.
Paragrafo non molto chiaro, lo riscriverei precisando che metodo utilizzare. Oppure potresti riscriverlo inserendolo nel paragrafo dove parli del metodo a cui ti riferisci

2024-03-02 17:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Decisa una strategia di testing per l'elemento di sistema e, se possibile, scritti i test di unità il programmatore può quindi cominciare lo sviluppo o l'adeguamento del software.
Programmatore, "P" maiuscola

2024-03-02 21:24 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Nel caso di codice riutilizzato o adattato si segue il metodo precedentemente descritto per certificare la bontà del codice introdotto.
ho modificato specificando la cosa sia nel primo che nel terzo paragrafo

2024-03-03 10:11 UTC, AlessioBanzato approved these changes

2024-03-03 10:11 UTC, merged