DOC-167 Redigere sezione Technical Processes/Transition Process
Error-418-SWE/Documenti pull request #363
Opened 2024-03-11 17:20 UTC by FakeDaemon

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-11 20:39 UTC, AlessioBanzato requested changes
Qualche piccolezza da cambiare ma in generale ottimo

2024-03-11 20:39 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +=== Risultati
Due opzioni per l'elenco di questa sezione:

1. si mantiene così ma prima si mette "..., otteniamo che:";
2. cambiare l'elenco in:

- redazione del #man;
- formazione e supporto degli utenti nell'utilizzo del sistema;
- rilascio di una versione del sistema;
- deploy su Azure.


Se preferisci usare l'opzione 1 allora nel secondo punto sostiuirei "allenati" con "formati"

2024-03-11 20:39 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Le seguenti attività non sono quindi necessariamente consequenziali, ma la loro corretta applicazione porta il conseguimento dei risultati precedentemente descritti.
"... porta ~~il~~ _al_ conseguimento..."

2024-03-11 20:39 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +In particolare descriviamo:
Toglierei questa riga

2024-03-11 20:39 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +La repository Github dedicata a WMS3 si compone di un branch _dev_ necessario per gli sviluppatori, in quanto fonte da cui vengono creati i feature branch necessari al conseguimento degli obiettivi d
- ~~Github~~ -> GitHub;
- nomi dei branch in `monospace` per coerenza con il resto del documento.

2024-03-11 20:39 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +I rilasci del prodotto avvengono sempre dal ranch di partenza _dev_ a quello di destinazione _release_, in quanto solo il codice contenuto in _dev_ soddisfa i requisiti di qualità imposti dal gruppo
- ~~ranch~~ -> branch;
- _dev_ -> `dev`;
- _release_ -> `release`;
- _dev_ -> `dev`.

2024-03-11 20:39 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il gruppo ha definito una GitHub Action chiamata _Deploy to VPS_ (i cui job sono descritti nel file deploy.yml) il cui compito è quello di effettuare il deploy del sistema aggiornato all'ultima versi
- deploy.yml va in corsivo;
- dev -> `dev`.

2024-03-11 20:39 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- guida al'utilizzo delle interfacce per la creazione, modifica e popolamento dell'ambiente 3D.
_all'_ utilizzo

2024-03-11 22:09 UTC, TodescoMattia commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +La repository Github dedicata a WMS3 si compone di un branch _dev_ necessario per gli sviluppatori, in quanto fonte da cui vengono creati i feature branch necessari al conseguimento degli obiettivi d
mi aggiungo a gamba tesa un secondo, repository è maschile (almeno nei nostri documenti di solito)

2024-03-13 10:02 UTC, FakeDaemon commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +=== Risultati
ho preferito la prima opzione perché più conforme al resto dei capitoli

2024-03-13 10:18 UTC, AlessioBanzato approved these changes

2024-03-13 10:19 UTC, merged