DOC-577 Estendere UC relativi all'ambiente 3D
Error-418-SWE/Documenti pull request #366
Opened 2024-03-12 23:25 UTC by ggardin

### Note

Sottopongo a review questa prima parte.

- Aggiunti riferimenti ai capitoli dei requisiti
- Aggiunto paragrafo sui requisiti prestazionali
- Riorganizzati script Typst di supporto
- Scritta introduzione alla sezione UC
- Stesura UC1
- Stesura UC2
- Stesura UC3
- Stesura UC4, UC5, UC6
- Stesura UC7

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-12 23:33 UTC, ggardin commented
Per qualche ragione il mio [ultimo commit](https://github.com/Error-418-SWE/Documenti/commit/e837958e14650cc7ea55b407e24197b14de21c6a) non è ancora apparso qui nella PR. Ricontrollo domani mattina e casomai riapro la PR.

2024-03-13 14:01 UTC, AlessioBanzato requested changes
Niente da dire sul contenuto, anche i diagrammi vanno bene. Ci sono solo una svista su un UC e sulla numerazione in un diagramma

2024-03-13 14:01 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +)
Mancano le Estensioni

2024-03-13 14:01 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "Come utente, desidero definire il passo della griglia di aggancio per poter disporre le zone in modo ordinato. Il passo è un numero non negativo espresso in metri."
Rimuovere punto al termine della User story

2024-03-13 14:01 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/imgs/UC11.svg
- Titolo nel rettangolo generale, ~~UC-8~~ -> UC-11;
- ~~UC-8.4~~ Reset planimetria -> UC-11.3 Reset planimetria;
- ~~UC-8.5~~ Rimozione dati importati-> UC-11.4 Rimozione dati importati.

2024-03-13 14:01 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "La lista delle movimentazione è stata azzerata",
"La lista delle movimentazion**i** ..."

2024-03-13 14:27 UTC, AlessioBanzato approved these changes

2024-03-14 14:00 UTC, AlessioBanzato requested changes

2024-03-14 14:00 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  [Visualizzazione profondità prodotto (@uca.6)],
Le dimensioni visualizzate sono larghezza, lunghezza e altezza. Sostituire profondità con altezza

2024-03-14 14:00 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
Rimuovere riga vuota

2024-03-14 14:00 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== Visualizzazione profondità prodotto <uca.6>
Anche qui sostituire profondità con altezza, nel titolo e nella descrizione del UC

2024-03-14 14:00 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/imgs/UCa.1.svg
UCa.6: sostituire profondità con altezza

2024-03-14 14:00 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== Visualizzazione ID prodotto <uca.1>
Piccolo dubbio: perché in questi UC, o anche nelle generalizzazioni della ricerca, non vengono scritte le User Story? Ipotizzo sia perché derivino tutti dalla User story del UC principale, però, ad esempio, nel UC-11 (Reimpostazione ambiente 3D), le inclusioni hanno tutte una loro User story associata

2024-03-14 14:12 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +===== Visualizzazione errore spostamento impossibile <ucd.2.1>
Aggiungo quest'altra osservazione come commento: in questi UC la struttura della descrizione degli errori è diversa dagli UC visti ieri. Su quelli delle Zone la visualizzazione dell'errore è vista come postcondizione, mentre qui come scenario principale

2024-03-14 15:00 UTC, giogardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== Visualizzazione ID prodotto <uca.1>
Li ho omessi perché mi sembravano tutte ripetizioni della stessa cosa, ma effettivamente inserirli non costa nulla

2024-03-14 15:14 UTC, giogardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +===== Visualizzazione errore spostamento impossibile <ucd.2.1>
Grazie grazie grazie, questa era una svista che poteva costarci caro

2024-03-15 10:33 UTC, AlessioBanzato requested changes

2024-03-15 10:33 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  [Ricerca prodotti (@ucc)]
Ricerca prodotti (`@ucc`) -> Ricerca zona (`@ucr`)

2024-03-15 10:33 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "L'utente richiede lo spostamento del POV così da inquadrare la zona"
Forse sostituirei "richiede lo spostamento" con "effettua lo spostamento", ma vedi te come preferisci

2024-03-15 10:33 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "L'utente richiede lo spostamento del POV così da inquadrare il bin"
Idem qui la proposta di sostituzione

2024-03-15 14:11 UTC, ggardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "L'utente richiede lo spostamento del POV così da inquadrare la zona"
Ho messo così per sottolineare il fatto che non è l'utente che muove l'inquadratura ma il sistema che la pilota sulla base di un input dell'utente. Scrivere "effettua lo spostamento" mi sembra simile agli UC di spostamento dell'inquadratura

2024-03-15 14:12 UTC, ggardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "L'utente richiede lo spostamento del POV così da inquadrare il bin"
[Risposta alla conversazione analoga](https://github.com/Error-418-SWE/Documenti/pull/366#discussion_r1526351008)

2024-03-16 13:37 UTC, AlessioBanzato requested changes

2024-03-16 13:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "Precondizioni",
Nelle precondizioni aggiungerei che è presente almeno una zona nell'ambiente 3D. Se l'ambiente è vuoto lo sarà anche la lista zone, quindi non posso vederne il singolo elemento

2024-03-16 13:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "Precondizioni",
Anche qui stesso discorso del commento precedente

2024-03-16 14:22 UTC, ggardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "Precondizioni",
Effettivamente hai ragione, aggiungo

2024-03-17 10:18 UTC, AlessioBanzato requested changes

2024-03-17 10:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "L'utente visualizza la altezza della zona selezionata"
*l'altezza

2024-03-17 10:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  caption: "Diagramma UC--q.3"
Non so se il numero dopo il punto rimarrà quello, ma qui sarebbe "Diagramma UC--q.6"

2024-03-17 10:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "Come utente, desidero visualizzare le informazioni associate ai bin presenti nell'ambiente 3D"
Nella user story del UC-q hai aggiunto "come dimensioni e bin presenti al suo interno", così da evitare le user story dei sotto-uc riguardo quelle cose (almeno, immagino sia per quello). Dato che non hai inserito le User story negli UC-i.x, direi di fare una cosa simile al UC-q e aggiungere quindi "... nell'ambiente 3D, come ID e dimensioni."

2024-03-17 10:18 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- *Zone e Bin* (@uc-zone): operazioni CRUD sulle zone e gestione dei bin;
In questo punto e in quello dopo della lista, il tag alle sezioni viene visualizzato come "Caso d'uso x.y" e non "Sezione x.y"

2024-03-17 20:48 UTC, AlessioBanzato requested changes

2024-03-17 20:48 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/imgs/UC12.svg
Mancano i trattini tra "UC" e il numero del UC

2024-03-17 20:48 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/imgs/UC12.4.svg
Anche qui mancano i trattini

2024-03-17 20:48 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/imgs/UC12.5.svg
Anche qui mancano i trattini

2024-03-17 20:48 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "Scenari alternativi",
C'è lo scenario alternativo ma non c'è l'estensione per la visualizzazione dell'errore

2024-03-17 20:48 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "La larghezza della zona è calcolata come la somma delle larghezze delle singole colonne"
Dato che questo caso d'uso include la definizione della larghezza della zona da parte dell'utente, toglierei questa postcondizione

2024-03-17 20:48 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "Scenari alternativi",
Anche qui c'è lo scenario alternativo ma non l'estensione

2024-03-18 07:46 UTC, AlessioBanzato requested changes

2024-03-18 07:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/imgs/UC13.svg
"Definizione lunghezza" e la sua estensione sono rispettivamente UC-12.2 e UC-12.2.1

2024-03-18 15:09 UTC, AlessioBanzato requested changes

2024-03-18 15:09 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  [Visualizzazione errore numero livelli minore di zero (@uc12.5.1.1)]
*minore _o uguale a_ zero

2024-03-18 15:09 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +====== Visualizzazione errore numero livelli minore di zero <uc12.5.1.1>
*minore _o uguale a_ zero

2024-03-18 15:09 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "L'utente visualizza un errore relativo al valore immesso minore di zero"
*minore _o uguale a_ zero

2024-03-18 15:09 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +  "L'utente inserisce un numero di livelli minore di zero"
*minore _o uguale a_ zero

2024-03-18 15:09 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/imgs/UC12.5.svg
Correggere titolo UC-12.5.1.1 -> Visualizzazione errore numero livelli minore o uguale a zero

2024-03-18 20:42 UTC, AlessioBanzato requested changes
Principalmente delle sviste, tutte cose che si correggono velocemente

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"description": "L'utente deve visualizzare un errore se la larghezza indicata non è positiva (>=0)",
In riferimento al contenuto delle parentesi: l'errore è quando la dimensione indicata è <=0. Se invece volevi indicare la positività deve essere solo ">0"

Per evitare di scrivere più commenti uguali: questa cosa è presente in diversi requisiti simili a questo, quindi modifica tutto con un bel Ctrl+F

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +		},
Manca il requisito legato alla visualizzazione dell'errore quando nel SVG non ci sono elementi grafici. Si potrebbe anche aggiungere come source nel FD-13 in realtà, se si può fare

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "Decisione interna",
Si potrebbe aggiungere anche l'UC-1.2.2 tra le fonti, però se vuoi lasciare così perché anche l'UC stesso deriva da una decisione interna allora va bene

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "Decisione interna",
Stesso discorso fatto per FD-14

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"description": "L'utente deve poter ridefinire la lunghezza dell'ambiente 3D corrente",
L'UC-2.1 indicato come fonte parla di larghezza

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"description": "L'utente deve poter ridefinire la larghezza dell'ambiente 3D corrente",
L'UC-2.2 indicato come fonte parla di lunghezza

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"id": "FM-22",
FD, in quanto riguarda l'SVG

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "Decisione interna",
Stesso discorso fatto qualche commento fa: si potrebbe aggiungere anche l'UC-2.3 tra le fonti, però se vuoi lasciare così perché anche l'UC stesso deriva da una decisione interna allora va bene

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"cat": "Obbligatorio",
Desiderabile, in quanto riguarda l'SVG

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"id": "FM-23",
Valgono i tre commenti fatti per il requisito precedente

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"id": "FM-56",
Se la possibilità di indicare un codice identificativo è desiderabile lo deve essere anche la visualizzazione dell'errore correlata

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"description": "L'utente deve poter scegliere tra `NS` e `WE` come orientamento della zona da creare",
I backtick non vengono trasformati in monospace nel pdf, quindi penso sia meglio eliminarli

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "VE",
VE 24-02-29

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "UC–16.1.1",
*UC-16.1.2

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "UC–19.4",
*UC-22

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "VE 23-11-15",
*VE 23-11-23

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"id": "FD-123",
Da **FD-123** a **FD-128**: discorso già fatto sull'aggiunta dell'UC di riferimento oltre a "Decisione interna", che riporto di seguito

_Si potrebbe aggiungere anche l'UC-x.y tra le fonti, però se vuoi lasciare così perché anche l'UC stesso deriva da una decisione interna allora va bene_

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "UC–26.1.1",
*UC-26.1.3

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"source": "UC–26.1.1",
*UC-26.1.4

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +	"quality": [
Nei requisiti di qualità è stato invertito l'ordine di presentazione di `source` e `cat`, nella tabella vengono visualizzati in modo errato

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +		}
Aggiungerei un requisito sulla Specifica Tecnica, del tipo

{
			"id": "QM-9",
			"source": "Decisione interna",
			"description": "Deve essere fornita la documentazione dell'architettura del prodotto",
			"cat": "Obbligatorio",
			"achieved": false
		}

2024-03-18 20:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +		{
- Anche su questi è stato invertito l'ordine di `source` e `cat`;
- Sostituire "Interno" con "Decisione interna" per coerenza con gli altri requisiti.

2024-03-19 08:26 UTC, ggardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +		}
Ha molto senso, aggiungo

2024-03-19 13:54 UTC, AlessioBanzato requested changes

2024-03-19 13:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"id": "FM-56",
~~FM~~ -> FD

2024-03-19 13:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"id": "FD-XX",
Manca il numero

2024-03-19 13:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"description": "L'utente deve visualizzare un errore se la larghezza indicata non è positiva (<=0)",
Solo un avviso, **non** è da modificare (a meno che tu non sappia già come fare): non so perché, visto che con ">=" funzionava, ma nel pdf viene visualizzato "<=" e non il simbolo matematico. Ho provato a inserire i dollari ma fa come con i backtick

2024-03-19 13:58 UTC, ggardin commented on 3 - PB/Documentazione esterna/Analisi dei Requisiti/requirements.json
> +			"description": "L'utente deve visualizzare un errore se la larghezza indicata non è positiva (<=0)",
Ops, devo aggiornare una regoletta di stile (sì l'unico modo di farlo è scrivendo una funzioncina hardcoded)

2024-03-19 14:14 UTC, AlessioBanzato approved these changes

2024-03-19 14:15 UTC, merged