DOC-591 aggiungere sezione requisiti
Error-418-SWE/Documenti pull request #368
Opened 2024-03-14 15:36 UTC by TodescoMattia

### Note
Fammi sapere se te ne vengono in mente altri perchè sto un po improvvisando su alcune cose

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-14 16:50 UTC, AlessioBanzato requested changes
Non ho trovato requisiti in più, giusto un paio di modifiche e ci siamo

2024-03-14 16:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +    [Docker],[>= 24.0.7],[https://docs.docker.com/],
In tutta la tabella mettere i ">=" tra due $, in modo che venga visualizzato con il simbolo corretto

2024-03-14 16:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +    [WSL (se da SO Windows)],[>= 1.1.3],[https://ubuntu.com/desktop/wsl],
Non penso sia necessario avere WSL se si lavora su Windows

2024-03-14 16:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +    [Virtualizzazione],[Abilitare la virtualizzazione hardware nel BIOS],
Anche questo non penso sia necessario

2024-03-14 16:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +    [Google Chrome],[>= 89],
Stesso discorso di prima riguardo i ">="

2024-03-14 16:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  caption: "Requisiti di sistema minimi."
Rimuovere il punto a termine caption in tutte le tabelle

2024-03-14 17:57 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +    [Virtualizzazione],[Abilitare la virtualizzazione hardware nel BIOS],
me lo segna come necessario per avviare docker uguale con wsl. Secondo te non è da mettere?

2024-03-14 17:57 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +    [WSL (se da SO Windows)],[>= 1.1.3],[https://ubuntu.com/desktop/wsl],
vedi sotto

2024-03-15 08:07 UTC, AlessioBanzato approved these changes

2024-03-15 08:12 UTC, merged