DOC-100 Aggiungere UC da 7 a 11
Error-418-SWE/Documenti pull request #39
Opened 2023-11-22 19:51 UTC by AlessioBanzato

Link alla issue di Jira: https://error418swe.atlassian.net/browse/DOC-100?atlOrigin=eyJpIjoiNTVjODczZWViZDQyNDk4OWIxM2JiMDM0YzMwN2ZlOGEiLCJwIjoiaiJ9

Note: Aggiunti gli use case dal numero 7 al numero 11 al file 'Analisi dei Requisiti.typ'

### ✏️ Checklist

- [x] documento testato;
- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-11-26 19:03 UTC, FakeDaemon requested changes

2023-11-26 19:03 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +l'area selezionata viene classificata come bin e non può essere sovrascritta.
l'area classificata come bin non è vero che non può più essere sovrascritta, può essere eliminata e i dati del bin possono essere modificati

2023-11-27 19:19 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +$bold("Descrizione: ")$
Qui ho un leggero dubbio: il caricamento degli elementi dal database avviene in maniera "automatica", pertanto non vi è un'azione manuale di inserimento di un prodotto in un bin. Questo use case lo aggiornerei più in una versione "Caricamento dei prodotti da database", dove l'utente "inizia la procedura di caricamento" configurando l'accesso al database, e successivamente i prodotti vengono posizionati nei rispettivi bin.

2023-11-27 19:23 UTC, Carraro-Riccardo requested changes

2023-11-27 19:23 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +=== UC10.1 - Assegnazione prodotto a bin non compatibile per dimensioni
Questo use case diventa impossibile dato quanto detto per quello precedente, essendo il programma stesso a caricare i prodotti. Inoltre, a seguito della mail di oggi, il proponente scrive "Facciamo affidamento al fatto che chi posiziona un articolo in un bin o chiede lo spostamento sappia se può essere contenuto o meno".

2023-11-28 17:00 UTC, merged