DOC-637 Redigere verbale esterno 22/03/2024
Error-418-SWE/Documenti pull request #392
Opened 2024-03-22 19:38 UTC by AlessioBanzato

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-25 16:31 UTC, Carraro-Riccardo requested changes

2024-03-25 16:31 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +Sono state presentate ai Proponenti le funzionalità dell'MVP sviluppate dall'ultimo incontro, in particolare:
Se non erro, il proponente è sempre singolare perchè individuabile come "l'Azienda". In questo caso potresti o mettere al singolare, o parlare di "referenti", just my opinion

2024-03-25 16:31 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +- configurazione dell'ambiente a partire da file SVG, e in conseguenza di questo:
toglierei "e in conseguenza di questo", lasciando solo i 2 punti dopo SVG

2024-03-25 16:31 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +  - caricamento da database e posizionamento nell'ambiente degli scaffali;
Più corretto denominarle zone. Btw si può riscrivere come "caricamento da database della struttura e organizzazione delle zone nell'ambiente;"

2024-03-25 16:31 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +
movimento della camera mediante tastiera (wasd e frecce direzionali)

2024-03-25 16:31 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +- *possibilità di muoversi all'interno dell'ambiente tramite tastiera*: se l'utente vuole spostare un bin in una zona non presente nell'inquadratura, potrà muovere la camera utilizzando la tastiera,
In realtà questo è già stato parzialmente mostrato, quello che intendiamo implementare entro il prossimo sprint è la seconda parte, ossia muovere la cam durante il dragging dell'oggetto (per ora la camera si muove già con la tastiera ma non mentre si fa il dragging)

2024-03-25 16:31 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +- *spostamento di un prodotto tramite _drag and drop_ dalla lista dei non collocati ad un bin*: risulta difficile implementare il _drag and drop_ poiché ci si deve spostare da un elemento di UI all'a
cambierei il titolo in "collocamento di un prodotto dalla lista dei non collocati all'interno di un bin vuoto"

2024-03-25 16:37 UTC, ggardin requested changes, later dismissed
Niente di che, ti ho solo lasciato dei reminder

2024-03-25 16:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +I Proponenti sono risultati soddisfatti delle funzionalità implementate.
"Proponente"

Riferimento: https://github.com/Error-418-SWE/Documenti/pull/392/files#r1537871281

2024-03-25 16:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +- *possibilità di muoversi all'interno dell'ambiente tramite tastiera*: se l'utente vuole spostare un bin in una zona non presente nell'inquadratura, potrà muovere la camera utilizzando la tastiera,
"Proponente"

Riferimento: https://github.com/Error-418-SWE/Documenti/pull/392/files#r1537871281

2024-03-25 16:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +Vengono illustrati ai Proponenti i pattern Factory e Strategy utilizzati per effettuare la ricerca di prodotti e zone.
"Proponente"

Riferimento: https://github.com/Error-418-SWE/Documenti/pull/392/files#r1537871281

2024-03-25 16:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +Vengono illustrati ai Proponenti i pattern Factory e Strategy utilizzati per effettuare la ricerca di prodotti e zone.
Direi inoltre "utilizzati per *implementare*"

2024-03-25 16:37 UTC, ggardin commented on 3 - PB/Documentazione esterna/Verbali/24-03-22/24-03-22.typ
> +Si concorda con i Proponenti che nei prossimi giorni il gruppo verrà aggiornato sulla struttura della lista di bug da consegnare a termine del progetto, come richiesto dal capitolato.
"Proponente"

Riferimento: https://github.com/Error-418-SWE/Documenti/pull/392/files#r1537871281

2024-03-26 20:03 UTC, Carraro-Riccardo approved these changes

2024-03-27 09:26 UTC, merged