DOC-638 Redigere verbale interno 22/03/2024
Error-418-SWE/Documenti pull request #393
Opened 2024-03-22 19:52 UTC by AlessioBanzato

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-25 16:36 UTC, Carraro-Riccardo requested changes

2024-03-25 16:36 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-03-22/24-03-22.typ
> +A seguito dell'incontro con i Proponenti, il gruppo ha svolto un meeting interno riguardante:
Se non erro, il proponente è sempre singolare perchè individuabile come "l'Azienda". In questo caso potresti o mettere al singolare, o parlare di "referenti", just my opinion

2024-03-25 16:36 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-03-22/24-03-22.typ
> +Non vengono aggiunte nuove task allo Sprint. Si prosegue, dunque, con le attività pianificate in retrospettiva. In particolare, si punta alla conclusione dell'MVP con l'implementazione delle funziona
Segnerei quali

2024-03-25 16:36 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-03-22/24-03-22.typ
> +
Aggiungerei una nota per giustificare un verbale di ridotte dimensioni come questo, come ad esempio "Data la natura dimostrativa del meeting esterno e l'avvicinarsi della conclusione del progetto didattico, non sono emerse ulteriori discussioni: il lavoro da svolgere è chiaro ai membri del gruppo secondo quanto stabilito e pianificato prima dello sprint corrente."

Qualcosa del genere, riformulato magari.

2024-03-25 16:38 UTC, ggardin requested changes, later dismissed
Buono, ho solo lasciato dei reminder.

2024-03-25 16:38 UTC, ggardin commented on 3 - PB/Documentazione interna/Verbali/24-03-22/24-03-22.typ
> +  - i Proponenti hanno apprezzato la UI e le funzionalità del MVP;
"Proponente"

Riferimento: https://github.com/Error-418-SWE/Documenti/pull/392/files#r1537871281

2024-03-25 16:38 UTC, ggardin commented on 3 - PB/Documentazione interna/Verbali/24-03-22/24-03-22.typ
> +  - i consigli dei Proponenti riguardo l'implementazione del collocamento manuale di un prodotto in un bin sono risultati ottimi, in quanto semplificheranno lo sviluppo di tale funzionalità.
"Proponente"

Riferimento: https://github.com/Error-418-SWE/Documenti/pull/392/files#r1537871281

2024-03-26 20:02 UTC, Carraro-Riccardo approved these changes

2024-03-27 09:25 UTC, merged