DOC-654 Estendere sezione Tecnologie
Error-418-SWE/Documenti pull request #406
Opened 2024-03-27 12:50 UTC by Carraro-Riccardo

### Note

[DOC-654]

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

[DOC-654]: https://error418swe.atlassian.net/browse/DOC-654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-03-27 14:29 UTC, AlessioBanzato requested changes
Ottimo, solo qualche svista

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
>  Gli aspetti fondamentali riguardano l'architettura implementativa, analizzazndo tecnologie e design pattern adottati, e l'archietettura di deployment del prodotto.
Typo in "architettura di deployment"

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- Definizione struttura componenti web;
Punto e non punto e virgola

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- Definizione stile e layout componenti web;
Punto e non punto e virgola

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *Link: * [https://tailwindcss.com/]
Le parentesi quadre sono una scelta stilistica? Per mio gusto le toglierei, ma se preferisci tenerle va bene uguale

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +=== Typescript
*TypeScript

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Typescript è un superset di JavaScript che aggiunge tipizzazione statica al linguaggio, offrendo maggiore struttura al codice. Questo permette di rilevare errori di programmazione in fase di sviluppo
*TypeScript

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- Implementazione dei componenti react;
*React

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *Link: * [https://shadcn-ui.com/]
Link sbagliato, il link corretto è `https://ui.shadcn.com/`

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Jest è un framework di testing per JavaScript e Typescript. Viene utilizzato principalmente per lo unit e l'integration testing, offrendo funzionalità avanzate come la parallelizzazione dei test e il
*TypeScript

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Container docker utilizzati*
- *Docker;
- I container non si chiamano postgres e frontend? Se sì vanno modificati anche nella sezione "Installazione".

2024-03-27 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- Gestione dell'orchestrazione dei container Docker utilizzati;
Punto e non punto e virgola

2024-03-27 16:32 UTC, giogardin requested changes
Buono, solo qualche dettaglio minore

2024-03-27 16:32 UTC, giogardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
>  Gli aspetti fondamentali riguardano l'architettura implementativa, analizzazndo tecnologie e design pattern adottati, e l'archietettura di deployment del prodotto.
~analizzazndo~ analizzando

2024-03-27 16:32 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Il presente documento si pone come obiettivo la descrizione dettagliata delle scelte progettuali effettuate, al fine di garantire una comprensione chiara e completa del software "WMS3: Warehouse Mana
- "**ha** come obiettivo"
- "3D, proposto da Sanmarco Informatica S.p.A."

2024-03-27 16:32 UTC, giogardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +HTML (HyperText Markup Language) è il linguaggio di markup standard utilizzato per la creazione di pagine web. Viene utilizzato per definire la struttura e il contenuto delle pagine web.
Attenzione che React non usa HTML, bensì [JSX](https://en.wikipedia.org/wiki/JSX_(JavaScript)). Che poi produca HTML **credo** sia un discorso che trascende lo scopo di questo paragrafo

2024-03-27 16:32 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *Link: * [https://tailwindcss.com/]
Se scelta stilistica sono da togliere, perché negli altri documenti non ci sono. Inoltre aggiungere anche `#lastVisitedOn(27, 03, 2024)` per ciascun link

2024-03-27 16:32 UTC, giogardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - Framework di sviluppo web front-end basato su React e utilizzato per la creazione di applicazioni web. Offre funzionalità avanzate come il rendering lato server, la generazione di pagine statiche
- Il rendering lato server forse eviterei di nominarlo esplicitamente... l'ultima volta è stato un trigger pavloviano 👀 Metterei piuttosto la possibilità di realizzare API, il middleware, o qualsiasi altra cosa
- "~delle route~" > "del _routing_"

2024-03-27 16:32 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - Libreria JavaScript utilizzata per la creazione di interfacce utente dinamiche e reattive. Si basa sul concetto di "components", ovvero blocchi di codice autonomi che gestiscono la propria logica
"~e~ reattive e _stateful_"

2024-03-27 16:32 UTC, giogardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- *Shadcn-UI*
shadcn/ui

2024-03-27 16:32 UTC, giogardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - Libreria di componenti React personalizzati per la creazione di interfacce utente. Offre una serie di componenti pronti all'uso per la realizzazione di interfacce grafiche.
Non è una lib, è una raccolta

2024-03-27 16:32 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Librerie e framework ambiente 3D*
Cambierei l'ordine perché sono uno l'estensione del precedente: Three, Fiber, Drei

2024-03-27 16:32 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- *Fiber*
@react-three/fiber

2024-03-27 16:32 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- *Drei*
@react-three/drei

2024-03-27 16:32 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- Deployment del software “WMS3” mediante container Docker;
Virgolette non standard, meglio usare quelle normali `"`

2024-03-27 16:32 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Container docker utilizzati*
Sono immagini, non container (come correttamente scritto poco sotto)

2024-03-27 19:21 UTC, Carraro-Riccardo commented
@ggardin per quanto riguarda la correzione in merito a HTML, ho rimosso la tecnologia... dimmi se in caso è preferibile porre JSX

2024-03-27 22:04 UTC, ggardin commented
È un linguaggio e se sono stati inclusi anche gli altri linguaggi allora lo terrei.

Ma che ne direste di non raggruppare per linguaggio ma semplicemente fare la lista delle tecnologie usate e, per ciascuna, indicare il linguaggio che usa? Molto del paragrafo in oggetto riporta una breve descrizione del linguaggio, ma quella è già contenuta nel Glossario.

2024-03-28 08:55 UTC, AlessioBanzato commented
> Ma che ne direste di non raggruppare per linguaggio ma semplicemente fare la lista delle tecnologie usate e, per ciascuna, indicare il linguaggio che usa? Molto del paragrafo in oggetto riporta una breve descrizione del linguaggio, ma quella è già contenuta nel Glossario.

Sì, secondo me può aver senso fare così

2024-03-29 08:41 UTC, AlessioBanzato requested changes, later dismissed

2024-03-29 08:41 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- @react-three/drei: \
Aggiungere carattere di escape altrimenti non compila

2024-03-29 08:41 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- @react-three/fiber: \
Aggiungere carattere di escape altrimenti non compila

2024-03-29 18:12 UTC, ggardin requested changes
Domani vorrei discutere della struttura della prima parte della sezione. Il contenuto va bene.

2024-03-30 09:26 UTC, ggardin requested changes

2024-03-30 09:26 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +== Tencologie per la validazione dei dati
Typo in tecnologia

2024-04-02 15:45 UTC, ggardin approved these changes

2024-04-02 15:47 UTC, merged