DOC-618 Revisionare sezione Processo di Integrazione
Error-418-SWE/Documenti pull request #407
Opened 2024-03-27 14:39 UTC by TodescoMattia

### Note
Creo una draft perchè mi servirebbero consigli su cosa aggiungere.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-28 14:37 UTC, AlessioBanzato requested changes
Oltre a queste correzioni non saprei benissimo cosa aggiungere. Dato che Riccardo è impegnato con la Specifica Tecnica, sento se Giovanni è disponibile a dare un'occhio

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Per supportare l'integrazione e il deployment, è disponibile un Virtual Private Server su Azure che ospita un ambiente Docker, su cui viene eseguito il container con l'ultima versione del prodotto di
Azure va tolto. Se riesci, andrebbe tolto anche da processo di transizione, e se c'è da riformulare frasi in conseguenza fai pure, che poi controllo tutto

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>  È quindi necessario il coordinamento con il processo di definizione dell'architettura (@processo_definizione_architettura) e il processo di design (@processo_design).
*processo di definizione del design

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  La strategia di integrazione definita dal gruppo si basa sull'adozione delle pratiche "Continuous Integration" e "Continuous Deployment", al fine di garantire un frequente allineamento degli ambien
Cambierei in

"Il gruppo deve basare la propria strategia di integrazione sulle pratiche di _continuous integration_ e _continuous deployment_, al fine di permettere il frequente allineamento degli ambienti di lavoro tra i membri e disporre sempre della versione più recente del prodotto."

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    Essa prevede la gestione dell'integrazione degli elementi software e dell'esecuzione dei test di unità, integrazione e non regressione mediante automazioni GitHub Actions.
Togliere i test di non regressione

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    Testare automaticamente il prodotto ad ogni iterazione garantisce inoltre il rispetto dei requisiti descritti nel documento #adr_v e i processi di verifica.
Eliminare questa riga

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  Gli elementi software implementati attivano il processo di integrazione dal momento in cui le modifiche presenti nella Pull Request vengono approvate da un Verificatore, il quale attua la funzione
- "... vengono ~~approvate~~ accettate da un Verificatore, il quale ~~attua la funzione di~~ approva il merge."

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    Le GitHub Action provvedono a:
Cambierei in:

"Le GitHub Actions sviluppate dal gruppo dovranno:"

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    - copiare il contenuto del repository sul Virtual Private Server e proseguire con l'avvio di Docker Compose tramite il file _deploy.yml_;
Togliere, riferimento ad Azure

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    - l'esecuzione dei test avviene tramite la action "test_nodejs", le cui caratteristiche e job sono descritti nel file _test_nodejs.yml_.
Togliere, se ne parla nel processo di verifica e, se non sbaglio, non vengono eseguiti al merge della PR

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    - creare, tramite la action "tag_semver", le cui caratteristiche e job sono descritti nel file _tag_semver.yml_, un tag di versione semantica per ogni push sul branch di development del Version Con
Questo è da mettere come primo punto, perché è la prima cosa che accade

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    - creare, tramite la action "tag_semver", le cui caratteristiche e job sono descritti nel file _tag_semver.yml_, un tag di versione semantica per ogni push sul branch di development del Version Con
`tag_semver.yml`, in monospace

2024-03-28 14:37 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    - costruire l'immagine Docker e pubblicarla su Docker Hub e GitHub Container Registry tramite la action "build_docker", le cui caratteristiche e job sono descritti nel file _build_docker.yml_;
`build_docker.yml`, in monospace

2024-03-28 18:04 UTC, ggardin commented
Ho quasi finito l'estensione. Mi manca l'ultimo paragrafo, "Manage results of integration", e risolvere le conversations rilevanti.

2024-03-28 21:01 UTC, ggardin commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
>    Essa prevede la gestione dell'integrazione degli elementi software e dell'esecuzione dei test di unità, integrazione e non regressione mediante automazioni GitHub Actions.
@Carraro-Riccardo è corretto parlare di test di regressione?

2024-03-29 14:10 UTC, AlessioBanzato requested changes
Ottimo, solo piccolezze

2024-03-29 14:10 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- il processo di definizione dell'architettura (@processo_definizione_architettura).
Gli ultimi due punti vanno invertiti: nell'ISO c'è prima quello di architettura. Andranno scambiati di ordine anche i capitoli dei processi, c'è già una task in backlog creata da Mattia

2024-03-29 14:10 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +La strategia di integrazione definita dal gruppo si basa sull'adozione delle pratiche di _Continuous Integration_ (CI) e _Continuous Deployment_ (CD), al fine di permettere un frequente allineamento
"~~ed~~ garantire" -> "e garantire"

2024-03-29 14:10 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- il processi di Verifica (@processo_verifica), per:
*processo

2024-03-29 14:10 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  + identificare e risolvere le anomalie riscontrate, sia nel software che negli elementi ad esso associati quali requisiti, test, architettura e design;
Punto alla fine

2024-03-29 14:10 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +L'integrazione degli elementi software, individuati e specificati tramite i processi di definizione dell'architettura(@processo_definizione_architettura) e di definizione del design (@processo_design
Aggiungere spazio dopo "definizione dell'architettura"

2024-03-29 14:10 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +A seguito di tali attività, il Verificatore può approvare la Pull Request e, tramite la funzione di _merge_, integrare l'elemento software implementato nel sistema software. A supporto di tale operaz
*Actions

2024-03-29 14:10 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  - `#minor`, per incrementare il numero di minor (y);
Punto alla fine

2024-03-29 18:29 UTC, Carraro-Riccardo requested changes

2024-03-29 18:29 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Tale strategia prevede l'esecuzione di test di unità, di integrazione e di regressione negli ambienti locali di sviluppo e nel repository centrale, tramite GitHub Actions.
Non abbiamo test di regressione

2024-03-29 18:29 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +
Prima di arrivare in PR, credo sia bene menzionare che il codice software prodotto debba prima superare i test in locale e poi allora si procede con il creare la PR

2024-03-29 18:29 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +
Durante il processo di integrazione, dato che si menzionano le github actions, potrebbe essere valido anche menzionare coveralls e il rimando al processo di qualità (dato che alla fine si tratta di un GHA con lo scopo di soddisfare un requisito di qualità)

2024-03-29 18:29 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +La tracciabilità tra gli elementi del sistema software, la PR associata, e i requisiti avviene per mezzo di Jira. I ticket direttamente associabili ad un requisito ne riportano il codice identificati
PR -> pull request

2024-04-02 15:18 UTC, Carraro-Riccardo approved these changes

2024-04-02 19:16 UTC, AlessioBanzato approved these changes

2024-04-02 19:17 UTC, merged