DOC-655 Estendere sezione Desing Pattern
Error-418-SWE/Documenti pull request #408
Opened 2024-03-28 00:32 UTC by Carraro-Riccardo

### Note
DOC-655
Chiude anche DOC-656

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-28 10:20 UTC, ggardin requested changes
Mi sembra molto bene, solo qualche piccolezza

2024-03-28 10:20 UTC, giogardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +=== Nextjs Server Actions
Next**.**js

Fai un ctrl+h perché è un errore ripetuto.

2024-03-28 10:20 UTC, giogardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Quando viene richiamata una server action, Next.js può restituire sia l'interfaccia utente aggiornata sia i nuovi dati in un'unica risposta, integrandosi perfettamente con l'architettura cahcing and
- typo in _caching_
- non è chiara cosa sia l'architettura "[caching and revalidating di Next.js](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating)", ma non mi dilungherei troppo. Semmai puoi sempre mettere il link alla docs, compresa l'indicazione di ultima visita

2024-03-28 10:20 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Interfaccia imlplementata*
Typo in **implementata**

2024-03-28 10:20 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +rappresenta il prodotto da gestire in magazzino.
R maiuscola

2024-03-28 10:20 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +    - *toDomain*: metodo astratto che definisce la logica di mappatura dei dati JSON recuperati dal database in oggetti di businness.
"Business" va con una "n". Fai anche qui ctrl+h che è un errore facile da ignorare durante la lettura

2024-03-28 10:20 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Il Factory Pattern utilizzato insieme allo Strategy Pattern permette di gestire la possibilità di cercare specifici prodotti e specifiche zone. Disponendo infatti di famiglie diverse di algoritmi per
Il Factory Pattern**,** (virgola) utilizzato insieme allo Strategy Pattern**,** (virgola)

2024-03-28 10:20 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Questo pattern è derivativo dall'utilizzo di React e Nextjs, che permettono di utilizzare le Context API per la gestione dello stato dell'applicazione.
Qui forse spenderei qualche parola in più sul perché sia derivativo e sul cosa siano le Context API di React.

2024-03-28 10:20 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Gli oggetti di modello vengono passati come parametri ai componenti Three.js per la loro creazione, rendendo dunque indipendente la rappresentazione grafica dall'oggetto di modello.
Credo sia più corretto dire che è l'oggetto di modello ad essere indipendente dalla rappresentaizone grafica

2024-03-28 10:20 UTC, ggardin commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Mediante l'utilizzo dei framework \@react-three/fiber e \@react-three/drei, è possibile creare facilmente elementi 3D all'interno di un'applicazione React trattando gli elementi come componenti.
~FACILMENTE~ un cazz ahahahah

2024-03-28 10:54 UTC, AlessioBanzato requested changes
Contenuto ottimo, le cose segnate sono solo dettagli

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
>  - Ogni livello dell'archiettetura crea un livello di astrazione che permette di perseguire _separation of concerns_ e di rendere il software più manutenibile e scalabile;
Metterei "**la** _separation of concerns_"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +=== Nextjs Server Actions
*Next.js

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +L'accesso al database avviene mediante Server Actions, feature offerta da Nextjs che permette la definizione di codice eseguibile solamente lato server senza eseguire operazioni di fetch tipiche dell
- *Next.js;
- virgola dopo "lato server".

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Quando viene richiamata una server action, Next.js può restituire sia l'interfaccia utente aggiornata sia i nuovi dati in un'unica risposta, integrandosi perfettamente con l'architettura cahcing and
- *Server Action;
- *caching;
- metterei in corsivo _caching and revalidating_.

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Le server action sono del tutto analoghe all'utilizzo di una funzione all'interno del codice, ma con la differenza che la sua esecuzione avviene lato server, mediante una chiamata POST interamente ge
*Server Actions

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +=== Server Actions implementate
Un paio di cose che farei in tutto l'elenco di Server Actions:
- aggiungere i due punti su tutti i "risultati";
- punto e virgola alla fine di tutti gli elementi "Esito positivo".

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +    - *Esito positivo: * JSON contenente lista dei _bin_ presenti nel database.
Togliere corsivo da "bin"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- La separazione tra la logica di business e la logica di accesso ai dati semplifica la manutenzione e il testing del codice;
Punto alla fine

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Interfaccia imlplementata*
*implementata

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +      - *risultati*
Due punti dopo "risultati"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +      - *risultati*
Due punti dopo "risultati"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *Metodi*
Due punti dopo "Metodi"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +L'interfaccia `DataMapperInterface` è implementata dalle seguenti classi:
Indicazioni valide per tutta la lista di repository:
- due punti dopo "Metodi";
- cambiare le occorrenze di "ottenere (tutte) le ... " -> "ottiene (tutte) le ...".

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *Metodi*
Due punti dopo "Metodi"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Classi implementate*
In tutte e tre le classi, due punti dopo "Metodi"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Le classi del Business layer rappresentano gli oggetti di interesse per l'applicazione. Queste classi rappresentanti il modello di dominio dell'applicazione devono risultare indipendenti dalle tecnol
Da "Queste classi" è una ripetizione:
- della frase precedente, per il discorso su cosa rappresentano le classi;
- della descrizione del business layer fatta prima, per l'indipendenza dalle tecnologie di persistenza e presentazione.

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  La lettera corrispondente alla colonna fa riferimento ad una mappatura per cui "A" equivale alla colonna zero e viene incrementata seguendo i caratteri dell'alfabeto inglese con l'aumentare del num
- Virgola dopo "zero";
- Non è indentato perfettamente, forse bisogna inserire un tab in più.

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Attributi*:
Per ogni attributo, su "tipo":
- usare il `monospace`;
- mettere il punto e virgola.

Usare `monospace` anche su "visibilità"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  Dopo la lettera "Z" viene utilizzato "AA" proseguendo con la logica descritta;
Anche qui penso serva un tab in più

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *descrizione*: enum `BinState` che identifica lo stato di un bin contestualmente alla richiesta di spostamento dei prodotti.
Scriverei "enumerazione", o se vuoi lasciare "enum" lo metterei in monospace

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *obiettivo*: Metodo che permette di assegnare il valore `null` all'attributo `product`.
- Toglierei "Metodo che";
- Punto e virgola alla fine.

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *parametri*: nessuno.
Punto e virgola

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo di ritorno*: void.
`void`, in monospace

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Attributi*:
Come per Bin, per ogni attributo, su "tipo":

- usare il monospace;
- mettere il punto e virgola.

Usare monospace anche su "visibilità"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *descrizione*: enum `ZoneOrientation` che identifica l'orientamento della zona rispetto all'asse X.
Scriverei "enumerazione", o se vuoi lasciare "enum" lo metterei in monospace

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo*: boolean.
Qui non va punto e virgola ma i due punti

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +- Setter:
In grassetto e con la "s" finale

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *setXCoordinate*:
Scriverei i setters come sono scritti per Bin, quindi:

"Setters presenti per gli attributi `xcoordinate` e `ycoordinate`."

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *obiettivo*: ottenere il bin corrispondente al codice identificativo univoco;
"... corrispondente **a un** codice ..."

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo di ritorno*: `Bin` corrispondente al codice identificativo univoco o NULL.
- Specificherei "codice identificativo univoco **fornito**";
- `null`, minuscolo  in monospace.

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Attributi*:
Come per Bin, per ogni attributo, su "tipo":

- usare il monospace;
- mettere il punto e virgola.

Usare monospace anche su "visibilità"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Attributi*:
Come per Bin, per ogni attributo, su "tipo":

- usare il monospace;
- mettere il punto e virgola.

Usare monospace anche su "visibilità"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Attributi*:
Come per Bin, per ogni attributo, su "tipo":

- usare il monospace;
- mettere il punto e virgola.

Usare monospace anche su "visibilità"

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *Metodi*
Due punti

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +      - *parametri*: `URLSearchParams` che rappresenta i parametri per la creazione dell'oggetto `Floor`.
Punto e virgola alla fine

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +      - *tipo di ritorno*: Promise contente l'oggetto `Floor`creato.
Aggiungere uno spazio dopo `Floor`

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Lo strategy pattern permette di definire una famiglia di algoritmi, incapsularli e renderli intercambiabili. Questo pattern permette di variare l'algoritmo indipendentemente dal contesto in cui viene
*Strategy Pattern

2024-03-28 10:54 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Componenti implementati*
- Anche qui nei "tipo" serve il monospace;
- Rivedere l'uso della punteggiatura negli elenchi da qui alla sezione Three.js, in quella sezione mi pare siano tutto a posto .

2024-03-28 13:49 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *setXCoordinate*:
Ho preferito ampliare quelli di Bin

2024-03-28 14:31 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Mediante l'utilizzo dei framework \@react-three/fiber e \@react-three/drei, è possibile creare facilmente elementi 3D all'interno di un'applicazione React trattando gli elementi come componenti.
😂

2024-03-29 08:05 UTC, AlessioBanzato submitted a review, later dismissed
Solo qualche punto/punto e virgola, il contenuto va bene

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +    Next.js caching and revalidating.
Togliere il punto a fine caption

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +Le Server Action sono del tutto analoghe all'utilizzo di una funzione all'interno del codice, ma con la differenza che la sua esecuzione avviene lato server, mediante una chiamata POST interamente ge
- *Actions;
- "... la ~~sua~~ **loro** esecuzione...".

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *risultati; *
Due punti, non punto e virgola

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo di ritorno*: intero che rappresenta il numero dell'ultimo livello `number`;
Punto

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo*: BinState.
- Monospace;
- Punto e virgola.

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo di ritorno*: intero che rappresenta il numero dell'ultima colonna `number`;
Punto

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo*: `string`.
Punto e virgola

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo*: `string`.
Punto e virgola

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo*: `string[]`.
Punto e virgola

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +*Attributi*:
Punto e virgola alla fine di ogni "tipo"

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo*: `string`.
Punto e virgola

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *tipo*: SVG.
- Monospace;
- Punto e virgola.

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +        - *query : string*: stringa da cercare;
Punto

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +        - *query : string*: stringa da cercare;
Punto

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +        - *query : string*: stringa da cercare;
Punto

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +        - *query : string*: stringa da cercare;
Punto

2024-03-29 08:05 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
>  L'interfaccia utente è realizzata mediante elementi importati da Shadcn-UI e componenti personalizzati.
*shadcn/ui

2024-04-02 15:47 UTC, ggardin approved these changes

2024-04-02 15:51 UTC, merged