DOC-641 Redigere verbale interno 24/03/2024
Error-418-SWE/Documenti pull request #412
Opened 2024-03-28 17:20 UTC by AlessioBanzato

### Note

Mancano:
- discussione metriche;
- pianificazione.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-28 20:06 UTC, TodescoMattia submitted a review, later dismissed
per il momento ho trovato solo una cosina, riguardo bene poi quando è completato

2024-03-28 20:06 UTC, TodescoMattia commented on 3 - PB/Documentazione interna/Verbali/24-03-24/24-03-24.typ
> +Sono state concluse l'aggiornamento e l'estensione del documento, il quale è stato mandato in revisione al #cardin dopo un ultimo controllo da parte dei membri del gruppo.
Sono stati conclusi (credo vada il maschile in questo caso)

2024-03-29 18:02 UTC, ggardin commented
@AlessioBanzato, approfitto del fatto che il documento sia in stesura per suggerire che magari potremmo inserire, in pianificazione o devo ritieni, il fatto che il meeting successivo (quello di domani) venga anticipato per festività

2024-04-03 06:05 UTC, ggardin commented
@AlessioBanzato @TodescoMattia qual è lo status del documento? È pronto per il merge?

2024-04-03 06:53 UTC, AlessioBanzato commented
> @AlessioBanzato @TodescoMattia qual è lo status del documento? È pronto per il merge?

Mancano ancora le parti che ho indicato in nota

2024-04-07 08:16 UTC, ggardin requested changes

2024-04-07 08:16 UTC, giogardin commented on 3 - PB/Documentazione interna/Verbali/24-03-24/24-03-24.typ
> +Durante lo Sprint 20 sono state completate buona parte delle task previste, ed è stato quasi concluso lo sviluppo del MVP.
**È stata completata** buona parte delle task

2024-04-07 08:16 UTC, giogardin commented on 3 - PB/Documentazione interna/Verbali/24-03-24/24-03-24.typ
> +- rimozione sezione requisiti di sistema e hardware, lasciando solo i requisiti riguardanti i browser;
Aggiungerei "poiché ritenuti di scarso interesse per l'utilizzatore finale" o qualcosa di simile, per far capire il ragionemento che c'è dietro

2024-04-22 09:50 UTC, ggardin approved these changes
Ottimo.

2024-04-22 10:26 UTC, merged