DOC-648 Creare tabella tracciamento test-risultato
Error-418-SWE/Documenti pull request #418
Opened 2024-03-29 10:48 UTC by FakeDaemon

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-03-29 11:29 UTC, ggardin requested changes

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +In questa sezione vengono elencati i test eseguiti sul prodotto che, come riportato in #ndp_v, possono essere:
~vengono~ sono

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-1.1],[*Bin*: verifica che il metodo `getId()` ritorni correttamente l'Id del bin],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-1.8],[*Bin*: verifica che il metodo `setId()` modifichi correttamente l'Id del bin],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-3.1],[*Order*: verifica che il metodo `getId()` ritorni correttamente l'Id dell'ordine],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-4.1],[*Product*: verifica che il metodo `getId()` ritorni correttamente l'Id del prodotto],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-5.1],[*Zone*: verifica che il metodo `getId()` ritorni correttamente l'Id della zona],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-5.9],[*Zone*: verifica che il metodo `getBin()` ritorni correttamente il bin cercato tramite id valido],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-5.10],[*Zone*: verifica che il metodo `getBin()` ritorni correttamente undefined quando il bin cercato ha Id non valido],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-2.1],[*getBinById*: verifica che venga correttamente restituito il bin cercato per Id da database],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-4.1],[*getProductById*: verifica che venga correttamente restituito il prodotto cercato per Id da database],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-5.2],[*productRepository*: verifica che venga correttamente restituito il prodotto cercato per Id],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-5.4],[*productRepository*: verifica che venga correttamente gestito un errore quando si vuole restituire un prodotto cercato per Id],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-5.6],[*productRepository*: verifica che venga correttamente restituito null quando non vengono trovati prodotti cercando per Id],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-6.3],[*zoneRepository*: verifica che venga correttamente restituita la zona cercata per Id], [P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-6.5],[*zoneRepository*: verifica che venga correttamente gestito un errore quando si vuole restituire una zona cercata per Id],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-6.7],[*zoneRepository*: verifica che venga correttamente restituito null quando non viene trovata la zona cercata per Id],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-12.1],[*getBinsByZoneId*: verifica che vengano correttamente ritornati tutti i bin dato l'Id di una zona],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-13.1],[*getZoneById*: verifica che venga correttamente ritornata la zona cercata per Id e i suoi bin],[P],
ID e non Id

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [I-1.2],[*getAllBins*: verifica che venga correttamente restituito null se si verifica  un errore],[P],
null tra backtick

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-5.8],[*Zone*: verifica che il metodo `isNSOriented()` ritorni correttamente true se la zona ha orientamento nord-sud],[P],
true tra backtick

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-3.3],[*Order*: verifica che il metodo `getEndPoint()` ritorni correttamente il bin di arrivo dell'ordine],[P],
~arrivo~ destinazione

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +
Riga vuota da eliminare

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +
Riga vuota da eliminare

2024-03-29 11:29 UTC, ggardin commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +
Riga vuota da eliminare

2024-03-30 12:50 UTC, AlessioBanzato requested changes

2024-03-30 12:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +- `I`: test di integrazione;
Punto alla fine

2024-03-30 12:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-2.5],[*Floor*: verifica che il metodo `getSVG()` ritorni correttamente l'SVG del piano
Metterei "\\" a fine riga così da visualizzare meglio i due elementi

2024-03-30 12:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-2.6],[*Floor*: verifica che il metodo `getSVG()` ritorni correttamente l'SVG del piano
Metterei "\\" a fine riga così da visualizzare meglio i due elementi

2024-03-30 12:50 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [U-2.7],[*Floor*: verifica che il metodo `getSVG()` ritorni correttamente l'SVG del piano
Metterei "\\" a fine riga così da visualizzare meglio i due elementi

2024-04-02 12:37 UTC, ggardin approved these changes

2024-04-02 19:01 UTC, AlessioBanzato approved these changes

2024-04-02 19:02 UTC, merged