DOC-105 Scritto il verbale interno 23-11-23
Error-418-SWE/Documenti pull request #42
Opened 2023-11-24 21:38 UTC by ZacconeRosario

Link alla issue di Jira: https://error418swe.atlassian.net/browse/DOC-105?atlOrigin=eyJpIjoiM2IyMDU4ZGE3YTRlNDk3NmEwMTc3M2MxM2JkZGI4OWUiLCJwIjoiaiJ9

Note: n.d.

### ✏️ Checklist

- [x] documento testato;
- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-11-24 21:52 UTC, ggardin requested changes
Ottimo lavoro. Prova a vedere il mio commento riguardo il paragrafo di suddivisione dei compiti e fammi sapere che ne pensi, grazie

2023-11-24 21:52 UTC, ggardin commented on 2 - RTB/Documentazione interna/Verbali/Interni/23-11-23/23-11-23.typ
> +Si è stati molto soddisfatti riguardo il lavoro fatto sull'individuazione degli use case e sulle spiegazioni ricevute dal referente esterno riguardo chiarimenti tecnici e compatibilità con diversi de
*deciso

2023-11-24 21:52 UTC, ggardin commented on 2 - RTB/Documentazione interna/Verbali/Interni/23-11-23/23-11-23.typ
> +Sono stati individuati tre documenti da completare e/o aggiornare: Analisi dei Requisiti, Norme di Progetto, Piano di Progetto. I vari documenti sono stati assegnati ai diversi componenti del team.
Direi "Si è ribadita l'importanza di completare in tempi brevi il documento di Analisi dei Requisiti. È inoltre necessario aggiornare le Norme di Progetto in vista delle prossime attività di analisi e di realizzazione del PoC. Infine, il consuntivo dello Sprint 2 non è ancora stato inserito nel Piano di Progetto. I vari documenti risultano in fase di redazione."

Secondo te può aver senso?

2023-11-24 23:06 UTC, ZacconeRosario commented on 2 - RTB/Documentazione interna/Verbali/Interni/23-11-23/23-11-23.typ
> +Sono stati individuati tre documenti da completare e/o aggiornare: Analisi dei Requisiti, Norme di Progetto, Piano di Progetto. I vari documenti sono stati assegnati ai diversi componenti del team.
Sì, anche se piuttosto che "tempi brevi" scriverei "tempi ragionevoli", per non dare l'idea di un' Analisi dei Requisiti scritta di fretta

2023-11-26 17:00 UTC, ggardin approved these changes

2023-11-26 17:01 UTC, ggardin approved these changes
Tutto ok

2023-11-26 17:01 UTC, merged