DOC-682 Riorganizzare paragrafo tecnologie
Error-418-SWE/Documenti pull request #428
Opened 2024-04-04 10:02 UTC by Carraro-Riccardo

### Note
DOC-682

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-04-04 13:03 UTC, AlessioBanzato requested changes
A parte la micro cosa che ho segnato, il contenuto va bene.

Secondo voi le definizioni le teniamo qui? Avevo pensato altrimenti di spostarle tutte nel Glossario e tenere nella ST solo le altre informazioni, come avevi proposto anche te @ggardin mi pare. Anche perché nel Glossario alcune tecnologie sono già state definite

2024-04-04 13:03 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Specifica Tecnica/Specifica Tecnica.typ
> +  - *Immagini Docker utilizzate*
Mancano i due punti

2024-04-04 13:37 UTC, Carraro-Riccardo commented
> A parte la micro cosa che ho segnato, il contenuto va bene.
> 
> Secondo voi le definizioni le teniamo qui? Avevo pensato altrimenti di spostarle tutte nel Glossario e tenere nella ST solo le altre informazioni, come avevi proposto anche te @ggardin mi pare. Anche perché nel Glossario alcune tecnologie sono già state definite

Sì allora, io le avevo inserite anche per dare maggiore contesto durante la spiegazione, ma se mi dite che preferite rimuoverle totalmente mi adeguo, Imo, 2 righe nel documento non fanno male

2024-04-04 15:03 UTC, ggardin requested changes
Così strutturato mi piace. Sposterei però Tailwind CSS sotto, magari prima di shadcn/ui perché averlo prima di Next.js è un po' bruttino imho.

Inoltre sarebbe Docker Compose (senza dash), ma non so se valga la pena correggere.

Edit: @Carraro-Riccardo @AlessioBanzato leggendo il documento credo che le descrizioni ci stiano bene perché contestualizzano la tecnologia specifica.

2024-04-04 15:17 UTC, AlessioBanzato approved these changes

2024-04-07 12:46 UTC, giogardin approved these changes

2024-04-07 12:47 UTC, merged