DOC-715 Redigere sezione test di accettazione
Error-418-SWE/Documenti pull request #443
Opened 2024-04-15 12:44 UTC by Carraro-Riccardo

### Note
DOC-715

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-04-15 13:38 UTC, AlessioBanzato requested changes
Mi pare ci sia solo questo da correggere

2024-04-15 13:38 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +La suite di test di accettazione ha lo scopo di verificare che il prodotto soddisfi quanto atteso dal Proponente. Tali test sono stati svolti manualmente in occasione dei regoli meeting esterni tenut
*regolari meeting

2024-04-15 13:38 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/acceptanceTest.json
> +	   "descrizione":"Deve essere possibile effettuare operazioni di zoom in e zoom out all'interno dell'ambiente tridimensionale",
*zoom-in e zoom-out

2024-04-15 13:38 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/acceptanceTest.json
> +	   "descrizione":"Deve essere possibile richiedere la creazione di un ordine di movimentazione di un prodotto da un bin ad un altro mediante un'operazione di drag n drop. La possibilità di effettuar
*_drag n drop_, in corsivo

2024-04-15 16:47 UTC, FakeDaemon commented
Per me va bene, @AlessioBanzato appena approvi mergia pure. 
@Carraro-Riccardo se riesci l'unica cosa se riesci, rimuovi la doppia riga ripetuta sul log, data dall'ultima pr che per sbaglio abbiamo approvato in due.

2024-04-16 07:55 UTC, AlessioBanzato approved these changes

2024-04-16 07:57 UTC, merged

2024-04-16 07:57 UTC, AlessioBanzato commented
> Per me va bene, @AlessioBanzato appena approvi mergia pure. @Carraro-Riccardo se riesci l'unica cosa se riesci, rimuovi la doppia riga ripetuta sul log, data dall'ultima pr che per sbaglio abbiamo approvato in due.

L'ho eliminata io