DOC-716 Redazione verbale 24-04-15
Error-418-SWE/Documenti pull request #444
Opened 2024-04-15 15:49 UTC by SilvioNardo

### Note
La PR è in draft poiché sono in TODO le sezioni dipendenti da dati non ancora disponibili.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-04-21 20:21 UTC, AlessioBanzato requested changes

2024-04-21 20:21 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +Il giorno mercoledì 10/04/2024 si è svolto lo sportello di valutazione PB con il professor Cardin, il quale esito non ci è stato ad oggi comunicato.
*il _cui_ esito non ~~ci~~ è stato ad oggi comunicato

2024-04-21 20:21 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +Come previsto, le ore di lavoro svolte in questo sprint sono state minori rispetto agli sprint precedenti in quanto è ridotto il lavoro rimanente per completare il progetto.
"S" maiuscola in "Sprint"

2024-04-21 20:21 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +Il documento è stato nuovamente revisionato dai capitolo 5.5 a 5.9.
*capitoli

2024-04-21 20:21 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +Le modifiche al documento sono state:
Cambierei in "Sono state apportate le seguenti modifiche al documento:"

2024-04-21 20:21 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +- CPI di progetto a 1.01, rappresenta un valore ottimale (dove l'ottimabilità è rappresentata da valori $>=1$);
Sostituirei la parte tra parentesi con "... ottimale in quanto `$>=1$`"

2024-04-21 20:21 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +Persiste una buona collaborazione tra i membri del gruppo e il ritmo di lavoro rimane soddisfaciente nonostante la sua preventivata riduzione.
*soddisfacente

2024-04-21 20:21 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Verbali/24-04-15/tasks.json
> +	  "Descrizione": "Aggiornare requisiti di sistema manuale utente.",
Togliere il punto alla fine della descrizione di ogni task

2024-04-22 15:07 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +Il giorno mercoledì 10/04/2024 si è svolto lo sportello di valutazione PB con il professor Cardin, il quale esito non ci è stato ad oggi comunicato.
usare la variabile \#cardin al posto di Professor Cardin

2024-04-22 15:07 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +Il documento è stato nuovamente revisionato dai capitolo 5.5 a 5.9.
oppure "dal" - "al"

2024-04-22 15:07 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +È stata aggiunta la sezione riguardante l'esecuzione del software e sono stati aggiornati i requisiti di sistema.
Non credo sia ragionevole un commento del genere, dato che il documento sta venendo valutata dal professore al momento in cui scrivi questo verbale. Rimuoverei il punto sulla st, in quanto non dovrebbe più essere soggetta a modifiche

2024-04-22 15:07 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-04-15/tasks.json
> +	  "ID task": "DOC-711",
non credo sia ragionevole evidenziare modifiche a documenti in corso di valutazione del prof

2024-04-22 16:24 UTC, AlessioBanzato approved these changes

2024-04-22 16:39 UTC, Carraro-Riccardo requested changes

2024-04-22 16:39 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +Il rendimento positivo dello Sprint è sostenuto dalle principali metriche esposte dal #pdq\:
metterei \#pdq_v

2024-04-22 16:39 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione interna/Verbali/24-04-15/24-04-15.typ
> +#figure(caption: [Task pianificate per lo Sprint 23.],
task pianificate per lo sprint 24*

2024-04-22 17:56 UTC, Carraro-Riccardo approved these changes

2024-04-22 19:03 UTC, merged