DOC-707 Aggiungere glossario
Error-418-SWE/Documenti pull request #447
Opened 2024-04-17 13:18 UTC by SilvioNardo

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-04-17 14:17 UTC, AlessioBanzato requested changes

2024-04-17 14:17 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/glossario_manuale_utente.json
> +	"Ingegneria del Software": {
Non viene mai citata nel documento, quindi toglierei

2024-04-17 14:17 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/glossario_manuale_utente.json
> +	  "description": "File vettoriale di tipo grafico che si allineano agli standard compatibili con il web",
Manca il punto alla fine

2024-04-17 14:17 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/glossario_manuale_utente.json
> +	"Zoom": {
Da togliere, non viene mai utilizzato nel documento, se non per indicare allontamanto/avvicinamento della camera, ma non serve definirlo

2024-04-17 14:17 UTC, AlessioBanzato commented on template_modern.typ
> +show regex(
Scrivo qui perché non saprei dove mettere mano: non è molto bello come viene visualizzato il glossario nell'indice. Forse centrano qualcosa i livelli delle intestazioni, che dovrebbero essere tipo

Glossario dei termini (è una sorta di h1)
B (h2)
Bin (h3)
Browser (h3)

2024-04-17 14:17 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/glossario_manuale_utente.json
> +  }
Forse aggiungerei la definizione di "Zona", tanto per specificare che intendiamo sia scaffale che zona sul pavimento

2024-04-17 14:36 UTC, SilvioNardo commented on 3 - PB/Documentazione esterna/Manuale Utente/glossario_manuale_utente.json
> +	"Ingegneria del Software": {
Per il documento in link ed email compare SWE

2024-04-17 21:04 UTC, SilvioNardo commented on template_modern.typ
> +show regex(
Ho optato per la rimozione dall'indice delle sottosezioni del glossario.

2024-04-18 06:17 UTC, ggardin requested changes

2024-04-18 06:17 UTC, ggardin commented on template_modern.typ
> +let glossary = json("./3 - PB/Documentazione esterna/Manuale Utente/glossario_manuale_utente.json");
Qui va messo solo il nome del file + estensione `glossario_manuale_utente.json`

2024-04-18 06:17 UTC, ggardin commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +// generato dal tempalte
Funziona? Non converrebbe togliere il codice del glossario da `template_modern.typ` e metterlo qui?

2024-04-18 17:37 UTC, SilvioNardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +// generato dal tempalte
funziona, ho scritto le funzioni nel template perché era solo codice e non contenuto testuale quindi mi sembrava più indicato al template più che al .typ di testo.

2024-04-18 17:50 UTC, ggardin approved these changes

2024-04-18 18:26 UTC, AlessioBanzato approved these changes

2024-04-18 18:26 UTC, merged