DOC-717 Ristrutturare metriche piano di qualifica con file JSON
Error-418-SWE/Documenti pull request #449
Opened 2024-04-17 14:04 UTC by Carraro-Riccardo

### Note
DOC-717

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-04-17 16:46 UTC, AlessioBanzato requested changes
In generale io userei `display` per visualizzare meglio sia le `sum` che i `cases`, però ovviamente fai come preferisci

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> += Introduzione
Non so cosa siano tutti questi `^M`. Comunque VSCode non escono, e non danno problemi nel pdf

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +      [Codice], [Metrica], [formula], [Soglia ottimale], [Soglia accettabile],
"F" maiuscola in "Formula"

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +          "descrizione" : "Valore indicante il budget massimo a disposizione del gruppo per lo svolgimento del progetto. Il valore ammonta a € 13.055,00 come stabilito nel documento PDP.",
Sostituire PDP con `#pdp_v`

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +          "formula" : "Definito all'interno del Piano di Progetto",
Sostituire "Piano di Progetto" con `#pdp`

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +          "noteAggiuntive" : "Come stabilito dal regolamento del progetto didattico, tale valore deve essere superiore alla soglia minima di € 12.000 e non superiore a quanto presentato alla candidat
Aggiungere ",00" ai 12k, per uniformare a come hai scritto il nostro BAC

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +        "descrizione": "La metrica PV rappresenta il valore pianificato ovvero il costo preventivato per portare a termine le attività pianificate nello Sprint. Per il calcolo del valore pianificato
- Mettere in grassetto "PV";
- Virgola dopo "rappresenta il valore pianificato";
- Specificare a quale documento ti riferisci in "... secondo quanto definito nel documento.".

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +  result += "Dati: \n";
Se si riesce sarebbe meglio visualizzare la parte "Dati" andando a capo. Come hai fatto te la parola "Dati" viene sulla stessa riga della descrizione e attaccata al punto finale

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +            "formula": "*SPV* $= sum_(r in R) \"OR\"_r * \"CR\"_r$",
Metterei `dot` al posto di `*`

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +                "nome" : "$\"s in S\"$",
Eliminare "`\"`", non viene visualizzata correttamente la math mode

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +        "descrizione" : "La metrica *AC* rappresenta la somma dei costi sostenuti dal gruppo in un determinato periodo di tempo. Tale metrica viene calcolata sia in riferimento all'intero progetto, s
Metterei "... consuntivo dei singoli Sprint."

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +                "nome" : "$\"s in S\"$",
Anche qui togliere "`\"`"

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +        "descrizione" : "L'Earned Value rappresenta il valore guadagnato dal progetto in un determinato periodo di tempo. Tale metrica viene calcolata sia in riferimento all'intero progetto, sia come
Anche qui metterei "... consuntivo dei singoli Sprint."

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +            "formula" : "*SEV* $= display(\"SPC\"/\"SPP\")*\"SPV\"$",
Userei `dot` al posto di `*`

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +                "nome" : "$\"s in S\"$",
Anche qui togliere "\""

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +        "descrizione": "Il *CPI* rappresenta l'indice di performance del costo, ovvero il rapporto tra il valore guadagnato e il costo effettivo sostenuto. Tale metrica viene calcolata in riferimento
Sostituire la descrizione con quella corretta

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +                    "descrizione" : "Numero di metriche soddisfatte"
"n" minuscola all'inizio

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +                    "descrizione" : "Numero di metriche totali"
"n" minuscola all'inizio

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +            "formula" : "*MS* = $display(\"MS\"/\"MT\")*100$",
Userei `dot` al posto di `*`

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +                "descrizione" : "Ore ruolo"
"o" minuscola all'inizio

2024-04-17 16:46 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +                "descrizione" : "Costo ruolo"
"c" minuscola all'inizio

2024-04-17 19:47 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> += Introduzione
oddio non li vedo

2024-04-17 19:51 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +        "descrizione": "La metrica PV rappresenta il valore pianificato ovvero il costo preventivato per portare a termine le attività pianificate nello Sprint. Per il calcolo del valore pianificato
purtroppo non posso mettere la variabile relativa al nome del documento, perchè proveniendo dal JSON, typest non la riconosce quando fa #eval()

2024-04-17 19:52 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +          "formula" : "Definito all'interno del Piano di Progetto",
purtroppo dal file json non posso usare le variabili

2024-04-17 19:52 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +          "descrizione" : "Valore indicante il budget massimo a disposizione del gruppo per lo svolgimento del progetto. Il valore ammonta a € 13.055,00 come stabilito nel documento PDP.",
purtroppo dal file json non posso usare le variabili

2024-04-17 19:53 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +            "formula": "*SPV* $= sum_(r in R) \"OR\"_r * \"CR\"_r$",
potentissimo

2024-04-18 00:58 UTC, TodescoMattia requested changes
Typo trovati qua e la

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Durante il secondo periodo, il gruppo, come evidenziato dal grafico del primo periodo, si è impegnato ad assorbire la differenza tra *PEV* e *PPV*. Infatti, come è possibile evincere dal gr
*Pressoché

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Durante il secondo periodo di progetto, come supportato anche dalle metriche *CPI* e *PEV*, il gruppo è riuscito a ridurre il valore dell'*EAC* rispetto al *BAC*. Infatti, come si può notar
typo su diminuzione

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Durante il secondo periodo del progetto didattico, data la maggiore confidenza con gli strumenti utilizzati e le automazioni impostate, il gruppo ha potuto mantenere un indice *CPI* sempre
typo su "diminuzione"

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Durante il secondo periodo del progetto didattico, data la maggiore confidenza con gli strumenti utilizzati e le automazioni impostate, il gruppo ha potuto mantenere un indice *CPI* sempre
"assorbimento *della* differenza"

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Durante il secondo periodo del progetto didattico, data la maggiore confidenza con gli strumenti utilizzati e le automazioni impostate, il gruppo ha potuto mantenere un indice *CPI* sempre
"a maggiore disponibilità temporale si è tradotta nella possibilità di individuare/svolgere" non suona bene, basta mettere semplicemente "la maggiore..."

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Come anche per il periodo RTB, i documenti hanno rilevato un maggior numero di errori ortografici nel periodo di maggiore stesura. Nonostante ciò, la maggiore confidenza con la redazione de
3 typo su modifiche in fila

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Come anche per il periodo RTB, i documenti hanno rilevato un maggior numero di errori ortografici nel periodo di maggiore stesura. Nonostante ciò, la maggiore confidenza con la redazione de
typo su all'inizio

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Il gruppo ha raggiunto un livello più che accettabile di Code Coverage pari al 92%. Durante i periodi 16 e 17, dove ancora la codebase era nel suo stadio inziale, la metrica risulta insoddi
typo su iniziale

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Il gruppo ha raggiunto un livello più che accettabile di Code Coverage pari al 92%. Durante i periodi 16 e 17, dove ancora la codebase era nel suo stadio inziale, la metrica risulta insoddi
typo su notevolmente

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Il gruppo ha raggiunto un livello più che accettabile di Code Coverage pari al 92%. Durante i periodi 16 e 17, dove ancora la codebase era nel suo stadio inziale, la metrica risulta insoddi
typo su impattando

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "caption":"Grafico andamento CCV (Codo Coverage)"
typo su Code

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "caption":"Grafico andamento BCV (Branch Converage)"
typo su coverage

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Dall'analisi del grafico è possibile notare l'andamento della metrica _FD_ che indica la percentuale di test falliti sul totale di test implementati. L'obiettivo del processo di testing è q
typo su efficiente

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +        "nome" : "Eastimated at Completion",
typo su estimated

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +                    "descrizione" : "Mandatory Requirements Fullfilled"
typo su fulfilled

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +                    "descrizione" : "Desiderable Requirements Fullfilled"
typo su fulfilled

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +                    "descrizione" : "Optional Requirements Fullfilled"
typo su fulfilled

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> -=== RC (Responsability Count)
la parola corretta tecnicamente è responsibility

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> -      [*Responsability Count*], [$1$], [$1$],
la parola corretta tecnicamente è responsibility

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> -    caption: "Responsability Count"
la parola corretta tecnicamente è responsibility

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +            "nome" : "Responsability Count",
la parola corretta tecnicamente è responsibility

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +            "formula" : "Responsability Count",
la parola corretta tecnicamente è responsibility

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +- *test di accettazione*: svolti assieme al Propoente, per verificare che il prodotto soddisfi quanto atteso.
typo su proponente

2024-04-18 00:58 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +    let delimeter = ";"
credo sia delimiter se ci interessa essere precisi (questo per tutte le sue iterazioni)

2024-04-18 01:02 UTC, TodescoMattia requested changes

2024-04-18 01:02 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/Piano di Qualifica.typ
> +    let delimeter = ";"
Tecnicamente se vogliamo essere precisi qui sarebbe delimiter

2024-04-18 01:02 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +            "nome" : "Desiderable Requirements Coverage",
tecnicamente sarebbe Desirable (vale anche per le iterazioni dopo)

2024-04-18 06:38 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +          "descrizione" : "Valore indicante il budget massimo a disposizione del gruppo per lo svolgimento del progetto. Il valore ammonta a € 13.055,00 come stabilito nel documento PDP.",
Nel `.typ` dell'AdR viene messo questo `#show "#ndp_v": [#ndp_v]` per mostrare le variabili correttamente quando sono importate dal json, non so se anche qui possa funzionare

2024-04-18 14:29 UTC, AlessioBanzato requested changes
Nelle descrizioni delle metriche del prodotto i nomi delle metriche non sono in grassetto, mentre nella sezione precedente lo erano. Vedi te come preferisci uniformare

2024-04-18 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +            "formula" : "*MRC* = $display(\"MRF\"/\"TMR\")*100$",
Sostituire `*` con `dot`

2024-04-18 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/processi.json
> +            "formula": "*PPV* $= sum_(r in R) \"OR\"_r * \"CR\"_r$",
`*` -> `dot`

2024-04-18 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +            "formula" : "*MRC* = $display(\"MRF\"/\"TMR\")*100$",
Per evitare di lasciarti tanti commenti, riporto qui tutti i codici delle metriche dove c'è da sostituire `*` con `dot`:
- [ ] MS2;
- [ ] MS3;
- [ ] MS10;
- [ ] MS11;
- [ ] MS12;
- [ ] MS13.

2024-04-18 14:29 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Piano di Qualifica/metriche/prodotto.json
> +            "noteAggiuntive" : "É necessario precisare che la metrica di code coverage non considera la porzione di codice dedicata all'interfaccia grafica, bensì gli aspetti funzionali come le class
*È

2024-04-19 19:35 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Durante il secondo periodo del progetto didattico, data la maggiore confidenza con gli strumenti utilizzati e le automazioni impostate, il gruppo ha potuto mantenere un indice *CPI* sempre
typo su disposizione

2024-04-19 19:35 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Il gruppo ha raggiunto un livello più che accettabile di Code Coverage pari al 92%. Durante i periodi 16 e 17, dove ancora la codebase era nel suo stadio iniziale, la metrica risulta insodd
typo su notevolmente

2024-04-19 19:37 UTC, TodescoMattia submitted a review, later dismissed
trovati altri 2 typo

2024-04-20 16:39 UTC, ZacconeRosario requested changes

2024-04-20 16:39 UTC, ZacconeRosario commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Durante il secondo periodo di progetto, come supportato anche dalle metriche *CPI* e *PEV*, il gruppo è riuscito a ridurre il valore dell'*EAC* rispetto al *BAC*. Infatti, come si può notar
Nell'RTB abbiamo evidenziato come periodo critico quello relativo alla sessione d'esame festività, qui potrebbe essere consono riportare il periodo della settimana di StageIT

2024-04-20 16:39 UTC, ZacconeRosario commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "RTB":"Gli errori ortografici nella documentazione rispecchiano i periodi in cui i documenti hanno subito la maggior parte delle modifiche. In particolare: \n - *Documentazione esterna*: \n\t - #
il _Glossario_ è stato soggetto a relativamente poche modifiche => relativamente, il _Glossario_ è stato soggetto a poche modifiche

2024-04-20 16:39 UTC, ZacconeRosario commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "RTB":"Gli errori ortografici nella documentazione rispecchiano i periodi in cui i documenti hanno subito la maggior parte delle modifiche. In particolare: \n - *Documentazione esterna*: \n\t - #
sè => sé (cambio di accento)

2024-04-20 16:39 UTC, ZacconeRosario commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Come anche per il periodo RTB, i documenti hanno rilevato un maggior numero di errori ortografici nel periodo di maggiore stesura. Nonostante ciò, la maggiore confidenza con la redazione de
In particolare infatti => Infatti ("in particolare" è stato già scritto precedentemente)

2024-04-20 16:39 UTC, ZacconeRosario commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Come anche per il periodo RTB, i documenti hanno rilevato un maggior numero di errori ortografici nel periodo di maggiore stesura. Nonostante ciò, la maggiore confidenza con la redazione de
La sua redazione è conclusa 
=> La sua redazione è stata completata

2024-04-20 16:39 UTC, ZacconeRosario commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Come anche annunciato durante il secondo colloquio RTB, il gruppo ha impostato il lavoro al fine di coprire non solo i requisiti obbligatori, ma anche quelli desiderabili e opzionali. Il gr
la loro implementazione è terminata => la loro implementazione è stata terminata

2024-04-20 16:39 UTC, ZacconeRosario commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Il gruppo ha raggiunto un livello più che accettabile di Code Coverage pari al 92%. Durante i periodi 16 e 17, dove ancora la codebase era nel suo stadio iniziale, la metrica risulta insodd
i tempi di implementazione dei test è stato notevolemente ridotto => i tempi di implementazione dei test sono stati notevolemente ridotti

2024-04-21 14:59 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Piano di Qualifica/cruscotto/cruscotto.json
> +	   "PB":"Durante il secondo periodo di progetto, come supportato anche dalle metriche *CPI* e *PEV*, il gruppo è riuscito a ridurre il valore dell'*EAC* rispetto al *BAC*. Infatti, come si può notar
Onestamente, data la metrica comunque con un valore positivo non credo sia significativo menzionarlo. Diciamo che non ci sono cali da giustificare.

2024-04-21 16:33 UTC, AlessioBanzato approved these changes

2024-04-22 10:24 UTC, ZacconeRosario approved these changes

2024-04-22 12:02 UTC, TodescoMattia approved these changes

2024-04-22 12:14 UTC, merged