DOC-720 Aggiornare sistema tracciamento delle metriche del Piano di Qualifica
Error-418-SWE/Documenti pull request #450
Opened 2024-04-17 14:23 UTC by Carraro-Riccardo

### Note
DOC-720

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-04-17 14:42 UTC, AlessioBanzato requested changes

2024-04-17 14:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  - `Z` è un numero opzionale che identifica l'eventuale estensione della metrica, come avviene ad esempio per per PV che si estende in SPV e PPV.
C'è un "per" in più

2024-04-17 14:42 UTC, AlessioBanzato commented on 3 - PB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +        - MS11 - BCV (Branch CoVerage).
Punto e virgola

2024-04-17 15:34 UTC, FakeDaemon commented
per me va bene, risolte le conversation di @AlessioBanzato si può approvare

2024-04-18 20:59 UTC, AlessioBanzato approved these changes

2024-04-18 21:00 UTC, merged