DOC-719 Revisione finale MU
Error-418-SWE/Documenti pull request #458
Opened 2024-04-19 01:04 UTC by ZacconeRosario

### Note
Revisione completata, poichè il branch è stato aperto prima della creazione del glossario relativo all'utente, c'è da risolvere un conflitto dovuto a questa aggiunta

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2024-04-22 13:53 UTC, TodescoMattia commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> ++ inserire da tastiera il nuovo valore o modificare quello attuale tramite le freccie di incremento/decremento;
*frecce

2024-04-22 13:54 UTC, TodescoMattia requested changes
typo

2024-04-22 20:06 UTC, Carraro-Riccardo requested changes
Il documento copre bene o male l'intero set di operazioni disponibili. Registro, forma, organizzazione però spesso non sono uniformi: a volte si entra tanto nello specifico (parlando di ogni pulsante e campo presente), altre volte invece è estremamente superficiale ("Informazioni: contiene varie informazioni del prodotto").

Non capisco perchè i numerosi giri di parole tipo "pulsante rosso con la scritta elimina"... basta dire "il Pulsante elimina". Ho capito che parliamo con un utente non informatico, ma...

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>    _#link("https://www.math.unipd.it/~tullio/IS-1/2023/Progetto/C5.pdf")_
lo metto qui perchè non riesco a metterlo più sopra, ma riumuoverei la frase "filtraggio e ricerca delle merci con rappresentazione grafica dei risultati"... non mi è chiaro quella "rappresentazione grafica dei risultati"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  = Requisiti
è corretto che nel manuale utente ci siano riferimenti alla specifica tecnica?

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>    - aprire un browser web e collegarsi all'indirizzo "localhost:3000".
aggiungerei "un browser tra quelli supportati" o comunque metterei un riferimento alla tabella

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>    ],
metterei maiuscola su "qui vengono"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>    ],
Non esiste il pulsante "Prossimo", bensì il pulsante "Avanti"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  === Inizializzazione Planimetria Rettangolare
Uso delle maiuscole non conforme

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  == Avvio e Configurazione dell'ambiente
uso delle maiuscole non conforme

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- definire la larghezza del magazzino (numero maggiore di 0);
indicare che è espressa in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- definire la lunghezza del magazzino (numero maggiore di 0);
indicare che è espressa in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Premere quindi il pulsante *Submit* per procedere alla visualizzazione dell'ambiente 3D, oppure il pulsante *Indietro* per annullare la configurazione e tornare al menù mostrato in @avvio.
Submit -> Conferma

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  === Inizializzazione Planimetria Personalizzata
uso delle maiuscole non conforme

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- inserire la misura del lato maggiore del magazzino, in modo da scalarne correttamente la pianta;
indicare che è espresso in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Premere quindi il pulsante *Submit* per procedere alla visualizzazione dell'ambiente 3D, oppure il pulsante *Indietro* per annullare la configurazione e tornare al menù mostrato in @avvio.
Submit -> conferma

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Il sistema permette quattro diversi tipi di movimento di camera all'interno dell'ambiente: rotazione del piano, zoom-in e zoom-out, spostamento della camera sui due assi (panning) e con le frecce dir
di movimento _della_ camera

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Il sistema permette quattro diversi tipi di movimento di camera all'interno dell'ambiente: rotazione del piano, zoom-in e zoom-out, spostamento della camera sui due assi (panning) e con le frecce dir
dato che il movimento della camera può avvenire anche con wasd e con shift. metterei che il pan della camera può avvebire con mouse eo tastiera.

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Premendo il tasto sinistro e spostando il mouse verso destra è possibile ruotare il piano rispetto alla camera in senso antiorario, muovendolo invece verso sinistra verrà ruotato in senso orario, com
dato che il movimento può avvenire sia verso destra che verso sinistra, metterei nell'immagine il mouse con le frecce da entrambi i lati. Conseguentemente metterei anche l'immagine del piano per la rotazione a sinistra

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Allo stesso modo, spostando il mouse verso il basso è possibile cambiare l'angolazione del piano.
Dato che è stato fatto per la destra (e la sinistra), fare lo stesso anche per l'inclinazione del piano, quindi con immagini annesse.

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>      grid(
mi cringia parecchio leggere "rappresentata da un occhio" o "rappresentata da un cestino". Rivedrei l'intero paragrafo mettendo un elenco puntato e mettendo una mini immagine (tipo icona) del pulsante e in parte la descrizione. del tipo

Ad esso seguono le icone:
- [icona.png] ispeziona zona (porta all'apertura del pannello X descritto nella sezione Y);
- [cestino.png] elimina zona.

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> -  - il pulsante contenente l'icona raffigurante un occhio (@immagini_pulsanti_ispezione_zona (sinistra)) presente nella lista delle zone (@visualizzazione_lista_zone) nella riga corrispondente alla z
metterei al posto di "raffigurante un occhio", l'icona

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- fare doppio click sul cubo rosso presente nell'angolo in basso a sinistra rispetto alla zona, visibile nel caso in cui il cursore del mouse sia sovrapposto a tale zona (@immagini_pulsanti_ispezione
cubo rosso potrebbe diventare "ancora di selezione", e aggiungere il termine al glossario

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>      grid(
cubo rosso potrebbe diventare "ancora di selezione", e aggiungere il termine al glossario anche nella caption dell'immagine

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>      grid(
rivedere la formulazione "l'esecuzione di almeno una delle modalità elencate"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>      grid(
nel punto "ID:" togliere "è"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>    - *Altezza*: numero reale che definisce l'altezza della zona.
aggiungere per tutte e tre le dimensioni che la misura è in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  - codice alfanumerico identificativo univoco del bin (colonna Bin);
mettere tra virgolette il nome della colonna

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  - contenuto del bin ("Libero" se vuoto) (colonna Stato);
mettere tra virgolette il nome della colonna

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  - pulsante per l'ispezione del bin (@ispezione_bin) se non vuoto (colonna Info).
mettere tra virgolette il nome della colonna

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>    - *Elimina*: se premuto permette l'eliminazione della zona (@eliminazione_zona).
c'è un motivo per cui l'immagine è relativa solo al pulsante localizza?

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>      grid(
rivedere la formulazione "l'esecuzione di almeno una delle modalità elencate"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *ID*: codice alfanumerico identificativo univoco del bin, è visualizzato anche come titolo del pannello. È composto da tre valori:
rimuoverei quella "è"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  - una lettera dell'alfabeto inglese che identifica la colonna che lo contiene;
non è sempre una lettera, ma una stringa... potrebbe essere AA, AB, AC....

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  - numero del bin rispetto alla zona che lo contiene.
il numero indica il livello

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  - *Altezza*: numero reale che definisce l'altezza del bin.
indicherei per tutte e 3 che sono dimensioni espresse in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- ricercare il prodotto desiderato dal relativo pannello sulla sinistra tramite il suo `ID` o nome;
quel "sulla sinistra" potrebbe essere fuorviante dato che abbiamo anche dei pannelli sulla sinistra dello schermo per la ricerca etc. Lo rimuoverei

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Selezionando da esso la seconda icona (@icona_lista_prodotti, sinistra), la quale corrisponde alla voce "Prodotti", si aprirà un ulteriore pannello dove sarà possibile visualizzare le liste dei prodo
la quale corrisponde -> corrispondente o relativa a. farlo anche per le altre ricorrenze

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  Ogni riga di tali liste corrisponde ad un prodotto, il quale viene identificato dal suo nome, ed elenca le informazioni relative al suo `ID` e le categorie di cui fa parte.
sarebbe utile un riferimento all'immagine

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
trovare un'alternativa a dire "immagine di un occhio"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- cliccare il pulsante contenente l'icona raffigurante un occhio (@immagini_ispezione_prodotto, sinistra) presente nella lista dei prodotti (@visualizzazione_lista_prodotti) nella riga corrispondente
trovare un'alternativa per "raffigurante un occhio"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +L'esecuzione di almeno una delle modalità elencate permette la visualizzazione, sulla destra dello schermo, del pannello relativo alle informazioni del prodotto di interesse (@immagini_ispezione_prod
rivedere la formulazione "l'esecuzione di almeno una delle modalità elencate"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  - *Altezza*: numero reale che definisce l'altezza del prodotto.
spefcificherei che sono misure espresse in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *Peso*: numero reale che definisce il peso del prodotto.
espresso in kg

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Selezionando da esso la terza icona (@icona_lista_ordini, sinistra), la quale corrisponde alla voce "Ordini di movimentazione", si aprirà un ulteriore pannello dove sarà possibile visualizzare la lis
la quale corrisponde alla -> corrispondente o relativa a

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> ++ premere e tenere premuto il tasto sinistro del mouse per "prendere" il prodotto;
iniziare l'operazione di dragging?
Oppure per "agganciare il prodotto al puntatore del mouse"?

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> ++ spostare il puntatore del mouse per trascinare il prodotto nella posizione desiderata;
specificare "continuando a tenere premuto il pulsante sinistro del mouse"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  == Ricerca zone <ricerca_zone>
potrebbe essere utile un'immagine

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
particolarmente utile un'immagine anche per la ricerca prodotti, dato che si menzionano diverse cose da premere e le loro posizioni.

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *Direzione*: può assumere valore `Nord<->Sud` o `Est<->Ovest` e rappresenta l'orientamento della zona rispetto al piano;
la rappresentazione di nord-sud/est-ovest non è conforme a quanto fatto nella sezione "ispezione zona"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>    - *Altezza*: numero reale che definisce l'altezza della zona. Essa viene mostrata automaticamente come somma delle altezze dei singoli livelli.
indicare che sono dimensioni in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +    - *colonne personalizzate*: tramite l'opzione "Colonne personalizzate" è possibile specificare la *larghezza delle colonne* singolarmente dentro ad un apposito form separando ciascun valore (rapp
le dimensioni delle colonne sono espresse in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> -
quale altro form? è una text area

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>        #align(center, `2 1 3 1.5`)
metterei un'immagine dalla schermata

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>        si sta dichiarando che la zona possiede quattro colonne rispettivamente di larghezza 2, 1, 3 e 1.5.
mettere l'unità di misura

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *aggiunta livelli*: a destra del numero attuale di livelli configurati è presente un pulsante bianco contenente la scritta "Aggiungi", che, se premuto, permette l'aggiunta nell'area sottostante di
evitare espressioni tipo "pulsante bianco", ma mettere un'immagine o ancor meglio l'icona del pulsante incorporata nel testo

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *aggiunta livelli*: a destra del numero attuale di livelli configurati è presente un pulsante bianco contenente la scritta "Aggiungi", che, se premuto, permette l'aggiunta nell'area sottostante di
un'immagine renderebbe meglio il concetto

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *aggiunta livelli*: a destra del numero attuale di livelli configurati è presente un pulsante bianco contenente la scritta "Aggiungi", che, se premuto, permette l'aggiunta nell'area sottostante di
altezza in metri

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Per eseguire tale operazione è possibile interagire con il cubo rosso presente nell'angolo in basso a sinistra rispetto alla zona, visibile nel caso in cui il cursore del mouse venga sovrapposto ad e
cubo rosso potrebbe diventare "ancora di selezione", e aggiungere il termine al glossario

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> ++ premere il tasto sinistro del mouse sopra al cubo descritto;
premere e tenere premuto*

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Durante lo spostamento, la base della zona sarà di colore verde nel caso in cui essa non collida con altri elementi dell'ambiente di lavoro, rossa altrimenti.
"Durante lo spostamento, la base della zona verrà evidenziato in merito alla fattibilità dello spostamento. Lo spostamento risulterà valido se la zona non collide con altre."

Nella caption dell'immagine specificare 
"Spostamento zona valido (sinistra, evidenziato in verde) spostamento non valido per collisione (destra, evidenziato in rosso)"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  Per agevolare il posizionamento di una zona durante la fase di spostamento, è possibile usufruire di una griglia tramite il relativo pannello presente nella parte inferiore destra dello schermo (@imm
fase -> operazione

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  Per agevolare il posizionamento di una zona durante la fase di spostamento, è possibile usufruire di una griglia tramite il relativo pannello presente nella parte inferiore destra dello schermo (@imm
"Nel caso in cui da esso" -> "Se"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  Per agevolare il posizionamento di una zona durante la fase di spostamento, è possibile usufruire di una griglia tramite il relativo pannello presente nella parte inferiore destra dello schermo (@imm
Quando essa è attiva -> se attiva

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  Per agevolare il posizionamento di una zona durante la fase di spostamento, è possibile usufruire di una griglia tramite il relativo pannello presente nella parte inferiore destra dello schermo (@imm
aggiungere dopo "mutlipli del passo selezionato" tra parentesi ("Drag and snap")

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Durante un'azione di modifica di una zona è possibile rimuovere una o più colonne già presenti esclusivamente se:
un'azione -> l'azione

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- contengono solo bin senza prodotti al loro interno;
senza prodotti al loro interno -> vuoti

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- non sono presenti colonne con indice superiore a quello dell'insieme di colonne da rimuovere.
mmmm riformulare in modo più chiaro

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +    ),caption: [Esempio di rimozione colonne],
colonne e di un livello

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Un esempio di rimozione di colonne è presente nell'immagine che segue: nello scaffale di partenza è possibile eliminare al massimo le due colonne vuote a destra e il livello superiore.
forse sarebbe meglio evidenziare nell'immagine le colonne interessate dall'eliminazione

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  Nella parte inferiore del pannello relativo alla visualizzazione delle informazioni di una zona (@ispezione_zona), è presente un pulsante contenente la scritta "Modifica" (@pulsante_modifica_zona).
un pulsante contenente la scritta modifica -> il pulsante Modifica

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Alla sua pressione sarà permesso all'utente di poter modificare alcuni parametri della zona in oggetto: essi sono i medesimi richiesti durante la creazione della zona (@creazione_zona) e seguono gli
di poter modificare i parametri della zona ad eccezione dell'id. I parametri modificabili....

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Per aggiornare l'elemento 3D rappresentante la zona modificata è necessario premere il pulsante "Salva le modifiche alla zona" (@pulsante_salvataggio_modifica_zona).
Direi semplicemente per salvare le modifiche. Poi si può aggiungere che la sua rappresentazione 3D verrà aggiornata di conseguenza.

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- il pulsante rosso contenente la scritta "Elimina" contenuto nella parte inferiore del pannello relativo alla visualizzazione delle informazioni di una zona (@immagini_pulsanti_eliminazione_zona, si
il pulsante Elimina (evidenziato in rosso)

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- il pulsante contenente l'icona raffigurante un cestino (@immagini_pulsanti_eliminazione_zona, destra) presente nella lista delle zone (@visualizzazione_lista_zone) nella riga corrispondente alla zo
icona al posto di "raffigurante un cestino"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Nel caso in cui venisse premuto il pulsante "Elimina" presente in quest'ultimo pannello, verranno rimossi dall'ambiente di lavoro e dalle liste la zona selezionata e tutti i bin in essa contenuti.
L'eliminazione è un'operazione irreversibile, pertanto, viene mostrato un avviso di conferma prima di procedere alla sua eliminazione.

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +// #figure(
rimuovere parti commentate

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *Informazioni*: contiene varie informazioni riguardo il prodotto;
cosa vuol dire "varie"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Premendo il pulsante *Settings* in basso a sinistra dello schermo si aprirà il pannello mostrato in @impostazioni, all'interno del quale troviamo, in ordine:
Settings? Impostazioni

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Premendo il pulsante *Settings* in basso a sinistra dello schermo si aprirà il pannello mostrato in @impostazioni, all'interno del quale troviamo, in ordine:
rimuovere l'uso di forme personali come "troviamo"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *Planimetria*: riporta i valori dimensionali del piano;
quali sono? e specificare l'unità di misura

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Premendo il pulsante *Settings* in basso a sinistra dello schermo si aprirà il pannello mostrato in @impostazioni, all'interno del quale troviamo, in ordine:
contenente le sezioni:

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +  - *Reimposta*: permette di eliminare tutto il lavoro fatto sul piano e tornare alla schermata di @avvio.
permette di tornare alla schermata di configurazione iniziale \@avvio

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Nella sezione "Planimetria" del pannello delle impostazioni è possibile modificare le dimensioni del piano:
quali dimensioni?

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> ++ selezionare la casella contenente la dimensione che si desidera modificare;
mettere un'immagine della sezione relativa all'inserimento delle dimensioni

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> ++ selezionare la casella contenente la dimensione che si desidera modificare;
cosa vuol dire casella? "campo" piuttosto

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Nel caso di modifica di un piano personalizzato, il ridimensionamento non andrà ad influire sul SVG, che manterrà le dimensioni definite in fase di inizializzazione, ma aumenterà la superficie bianca
sul SVG -> sulla piantina rappresentante il file SVG caricato

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +Nel caso di modifica di un piano personalizzato, il ridimensionamento non andrà ad influire sul SVG, che manterrà le dimensioni definite in fase di inizializzazione, ma aumenterà la superficie bianca
aumenterà l'area di lavoro interagibile.

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
immagine sfocata e contiene l'unico scaffale che ha un errore di visualizzazione delle dimensioni 8.79999999

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>    image("./imgs/pulsante_salvataggio_modifiche_zona.png", width: 40%),
immagine sfocata e contiene l'unico scaffale che ha un errore di visualizzazione delle dimensioni 8.79999999

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  <glossario>
Parola BIN: "possono contenere al massimo UN prodotto", non "un tipo di prodotto"

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  \
Da quando è possibile creare, eliminare e modificare i singoli bin?

2024-04-22 20:06 UTC, Carraro-Riccardo commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
>  \
Parola Documentazione: perchè non dire semplicemente "Insieme dei documenti e artefatti prodotti durante la realizzazione del capitolato." al massimo estendere con la definizione di documenti

2024-04-22 21:26 UTC, ggardin commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *aggiunta livelli*: a destra del numero attuale di livelli configurati è presente un pulsante bianco contenente la scritta "Aggiungi", che, se premuto, permette l'aggiunta nell'area sottostante di
Rimosso "bianco", rimane valido il resto del suggerimento

2024-04-23 14:04 UTC, AlessioBanzato commented on 3 - PB/Documentazione esterna/Manuale Utente/Manuale Utente.typ
> +- *Direzione*: può assumere valore `Nord<->Sud` o `Est<->Ovest` e rappresenta l'orientamento della zona rispetto al piano;
Ho messo in quel modo perché in WMS3 è scritto così nella creazione zona, mentre è scritto `EW` e `NS` nell'ispezione

2024-04-23 14:13 UTC, ggardin commented
🎅

2024-04-23 14:13 UTC, closed without merging