DOC-109 Scrivere la sezione Processi di accordo/Fornitura
Error-418-SWE/Documenti pull request #49
Opened 2023-11-28 15:20 UTC by AlessioBanzato

Link alla issue di Jira: https://error418swe.atlassian.net/browse/DOC-109?atlOrigin=eyJpIjoiYWEyZTllZDEwYTI1NDU1ZGFkNmUwNDRlMGE0OTU1NDkiLCJwIjoiaiJ9

Note: Redazione della sezione "Fornitura" interna ai Processi di accordo delle Norme di Progetto

### ✏️ Checklist

- [x] documento testato;
- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-11-28 15:42 UTC, giogardin requested changes
Impianto buono. Ci sono alcune correzioni sintattiche da fare, ed ho alcuni dubbi su certe parti. Eventualmente ci possiamo confrontare velocemente a riguardo

2023-11-28 15:42 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il processo di fornitura ha come obiettivo l'offerta di un prodotto o servizio che soddisfi i requisiti concordati con proponente e committente. Tra quest'ultimi e il fornitore, in questo caso il gru
Tra quest'ultimi e il fornitore ~, in questo caso il gruppo _Error_418_,~ deve essere stabilito un accordo che definisca i requisiti, le tempistiche e i costi da rispettare.

2023-11-28 15:42 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il processo di fornitura ha come obiettivo l'offerta di un prodotto o servizio che soddisfi i requisiti concordati con proponente e committente. Tra quest'ultimi e il fornitore, in questo caso il gru
Prima ~di ciò~ allora, ~lo stesso~ il fornitore ~deve aver~ avrà effettuato un'attenta analisi del progetto proposto e dei rischi annessi alla sua realizzazione, con relative linee guida per mitigarli.

2023-11-28 15:42 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +  - fissare meeting.
Direi più "coordinamento"

2023-11-28 15:42 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ scritta, tramite e-mail, utilizzata per:
scritta, asincrona ~, tramite e-mail,~

2023-11-28 15:42 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ orale, tramite meeting su Zoom, durante i quali si affronteranno:
orale, sincrona ~tramite meeting su Zoom~

2023-11-28 15:42 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il dialogo tra il gruppo _Error_418_ e il proponente dovrà essere attivo e frequente fino al termine del progetto didattico, in modo che si riescano a raccogliere più feedback possibili riguardo la c
Indicare il riferimento alla sezione Processi di gestione dell'infrastruttura. Ad esempio immagino che potrebbe essere così: "La comunicazione avverrà secondo le norme espresse in <3.5.2> (id inventanto)"

2023-11-28 15:42 UTC, ggardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +I meeting avranno cadenza variabile, e saranno fissati al termine di altri incontri oppure via e-mail. Il contenuto di ogni incontro sarà raccolto all'interno del relativo verbale. Ognuno di questi v
Milestone, non baseline (giusto?)

2023-11-28 15:42 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +\
No need to andare a capo manualmente con `\`

2023-11-28 15:42 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +=== Strumenti utilizzati
Queste informazioni non dovrebbero andare in altre sezioni?

2023-11-30 10:27 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il dialogo tra il gruppo _Error_418_ e il proponente dovrà essere attivo e frequente fino al termine del progetto didattico, in modo che si riescano a raccogliere più feedback possibili riguardo la c
Il riferimento ai Processi di gestione dell'infrastruttura intendi inserirlo come qualcosa in più oppure in sostituzione a una frase/parte? In caso sia la seconda opzione, che frase/parte andrebbe a sostituire?

2023-11-30 20:58 UTC, ggardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il dialogo tra il gruppo _Error_418_ e il proponente dovrà essere attivo e frequente fino al termine del progetto didattico, in modo che si riescano a raccogliere più feedback possibili riguardo la c
Nella fattispecie direi qualcosa in più ma forse, come già discusso su Discord, inserirei i riferimenti in un secondo momento. Risolvo la conversazione

2023-11-30 21:01 UTC, ggardin approved these changes

2023-11-30 21:02 UTC, merged