Completamento UC-1 e UC-2
Error-418-SWE/Documenti pull request #54
Opened 2023-11-29 18:28 UTC by Carraro-Riccardo

Link alla issue di Jira:
https://error418swe.atlassian.net/browse/DOC-182?atlOrigin=eyJpIjoiNGQyZmMyNWQ4YjBmNGRkMmI4N2RjZmMzZDRmNzkyOTgiLCJwIjoiaiJ9

https://error418swe.atlassian.net/browse/DOC-183?atlOrigin=eyJpIjoiM2EyMjI5OTJjZjBjNGE3ZThjMzViMjQ4NjJhY2IxNWIiLCJwIjoiaiJ9
Note:
Erroneamente ho completato anche l'uc2
### ✏️ Checklist

- [x] documento testato;
- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-01 10:12 UTC, FakeDaemon requested changes

2023-12-01 10:12 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== UC-1.1.1.1 Visualizzazione errore file privo di informazioni
compilando mi mostra due volte UC 1.1.1.1

2023-12-01 10:12 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== UC-1.1.1.2 Visualizzazione errore informazioni del file incongruenti
compilando mostra due volte UC-1.1.1.2

2023-12-01 10:12 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +\
più che uno spazio inserirei proprio un newpage in modo da visualizzare titolo e immagine insieme

2023-12-01 10:12 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +- l'attività di spostamento di uno scaffale deve essere stata attivata;
non mi suona benissimo come frase, forse è meglio un " deve essere in corso lo spostamento dello scaffale" o "avviata l'attività di spostamento dello scaffale"

2023-12-02 23:55 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== UC-1.1.1.1 Visualizzazione errore file privo di informazioni
![image](https://github.com/Error-418-SWE/Documenti/assets/77143275/be626394-155a-494e-9a0d-ee5d7cf245b2)


Dove esattamente?

2023-12-02 23:56 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== UC-1.1.1.2 Visualizzazione errore informazioni del file incongruenti
Come nella risposta precedente

2023-12-02 23:57 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +\
Si lo avevo notato, ma magari aggiungevamo qualcosa nell'introduzione e quindi non serviva mettere nessun new page... in ogni caso al momento lo metto e in caso in futuro si toglie

2023-12-03 09:46 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== UC-1.1.1.1 Visualizzazione errore file privo di informazioni
![image_2023-12-03_104622088](https://github.com/Error-418-SWE/Documenti/assets/91839513/279a0c92-5aaa-4f17-99e9-bfbf66866d7e)

2023-12-03 09:47 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== UC-1.1.1.1 Visualizzazione errore file privo di informazioni
nel titolo hai messo === UC-1.1.1.2, devi togliere il numero della UC che viene calcolato dalla function

2023-12-03 09:48 UTC, FakeDaemon commented on 2 - RTB/Documentazione esterna/Analisi dei Requisiti/Analisi dei Requisiti.typ
> +==== UC-1.1.1.2 Visualizzazione errore informazioni del file incongruenti
come sopra

2023-12-03 19:31 UTC, merged