DOC-46 Analisi dei rischi
Error-418-SWE/Documenti pull request #61
Opened 2023-12-03 10:22 UTC by ggardin

Link alla issue di Jira: https://error418swe.atlassian.net/browse/DOC-46?atlOrigin=eyJpIjoiYjUyYjg3MjQ0NmRjNGVlYjhlNjJkZDhhNDUzOWNhZjUiLCJwIjoiaiJ9

Note: rischi e loro mitigazione presi da `1 - Candidatura`. Nessuna modifica.

### ✏️ Checklist

- [x] documento testato;
- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-05 10:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Conseguenze: attività non svolte o completate parzialmente determinerebbero uno slittamento della data di consegna e delle scadenze intermedie.;
Da rimuovere il ";" alla fine della frase.

2023-12-05 10:29 UTC, Carraro-Riccardo requested changes
Piccola correzione richiesta.

2023-12-05 10:33 UTC, Carraro-Riccardo commented
Il workflow genera un errore... sembrerebbe riguardante il file .csv

2023-12-05 16:39 UTC, ggardin commented
> Il workflow genera un errore... sembrerebbe riguardante il file .csv

Sì, è dovuto al fatto che il log conteneva 2 righe da 5 colonne. Ho corretto tutto. Si può procedere

2023-12-06 17:13 UTC, Carraro-Riccardo approved these changes

2023-12-06 17:14 UTC, merged