DOC-173 Redazione verbale 23-12-03
Error-418-SWE/Documenti pull request #70
Opened 2023-12-05 16:34 UTC by ggardin

### Note

Verbale un po' più corposo rispetto al solito.
È stata introdotta la tabella delle azioni correttive.

### Checklist

- [x] titolo della PR conforme;
- [ ] designato almeno un verificatore.

2023-12-05 17:41 UTC, ggardin commented
[DOC-173]

2023-12-05 19:19 UTC, ggardin commented
L'ho scritto io, ma nello sprint 4 ero verificatore. Siccome l'autore non può anche essere verificatore, ho assegnato @TodescoMattia come autore e @SilvioNardo come verificatore. A voi la palla

2023-12-06 07:35 UTC, ggardin commented
[DOC-173]

2023-12-06 18:37 UTC, TodescoMattia requested changes
Tutto bene, un paio di errori ortografici e una cosa da discutere su un mio dubbio sulla formulazione della frase.

2023-12-06 18:37 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-03/23-12-03.typ
> +- Presentazione degli dimostratori tecnologici realizzati;
Immagino tu intendessi dei* (?)

2023-12-06 18:37 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-03/23-12-03.typ
> ++ il lavoro sulla Analisi dei Requisiti è stato profondamente rivisto dopo il cambio di ruoli;
forma più corretta sarebbe sull'Analisi dei Requisiti

2023-12-06 18:37 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Verbali/23-12-03/23-12-03.typ
> ++ *importazione SVG*: applicazione basata su _Three.js_ che genera un ambiente 3D a partire da un file SVG standard;
l'ambiente generato è comunque 2D no? nel senso se ricordo bene dal poc di riccardo si vede solo l'immagine 2D inserita in un contesto 3D.

2023-12-09 08:46 UTC, ggardin commented
@TodescoMattia correzione inviata e pronta alla review

2023-12-09 13:23 UTC, TodescoMattia approved these changes
bene!

2023-12-09 13:27 UTC, merged