DOC-39 Documento-Glossario
Error-418-SWE/Documenti pull request #72
Opened 2023-12-06 18:51 UTC by TodescoMattia

### Note

Creazione e implementazione del Glossario. 
Chiedo particolare feedback sul posizionamento del documento all'interno delle cartelle e sul vostro pensiero.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-06 19:00 UTC, TodescoMattia commented
ok ma perchè ora non compila più...

2023-12-07 10:46 UTC, ggardin requested changes
Perdonami, ma non va bene. Ci sono diverse inesattezze, e in generale il documento manca di obiettività e coerenza tra le definizioni

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Un'API (Application Programming Interface) può essere definita come un'interfaccia
~può essere definita~

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Gruppo di attività da completare per un certo obiettivo. All'interno del framework agile
...per _conseguire_ un certo obiettivo

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +implementare e sprint backlog, ovvero la lista di funzionalità da trattare durante lo svolgimento di un particolare sprint.
Metti la spiegazione tra parentesi oppure (meglio) rimanda ad una voce di glossario

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Unità minima (non fissa) di spazio all'interno degli scaffali del magazzino. Lo spazio dello scaffale è suddiviso in aree dette bin che possono ospitare massimo un tipo di merce.
"non fissa" in che senso?

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +implementare funzionalità isolate tra di loro e sviluppate partendo dalla stessa radice.
1. il branch non è indipendente perché deriva dal commit precursore
2. il branch di per sé non implementa funzionalità isolate

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +tecnologici per lo sviluppo esplorativo di un determinato prodotto software.
~esplorativo~

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Un changelog è un registro di tutte le modifiche notevoli apportate a un progetto/documento.
~Un changelog è un~

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Un bug è un'anomalia che porta al malfunzionamento di un software, per esempio producendo un risultato inatteso o errato, tipicamente dovuto a un errore nella scrittura del codice sorgente di un prog
~Un bug è un'~

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Il comando git commit è una delle funzioni principali di Git, esso viene utilizzato per creare un'istantanea delle modifiche effettuate nella cronologia di un progetto Git.
Qui credo sia più utile definire cos'è un commit, non come funziona il comando

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Il committente è la figura che commissiona un lavoro, indipendentemente dall'entità o dall'importo.
Perché specificare "indipendemente da..."?

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Esso può essere una persona fisica oppure una persona giuridica (come ad esempio un ente).
un ente o un'azienda

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Il committente è la figura che commissiona un lavoro, indipendentemente dall'entità o dall'importo.
Il committente può anche essere "interno" aka il gruppo stesso

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Discord è una piattaforma statunitense di VoIP, messaggistica istantanea e distribuzione digitale progettata per la comunicazione tra comunità di videogiocatori. Gli utenti comunicano con chiamate vo
1. No need di dire che è statunitense
2. ~progettata per ...~

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Discord è una piattaforma statunitense di VoIP, messaggistica istantanea e distribuzione digitale progettata per la comunicazione tra comunità di videogiocatori. Gli utenti comunicano con chiamate vo
~come membri di un server~ con membri di uno stesso server

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Docker è un  software  progettato per eseguire processi informatici in ambienti isolabili, minimali e facilmente distribuibili chiamati container Linux, con l'obiettivo di semplificare i processi di
~isolabili~ isolati

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Docker è un  software  progettato per eseguire processi informatici in ambienti isolabili, minimali e facilmente distribuibili chiamati container Linux, con l'obiettivo di semplificare i processi di
~minimali~ non necessariamente

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Docker è un  software  progettato per eseguire processi informatici in ambienti isolabili, minimali e facilmente distribuibili chiamati container Linux, con l'obiettivo di semplificare i processi di
~Linux~

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Zoom è un servizio di videoconferenza basato su cloud che permette di effettuare chiamate video o solo audio e consente di registrare anche le sessioni per essere poi visualizzate in seguito.
~anche~
Metti un punto dopo "audio"

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +WOW è un acronimo che sta per Way Of Working e che potremmo tradurre con “il modo in cui un gruppo decide di lavorare” ed è un elemento fondamentale per aumentare le probabilità di successo di un tea
Questa definizione è un po' tentative, credo si possa migliorare

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Nello sviluppo software, la versione (di un software, programma o applicazione) corrisponde a un determinato stato nello sviluppo di un software secondo l'uso del versioning ("versionamento").Esso è
1. Versione ha senso anche per i documenti
2. stato *dello sviluppo
3. definizione ricorsiva

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Documento redatto da un pubblico ufficiale, o da chi è investito di questa specifica funzione, allo scopo di attestare e ricordare, in forma sintetica ma completa ed esauriente nei dati essenziali, f
PRONTO POLIZIAAAAAAA

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +La documentazione software, in informatica ed in particolare nell'ambito dello sviluppo software, è un testo scritto che accompagna un software, con lo scopo di spiegare quali funzionalità assolve il
~con lo~ allo

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Termine utilizzato per andare ad indicare una specifica funzionalità/caratteristica all'interno del programma sviluppato.
~Termine utilizzato per andare ad indicare una~

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Servizio di hosting per progetti software utilizzato da singoli ed organizzazione.  Il nome deriva dal fatto che "GitHub" è una implementazione dello strumento di controllo versione distribuito Git
~per~ di

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Servizio di hosting per progetti software utilizzato da singoli ed organizzazione.  Il nome deriva dal fatto che "GitHub" è una implementazione dello strumento di controllo versione distribuito Git
Non penso che la storia del nome sia di interesse per T, porrei invece maggiore enfasi sul fatto che si basa su git

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +GitHub Actions è la piattaforma integrata di GitHub per l'integrazione e la consegna continua (Continuous Integration e Continuous Delivery) che consente ai team di sviluppo di automatizzare il fluss
consegna continua = continous delivery, quindi leverei la traduzione italiana e terrei solo CI e CD

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +GitHub Pages è un modo semplice e veloce per rendere operativo un sito internet ed è particolarmente utile nel nostro caso per avere un luogo dedicato in cui esporre la nostra documentazione.
1. ~semplice e veloce~
2. ~un modo~ una piattaforma

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +GitHub Pages è un modo semplice e veloce per rendere operativo un sito internet ed è particolarmente utile nel nostro caso per avere un luogo dedicato in cui esporre la nostra documentazione.
Troppo discorsiva

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +collaborativa integrale dell'applicazione, accessibile con account comune Google.
Integrale? Account comune?

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +La Commissione elettrotecnica internazionale è un'organizzazione internazionale per la definizione di standard in materia di elettricità, elettronica e tecnologie correlate. Molti dei suoi standard s
Il significato dell'acronimo va nella defiizione. La traduzione italiana va con le maiuscole.

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +== Ingengeria del Software
Typo

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Un insieme di principi utilizzati per progettare, sviluppare, mantenere, testare e valutare i software. Le relative tecniche sono utilizzate per informare il processo di
Rivedi questa definizione, è riduttivo dire che è un insieme di principi

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +== ISO (International Organization for Standardization)
Anche qui l'acronimo va nella definizione

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +== ITS (Issue Tracking System)
Anche qui l'acronimo va nella definizione

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Si tratta di un sistema informatico che gestisce e registra delle liste di richieste di assistenza o di problemi, organizzato secondo le necessità di chi offre il servizio.
Assistenza? Non è un sistema di ticketing (anche se Jira fa anche questo)

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +ISO è la più importante organizzazione mondiale che si occupa di definire le cosiddette "norme tecniche" dette anche "norme ISO" oppure "standard ISO".
~mondiale~ internazionale

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +JavaScript Object Notation è un formato per lo scambio dati basato sul linguaggio di programmazione JavaScript.
Falso, non è basato su JS

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +JavaScript Object Notation è un formato per lo scambio dati basato sul linguaggio di programmazione JavaScript.
Wikipedia in italiano andrebbe bannata: https://en.wikipedia.org/wiki/JSON

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Jira è una suite di software proprietari per il tracciamento delle segnalazioni sviluppata da Atlassian, che consente il bug tracking e la gestione dei progetti sviluppati con metodologie agile.
Aggiungerei che è un ITS

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Bene economico trasportabile e stoccabile. All'interno del prodotto vengono visualizzati per ogni tipo diverso di merce eventuali dati rilevanti.
"All'interno del prodotto vengono visualizzati per ogni tipo diverso di merce eventuali dati rilevanti." è un dettaglio implementativo, non c'entra con la definizione

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Il termine milestone viene tipicamente utilizzato nella pianificazione e gestione di progetti complessi per indicare il raggiungimento di obiettivi stabiliti in fase di definizione del progetto stess
~complessi~ per indicare il raggiungimento di obiettivi prestabiliti ~in fase di ... stesso~.

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +== Minimum Viable Product (MVP)
Qui l'acronimo appare tra parentesi, mentre nel resto del documento avviene il contrario

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Il prodotto minimo funzionante è la versione di un prodotto con caratteristiche appena sufficienti per essere utilizzabile dai primi clienti, i quali possono quindi fornire feedback per lo sviluppo f
~primi~

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Node.js è un runtime system open source multipiattaforma orientato agli eventi per l'esecuzione di codice JavaScript di cui gli sviluppatori possono scrivere nuovi moduli nello stesso linguaggio di p
~di cui gli sviluppatori possono scrivere nuovi moduli nello stesso linguaggio di programmazione.~ Gli sviluppatori possono estenderne le funzionalità tramite moduli

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> += T
Manca TypeScript

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> += J
Manca JavaScript

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +== POC (Proof of Concept)
Stessa incoerenza negli acronimi

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Un Proof of Concept si riferisce a una realizzazione incompleta o abbozzata di un determinato progetto o metodo. Il suo scopo è quello di dimostrare la fattibilità o confermare la validità di alcuni
Manca il punto a fine frase

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Azienda/Ente che propone il capitolato d'appalto per il progetto didattico.
Il "progetto didattico" va definito

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +La gestione del rischio o risk management, è la pratica di valutare, prendere decisioni e pianificare tutte le attività necessarie per ridurre al minimo l'impatto negativo della variabilità sugli obi
~La gestione...~ È la pratica

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Un requisito è una condizione o capacità che deve essere verificata o posseduta dla sistema o da un componente del sistema per soddisfare un contratto, uno standard, una specifica o qualsiasi altro d
Typo

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Archivio in cui vengono conservati tutti i file di un progetto sotto forma di metadati
Credo che i metadati siano a corredo del file, mentre così sembra ci siano solo i metadati

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +La revisione dei documenti o del codice è un processo di peer review utilizzato per esaminare il codice/documentazione in modo da individuare i problemi e migliorare la qualità del software.
Ricorsiva

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Elemento presente all'interno del magazzino costituito da uno o più ripiani orizzontali che permettono lo stoccaggio della merce.
Definire ripiano

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Structured Query Language (SQL)  è un linguaggio standardizzato per database basati sul modello relazionale, progettato per le seguenti operazioni: creare e modificare schemi di database; inserire, m
Doppio spazio dopo SQL

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Structured Query Language (SQL)  è un linguaggio standardizzato per database basati sul modello relazionale, progettato per le seguenti operazioni: creare e modificare schemi di database; inserire, m
standard~izzato~

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Scalable Vector Graphics è un formato di file di grafica vettoriale bidimensionale basato sull'XML sviluppato da World Wide Web Consortium. Le immagini SVG possono essere incluse all'interno di una p
"Le immagini SVG possono essere incluse all'interno di una pagina HTML. Possono essere inoltre distribuite in versione compressa utilizzando l'algoritmo gzip." sono informazioni che non definiscono il formato.

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +Typst è un nuovo sistema di composizione basato su markup progettato per essere potente quanto LaTeX pur essendo molto più facile da apprendere e utilizzare.
Riscrivila

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Three.js è una libreria JavaScript cross-browser e un'interfaccia di programmazione dell'applicazione utilizzata per creare e visualizzare grafica computerizzata 3D animata in un browser Web utilizza
Definire WebGL

2023-12-07 10:46 UTC, giogardin commented on 2 - RTB/Glossario/Glossario.typ
> +un template indica un documento o programma nel quale, come in un foglio semicompilato cartaceo, su una struttura generica o standard esistono spazi temporaneamente "bianchi" da riempire successivame
Lettera minuscola a inizio frase

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +un template indica un documento o programma nel quale, come in un foglio semicompilato cartaceo, su una struttura generica o standard esistono spazi temporaneamente "bianchi" da riempire successivame
Anche qui credo si possa fare di meglio

2023-12-07 10:46 UTC, ggardin commented on 2 - RTB/Glossario/Glossario.typ
> +Gli use case consistono nel valutare ogni requisito che l'applicazione deve implementare focalizzandosi sul punto di vista degli attori che interagiscono col sistema, valutandone le varie interazioni
Riscivi anche questa in modo più diretto

2023-12-07 11:38 UTC, ggardin commented
Un'altro miglioramento riguarda la lunghezza delle frasi. Prova a farle un po' più corte 🙏

2023-12-09 08:50 UTC, ggardin approved these changes
Bene!

2023-12-09 08:51 UTC, merged