DOC-191 Redatto preventivo quinto sprint
Error-418-SWE/Documenti pull request #73
Opened 2023-12-07 01:42 UTC by ZacconeRosario

### Note
n.d.

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-07 14:43 UTC, TodescoMattia requested changes
solo un paio di modifiche ma per il resto bene

2023-12-07 14:43 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- svolgere meeting con il professore Cardin in merito all'Analisi dei Requisiti;
è una sciocchezza ma metterei professor* perchè se no suona male

2023-12-07 14:43 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- *Verificatore*: al fine di verificare la correttezza delle modifiche ai documenti, al fine di effettuare un controllo sulla validità e formulazione degli use case individuati e del documento di Ana
il doppio "al fine" secondo me non ci stà, userei un semplice "e di effettuare un controllo...."

2023-12-07 23:01 UTC, ZacconeRosario commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- svolgere meeting con il professore Cardin in merito all'Analisi dei Requisiti;
corretto

2023-12-07 23:01 UTC, ZacconeRosario commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- *Verificatore*: al fine di verificare la correttezza delle modifiche ai documenti, al fine di effettuare un controllo sulla validità e formulazione degli use case individuati e del documento di Ana
corretto anche questo

2023-12-08 00:46 UTC, TodescoMattia approved these changes

2023-12-08 00:47 UTC, merged