Creazione File Domande
Error-418-SWE/Documenti pull request #8
Opened 2023-10-22 16:11 UTC by Carraro-Riccardo

Il file contiene le domande principali sorte durante l'analisi dei capitolati. Ogni membro aggiungerà le rispettive domande.

2023-10-22 16:17 UTC, ggardin commented
Vogliamo procedere con l'aggiunta delle domande a questo branch, oppure uniamo il branch e modifichiamo tramite ulteriori PR?

2023-10-22 16:27 UTC, FakeDaemon requested changes

2023-10-22 16:27 UTC, FakeDaemon commented on 1 - Candidatura/Domande aziende.txt
> +
aggiungere domanda del tipo: quanto è complesso il modello matematico da implementare rispetto alle nostre conoscenze?

2023-10-22 16:27 UTC, FakeDaemon commented on 1 - Candidatura/Domande aziende.txt
> +## C7
aggiungi nome pls

2023-10-22 16:30 UTC, FakeDaemon commented
> Vogliamo procedere con l'aggiunta delle domande a questo branch, oppure uniamo il branch e modifichiamo tramite ulteriori PR?

modifichiamo il file in questo branch e mergiamo solo una volta che il file è completo

2023-10-23 13:43 UTC, ggardin approved these changes

2023-10-23 13:55 UTC, FakeDaemon approved these changes
sgtm

2023-10-23 13:56 UTC, merged