Redigere sezione Technical Management process configuration management
Error-418-SWE/Documenti pull request #92
Opened 2023-12-12 20:25 UTC by Carraro-Riccardo

### Note
https://error418swe.atlassian.net/browse/DOC-141?atlOrigin=eyJpIjoiMGJhZWYzNTUwZDI1NDkxOGJkZTkyZWI5ZjgyNjYzMWYiLCJwIjoiaiJ9

### Checklist

- [x] il documento compila;
- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-13 10:10 UTC, AlessioBanzato requested changes, later dismissed
Contenuto ottimo, ho segnato per la maggior parte typo e un paio di riformulazioni

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +== Processo di gestione dela configurazione
*della

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Lo scopo della Gestione della Configurazione è gestire e controllare gli elementi del sistema e le configurazioni durante il ciclo di vita. Lo scopo principale è tracciare e coordinare le procedure n
"... necessarie alla modifica _della_ documentazione ... "

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Tali informazioni sono salvate in un file CSV, unico per ogni documento. Il file CSV è salvato nella cartella dedicata al documento, denominato _log.csv_, generato automaticamente da una _GitHub Acti
Riformulerei la frase "Il file CSV ... pull request." in:

Questo file, denominato _log.csv_, è salvato nella cartella dedicata al documento a cui si riferisce, e viene generato automaticamente da una _GitHub Action_ invocata all'apertura, riapertura, sinconizzazione e chiususra di una pull request.

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Ogni documento, nella sezione direttamente sottostante all'indice, mostrerà in formato tabellare le informazioni relative al tracciamento delle modifiche, leggendo le informazioni dal file _log.csv_
Toglierei "... presente nella medesima cartella del documento" perché è già stato detto nel paragrafo precedente

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il gruppo per la redazione della documentazione ha deciso di utilizzare Typst come strumento di scrittura e compilazione dei documenti. Alternativa principale a Latex, permette la stesura di document
Il gruppo ~~per la redazione della documentazione~~ ha deciso di utilizzare Typst come strumento di scrittura e compilazione dei documenti

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il gruppo per la redazione della documentazione ha deciso di utilizzare Typst come strumento di scrittura e compilazione dei documenti. Alternativa principale a Latex, permette la stesura di document
*LaTeX

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- docType: tipologia del documento: Verbale, Documento;
"Verbale, documento" lo metterei tra parentesi

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- authros: autori del documento;
*authors

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- isExternalUse: flag che indica se il documento è per uso esterno;
Punto al posto di punto e virgola

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Al fine di semplficare la procedura di creazione di un documento, è stata condiviso un documento di testo denominato Quickstart.txt che contiene la configurazione base per la stesura dei documenti.
*stato

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il gruppo Error_418 ha creato un'organizzazione omonima su GitHub in modo da gestire e separe il lavoro in più repository pensate per scopi e contenuti diversi:
*separare

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- *Docs*: repository contenente la documentazione prodotta;
~~Docs~~ -> Documenti

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- *PoC*: repository contenente i Proof of Concept prodotti;
Punto al posto di punto e virgola

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +      - *Verbali*: contiene i verbali delle riunioni esterne;
*interne

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Docs è la repository dedicata alla documentazione prodotta, la quale possiede due branch principali:
~~Docs~~ -> Documenti

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Docs è organizzata in modo da suddividere la documentazione necessaria alle revisioni esterne che il gruppo dovrà affrontare:
~~Docs~~ -> Documenti

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +IL processo di verifica del documento è accompagnato dall'esecuzione di github actions che si occupano di automatizzare l'aggiornamento del file log.csv con i dati relativi alla modifica apportata, e
*Il

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- apportate le moidifiche, si richiede nuovamente la review per verificare che i cambiamenti apportati siano corretti;
*modifiche

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +L'integrazione con GitHub permette a Jira di lavorare e apportare modifiche direttamente alla repository del gruppo, permettendo la crezione, gestione e chiusura di branch e al conseguente aggiorname
*creazione

2023-12-13 10:10 UTC, AlessioBanzato commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- completata: task conclusa: branch dedicato chiuso a seguito di merge sul ramo principale.
Sostituirei ogni ":" secondario dell'elenco con un punto o una virgola

2023-12-13 14:18 UTC, ggardin approved these changes

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il versionamento è un processo che permette di tenere traccia delle modifiche effettuate su un prodotto software. Per ogni modifica viene creata una nuova versione del prodotto, che viene identificat
Non solo su prodotti software. Noi la utilizziamo anche per i documenti. Chiarirei questo passaggio

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ X: indica il numero di versione principale, aggiornato al cambiamento della struttura del documento;
Spiegherei cosa intendiamo per struttura del documento. Vedi https://semverdoc.org/semverdoc.html

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Y: indica il numero di versione secondaria, aggiornato all'aggiunta/rimozione di paragrafi;
"all'aggiunta _o alla_ rimozione"

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ Z: indica il numero di versione di revisione e correzione, aggiornato a seguito di cambiamenti minimi e correzioni ortografiche.
~e~ _o_ correzioni...

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +L'aggiornamento di una delle cifre del numero di versione, azzera le cifre di rilevanza inferiore.
Senza la virgola.

Espanderei aggiungendo:

``` typst
+ Questo schema descrive il versionamento dei documenti. I documenti prodotti dal gruppo sono descritti nel dettaglio nella sezione @sezione-che-probabilmente-ora-non-esiste.
+ Un normale numero di versione deve avere la forma `X.Y.Z`, dove `X`, `Y` e `Z` sono interi non negativi.
+ Numeri di versione con `X` pari a 0 indicano documenti in lavorazione, da non considerarsi pronti al rilascio.
+ Dopo il rilascio, il contenuto della versione non deve essere modificato. Qualsiasi modifica successiva al rilascio deve causare un cambio nel numero di versione.

```

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Il gruppo per la redazione della documentazione ha deciso di utilizzare Typst come strumento di scrittura e compilazione dei documenti. Alternativa principale a Latex, permette la stesura di document
Il gruppo ~ha deciso di~ utilizza Typst.

Il resto della frase non è rilevante ai fini delle norme.

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Al fine di dare una struttura comune ai documenti si è creato un file Template.typ parametrizzato, sfruttando la possibilità di produrre un file pdf compilando insieme più file typst. Questo file con
- ~file Template.typ~ _modello_ parametrizzato
- PDF in maiuscolo
- Typst con la lettera maiuscola
- se non ti prende troppo tempo wrapperei i parametri con `

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Al momento della creazione di un nuovo documento sarà sufficiente importare il file Template.typ e specificare i parametri sopra elencati.
~il file Template.typ~ modello

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +Al fine di semplficare la procedura di creazione di un documento, è stata condiviso un documento di testo denominato Quickstart.txt che contiene la configurazione base per la stesura dei documenti.
`quickstart.txt`

2023-12-13 14:18 UTC, giogardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +IL processo di verifica del documento è accompagnato dall'esecuzione di github actions che si occupano di automatizzare l'aggiornamento del file log.csv con i dati relativi alla modifica apportata, e
capitalize(GitHub Actions)

2023-12-13 14:18 UTC, ggardin commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> +- merge non richiesto: qualora non si richieda il merge del branch nel ramo src, è sinonimo di aver riscontrato errori o correzioni da apportare al documento a seguito della compilazione, pertanto sa
Punto non chiarissimo. Rif discussione in LabTA

2023-12-13 19:15 UTC, TodescoMattia requested changes

2023-12-13 19:15 UTC, TodescoMattia commented on 2 - RTB/Documentazione interna/Norme di Progetto/Norme di Progetto.typ
> ++ aggiornamento del file log.csv: il file di log viene aggioranato con le informazioni relative alla modifica effettuata: questo passaggio, avvenendo solamente a seguito di review positiva, permette
typo su aggiornato*

2023-12-14 02:04 UTC, TodescoMattia approved these changes

2023-12-14 07:42 UTC, merged