DOC-222 Aggiunto consuntivo quinto sprint
Error-418-SWE/Documenti pull request #93
Opened 2023-12-13 19:26 UTC by SilvioNardo

### Note

### Checklist

- [x] titolo della PR conforme;
- [x] designato almeno un verificatore.

2023-12-13 22:25 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- incontro con Proponente in data 06-12-23;
rimuoverei "mini" e aggiungerei il poc dockerizzato (o dockerizzazione del poc in sostanza)

2023-12-13 22:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- formulare convenzioni più chiare da adottare per il codice;
il primo punto lo riscriverei nella forma "Normare le convenzioni di stesura del codice nelle Norme di Progetto"

2023-12-13 22:28 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- impegnarsi a fissare delle scadenze infrasettimanali così da ridurre il carico di lavoro il weekend;
nel weekend*

2023-12-13 22:36 UTC, Carraro-Riccardo commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +#table(
dato che il preventivo dello sprint 5 era di 545 (seppur non presenta l'assegnazione di programmatori e deve essere corretto dato che avevamo poc in produzione già alla fine dello sprint 4), si può pensare di portare a 2 le ore di programmatore per tutti i programmatori (anzichè 1).

tenendo conto che in settimana sono stati creati e presentati 3 poc, anche eccedere il costo preventivato è comprensibile

2023-12-13 22:38 UTC, Carraro-Riccardo requested changes
Buono per impostazione e contenuto, giusto qualche correzione/aggiunta

2023-12-14 02:02 UTC, TodescoMattia requested changes
buono! mancano solo un paio di formalità

2023-12-14 02:02 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- redazione del glossario;
*Glossario

2023-12-14 02:02 UTC, TodescoMattia commented on 2 - RTB/Documentazione esterna/Piano di Progetto/Piano di Progetto.typ
> +- Normare le convenzioni di stesura del codice nelle Norme di Progetto;
minuscolo

2023-12-14 14:53 UTC, TodescoMattia approved these changes

2023-12-14 18:04 UTC, Carraro-Riccardo approved these changes

2023-12-14 18:05 UTC, merged